FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la TENTE DE COMBAT\nd'AUTEQUIA!\pJe serai votre guide pour le\nTOURNOI K.O.!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous participer à un\nTOURNOI K.O., oui ou non?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Nous espérons que vous relèverez\nbientôt notre défi!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Dans la TENTE DE COMBAT d'AUTEQUIA,\nvous participez à un TOURNOI K.O.\pLes participants s'inscrivent avec une\néquipe de trois POKéMON.\pCes POKéMON doivent être placés dans\nl'ordre dans lequel ils apparaîtront.\pPendant un combat, ils apparaîtront\nl'un après l'autre dans l'ordre\lprédéfini.\pUn POKéMON qui entre au combat doit\ny rester jusqu'à la fin.\pS'il n'y a pas de vainqueur au bout de\ntrois tours, l'ARBITRE intervient.\pSi vous voulez interrompre le défi,\nveuillez sauvegarder la partie.\pSi vous ne sauvegardez pas, vous ne\npourrez pas reprendre ce défi.\pSi vous mettez K.O. trois DRESSEURS de\nsuite, nous vous remettons un prix.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de me suivre dans la TENTE DE\nCOMBAT, vous devez sauvegarder. OK?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "We offer two levels of challenge,\nLevel 50 and Open Level.\lWhich is your choice?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Veuillez choisir les trois POKéMON que\nvous souhaitez inscrire.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Je regrette, cher DRESSEUR!\pVous n'avez pas trois POKéMON\naptes à participer.\pIls doivent aussi tenir des objets\ndifférents.\pLes OEUFS{STR_VAR_1} inaptes au combat.\pRevenez me voir quand vous aurez\nce qu'il faut.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Je regrette, cher DRESSEUR!\pVous n'avez pas trois POKéMON\naptes à participer.\pIl vous faut trois POKéMON différents\npour participer.\pIls doivent aussi tenir des objets\ndifférents.\pLes OEUFS{STR_VAR_1} inaptes au combat.\pRevenez me voir quand vous aurez\nce qu'il faut.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Je vais vous guider dans la\nTENTE DE COMBAT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je regrette, cher DRESSEUR!\pVous n'avez pas sauvegardé avant de\nquitter votre dernier défi.\pDans ce cas, c'est la disqualification.\nQuel dommage!\pBien entendu, vous pouvez recommencer\nun autre défi.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Splendide! Vous avez battu trois\nDRESSEURS à la suite!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Votre résultat va être sauvegardé.\nVeuillez patienter.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour récompenser ces trois victoires\nconsécutives, voici un prix.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} reçoit {STR_VAR_1}\nen récompense.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh, votre SAC est plein.\pVeuillez faire de la place dans votre\nSAC et revenez ensuite me voir.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Merci d'avoir participé!\pVotre résultat va être sauvegardé.\nVeuillez patienter.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Nous attendrons votre prochain défi\navec impatience.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Nous vous attendions!\pVous devez sauvegarder avant d'aller\nplus loin. Veuillez patienter.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la TENTE DE COMBAT\nde VERGAZON!\pNous testons la confiance des\nDRESSEURS envers leurs POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi de la\nTENTE DE COMBAT de VERGAZON?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Dans la TENTE DE COMBAT de VERGAZON,\nune règle importante est ajoutée.\pLes DRESSEURS peuvent seulement\nfaire entrer et sortir leurs POKéMON.\pLes DRESSEURS ne peuvent pas donner\nd'autres ordres à leurs POKéMON.\pLes POKéMON agiront conformément\nà leur nature et se battront seuls.\pVous devez placer votre confiance en\nvos POKéMON et les regarder.\pSi vous réalisez l'exploit de battre\ntrois DRESSEURS à la suite, vous\lrecevrez un prix.\pSi vous voulez interrompre le défi,\nveuillez sauvegarder la partie.\pAssurez-vous de bien sauvegarder, ou\nvous ne pourrez pas reprendre le défi.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Revenez quand vous aurez fortifié\nvotre esprit et vos POKéMON.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\nLevel 50 and Open Level.\lWhich is your choice of a challenge?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Je regrette!\pVous n'avez pas trois POKéMON\naptes à participer.\pIl vous faut trois POKéMON différents\npour participer.\pIls doivent aussi tenir des objets\ndifférents.\pLes OEUFS{STR_VAR_1} inaptes au combat.\pRevenez me voir quand vous aurez\nce qu'il faut.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Je regrette!\pVous n'avez pas trois POKéMON\naptes à participer.\pIl vous faut trois POKéMON différents\npour participer.\pIls doivent aussi tenir des objets\ndifférents.\pLes OEUFS{STR_VAR_1} inaptes au combat.\pRevenez me voir quand vous aurez\nce qu'il faut.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Très bien. Maintenant, veuillez choisir\nvos trois POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant d'entrer dans la TENTE DE COMBAT,\nvotre partie doit être sauvegardée. OK?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Très bien.\nSuivez-moi, je vous prie.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Ce fut un privilège de pouvoir assister\nà un tel combat.\pVotre résultat va être sauvegardé.\nVeuillez patienter.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Trois victoires consécutives…\pLes liens qui unissent votre esprit à\nvos POKéMON sont solides et sincères.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Votre résultat va être sauvegardé.\nJe vous demande de patienter un peu.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour récompenser ces trois victoires\nconsécutives, voici un prix.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la TENTE DE COMBAT\nde POIVRESSEL!\pJe serai votre guide pour le TOURNOI\nCOMBAT ECHANGE.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi du\nCOMBAT ECHANGE?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Dans la TENTE DE COMBAT de POIVRESSEL\nont lieu des COMBATS ECHANGE avec des\lPOKéMON de location.\pVous devez choisir trois POKéMON parmi\nles POKéMON de location.\pEnsuite, vous faites des COMBATS\nSOLO avec ces POKéMON.\pSi vous gagnez, vous pouvez échanger\nl'un des POKéMON de location.\pSi vous gagnez trois combats à la suite,\nvous remportez un prix.\pSi vous voulez interrompre le défi,\nveuillez sauvegarder la partie.\pSi vous ne sauvegardez pas,\nc'est la disqualification.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Nous espérons vous compter parmi\nnos participants une prochaine fois.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\nLevel 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de commencer, votre partie doit\nêtre sauvegardée. OK?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your POKéMON for\nsafekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Entrez, je vous en prie.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Merci d'avoir joué!\pJe vous rends vos POKéMON et reprends\nles POKéMON de location.\pJe dois sauvegarder vos données.\nVeuillez patienter.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your POKéMON in exchange\nfor our rental POKéMON.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Félicitations! Vous avez gagné trois\nCOMBATS ECHANGE à la suite!\pJe vous rends vos POKéMON et reprends\nles POKéMON de location.\pJe dois sauvegarder vos données.\nVeuillez patienter.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Pour récompenser ces trois victoires\nconsécutives, voici un prix.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\nOn dirait que vous n'avez plus de place.\pFaites de la place dans votre SAC et\nrevenez me voir.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Nous vous attendions!\pAvant de reprendre votre défi, vous\ndevez sauvegarder la partie.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je regrette!\pVous n'avez pas sauvegardé avant de\nquitter votre dernier défi.\pDans ce cas, c'est la disqualification.\nC'est dommage!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We'll return your personal POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Au COMBAT ECHANGE, vous ne pouvez\nutiliser que trois POKéMON.\pQu'ils aient été prêtés ou échangés,\nvotre équipe ne peut pas avoir deux\lfois le même POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Vous pouvez échanger un POKéMON avec\nle DRESSEUR que vous venez de battre.\pVous ne pouvez obtenir que les POKéMON\nse trouvant dans son équipe.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "A chaque fois que vous gagnez, vous\npouvez échanger l'un de vos POKéMON\lavec l'un de ceux de votre adversaire.\pVous ne pouvez pas faire d'échange\navec le troisième DRESSEUR.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Voici deux choses à savoir sur les\néchanges de POKéMON.\pAvant l'échange, vous ne pouvez pas\nconnaître les stats du POKéMON\lque vous voulez recevoir.\pLes POKéMON de votre équipe sont\nalignés dans l'ordre où vous les avez\lloués.\pCet ordre reste le même lorsque vous\néchangez des POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Tous les POKéMON de la TENTE DE COMBAT\nde POIVRESSEL sont prêtés.\pLes POKéMON sont tous de niveau 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The VERDANTURF BATTLE TENT\nrules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the VERDANTURF BATTLE TENT,\nPOKéMON are required to think and\lbattle by themselves.\pUnlike in the wild, POKéMON that live\nwith people behave differently\ldepending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a POKéMON\nmay prefer to attack no matter what.\pAnother POKéMON may prefer to protect\nitself from any harm.\pYet another may enjoy vexing or\nconfounding its foes.\pDepending on its nature, a POKéMON\nwill have favorite moves that it is good\lat using.\pIt may also dislike certain moves that\nit has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\ndirect damage on the foe.\pThere are defensive moves that are\nused to prepare for enemy attacks or\lused to heal HP and so on.\pThere are also other somewhat-odd\nmoves that may enfeeble the foes with\lstat problems including poison and \lparalysis.\pPOKéMON will consider using moves in\nthese three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its TRAINER,\na POKéMON may be unable to effectively\luse certain moves.\pA POKéMON is not good at using any\nmove that it dislikes.\pIf a POKéMON only knows moves that\ndo not match its nature, it will often\lbe unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a POKéMON may\nstart using moves that don't match its\lnature when it is in trouble.\pIf a POKéMON begins behaving oddly\nin a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Dans cette TENTE DE COMBAT, le niveau\nde vos adversaires est ajusté en\lfonction du niveau de vos POKéMON.\pCependant, aucun des DRESSEURS que\nvous affronterez n'aura de POKéMON\lde niveau inférieur à 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Règles de la TENTE DE COMBAT de\nVERGAZON.$"
