PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA: Bonjour, {PLAYER}!\pJe viens de recevoir une BAIE très rare.\nJ'aimerais te la donner.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si tu vois des BAIES qui ont poussé\nsur une terre meuble et fertile,\ltu peux les prendre.\pMais tu dois semer une autre BAIE à cet\nendroit. C'est la moindre des choses.\pTiens, je vais partager ça avec toi.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "A te voir, tu dois être DRESSEUR,\nn'est-ce pas?\pLes DRESSEURS font souvent tenir\ndes BAIES à leurs POKéMON.\pA toi de voir si tu préfères faire\npousser des BAIES ou les utiliser!$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J'ai arrosé les plantes chaque jour.\nElles ont donné beaucoup de fleurs.\pEt elles m'ont aussi procuré de\nnombreuses BAIES.\pVas-y!\nPrends!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais tout faire pour essayer\nd'obtenir des {POKEBLOCK}S de différentes\lcouleurs!\pJ'espère que tu vas tout faire aussi!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Je vais chercher des BAIES de quelle\ncouleur aujourd'hui?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J'adore utiliser le BROYEUR DE BAIES,\nalors je ramasse plein de BAIES!\pJe suis d'accord pour t'en donner\nune si tu veux!$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Tu devrais essayer le BROYEUR DE\nBAIES avec tes amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelles sortes de BAIES vais-je\nplanter? Et faut-il les utiliser ou\lles conserver?\pSe préoccuper de petites choses de ce\ngenre a aussi son charme.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les BAIES poussent en profitant de\nla lumière du soleil.\pNous les aidons à pousser en les\narrosant régulièrement.\pC'est une marque d'attention,\nn'est-ce pas?$"

Route120_Text_YesYouUnderstand:
	.string "Oui, oui.\nTu vois ce que je veux dire.\pTu devrais prendre ça.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais je suppose qu'il est important\nque tu te fasses ta propre opinion…\pTu n'as qu'à prendre ça.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Cette BAIE me semble rare. J'espère\nque tu vas en prendre bien soin.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Je vais aller chercher d'autres BAIES\nchez le MAITRE DES BAIES.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Quand on y regarde de près…\ples costumes me conviennent\nparfaitement.\pEt toi, une BAIE, ça te convient…\pEt pourquoi donc?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Si on veut trouver une explication…\pc'est parce que tu es DRESSEUR!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Quand on y regarde de près…\ptout comme la simplicité me va, les\n{POKEBLOCK}S conviennent très bien aux\lPOKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Tu peux m'appeler le MAITRE DES BAIES.\pJe rêve de recouvrir le monde de fleurs\nmagnifiques, alors je fais pousser des\lBAIES et j'en donne à tout le monde.\pJe te donne celle qui te revient!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être radin?\nPrends-en une autre!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "N'oublie pas d'aller chez le FLEURISTE\nJOLIE FLEUR, près de MEROUVILLE.\pQue les fleurs recouvrent la planète!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J'ai fini pour aujourd'hui.\nRepasse un autre jour.\pQue les fleurs recouvrent la planète!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Pour faire pousser des BAIES, mon mari,\nc'est le meilleur.\pJe suis fière de lui, vraiment.\pAu fait, mon p'tit, t'aurais pas entendu\nune belle expression récemment?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Quelle expression remarquable!\nÇa, c'est de l'inspiration!\pJe veux que tu prennes ça.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Quelle belle expression!\nTu es remarquable.\pJ'aimerais que tu prennes ça.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants devraient\nêtre encore meilleurs que mon mari.\pJ'ai toujours eu une vie heureuse!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour!\pVoici le FLEURISTE JOLIE FLEUR.\nVive les fleurs, plantons-en partout!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, voulez-vous en savoir plus\nsur les BAIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Comment vous appelez-vous?\p{PLAYER}{KUN}.\nQuel joli nom!\p{PLAYER}{KUN}, voulez-vous en savoir plus\nsur les BAIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les BAIES proviennent d'arbres\npoussant sur un sol meuble et fertile.\pQuand on cueille une BAIE, il faut\nen replanter une au même endroit.\pLa BAIE plantée poussera rapidement\npour devenir une plante, fleurir, et\ldonner à son tour des BAIES.\pJ'aimerais que le monde entier soit\nrecouvert de fleurs magnifiques.\lC'est mon rêve le plus cher.\pVous pouvez m'aider, {PLAYER}{KUN}, en\nplantant des BAIES un peu partout.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs illuminent la vie des gens,\nn'est-ce pas?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour!\pPour que les fleurs soient belles,\nil faut bien s'en occuper.\pVous allez aimer soigner vos fleurs, j'en\nsuis sûre. Tenez, c'est pour vous.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pour faire pousser les plantes\nà BAIES, il faut les arroser avec\lle SEAU WAILMER.\pAh, autre chose.\pSi on ne cueille pas de BAIES pendant\nun petit moment, elles tombent par\lterre. Mais d'autres repoussent vite.\pC'est étrange, non? Comme si elles\navaient le désir de vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "J'essaie d'imiter mes grandes sœurs.\nAlors je fais aussi pousser des fleurs!\pTiens! C'est pour toi!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Les BAIES, tu peux les planter ou les\ndonner à porter à des POKéMON.\pMaintenant, il existe aussi une machine\nqui sert à mixer les BAIES pour faire\ldes bonbons pour POKéMON.\pJe veux des bonbons aussi.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, comment tu t'appelles?\p… … …  … … … … … …\nC'est un beau nom!\pMoi c'est JOY.\pMon papa et ma maman m'ont appelée\ncomme ça pour que je sois tout le temps\ljoyeuse.\pC'est ce qu'ils voulaient.\nTiens, prends-en une.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "Je vais aussi te donner cette BAIE,\nla baie préférée de JOY!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Et toi, je me demande pourquoi\ntu t'appelles comme ça.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Printemps, été, automne et hiver.\pEn naissant au printemps, on aime le\nprintemps? Et en naissant en été, on\laime l'été?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "JOY est née en automne,\nalors j'adore l'automne!\pEt toi, quelle est ta saison préférée?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\nC'est pas grave…\pJ'aimerais savoir tellement de choses…$"
