CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenue au CLUB LINK POKéMON.\pLequel de nos services\nsouhaiteriez-vous utiliser?$"

CableClub_Text_WhichService:
	.string "Lequel de nos services\nsouhaiteriez-vous utiliser?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Echanger ses POKéMON avec un\ncâble GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Vous pouvez affronter un autre\njoueur avec un câble GBA Game Link.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Le CENTRE DE DONNEES est ouvert aux\npersonnes ayant un câble GBA Game Link.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Pour jouer en COMBAT DUO, il faut\navoir au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Pour un échange, il faut avoir au moins\ndeux POKéMON en sa possession.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Votre POKéMON qui porte la BAIE {STR_VAR_1}\nne peut pas être échangé.$"

gText_PleaseWaitForLink::
	.string "Veuillez patienter.\nAppuyez sur le bouton B pour annuler…$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Lorsque tous les joueurs sont prêts…\nBouton A: Confirmer   Bouton B: Annuler$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Démarrer connexion entre les {STR_VAR_1} joueurs.\nBouton A: Confirmer   Bouton B: Annuler$"

gText_AwaitingLinkup::
	.string "Connexion en cours…\nBouton B: Annuler$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Your progress must be saved before\nlinking. Is it okay to save?$"

CableClub_Text_PleaseEnter:
	.string "Veuillez entrer.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Je vais vous mener à la salle.$"

Text_SomeoneIsNotReadyToLink:
	.string "Quelqu'un n'est pas prêt à se\nconnecter.\pVeuillez revenir une fois que chacun\ndes joueurs sera prêt.$"

Text_LinkErrorPleaseReset:
	.string "Erreur de connexion…\nVérifiez les branchements et\lréinitialisez les consoles.$"

Text_PlayersMadeDifferentSelections:
	.string "Les joueurs se connectant semblent\nne pas avoir fait le même choix.$"

CableClub_Text_PleaseVisitAgain:
	.string "Revenez quand vous voulez.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Le nombre de participants n'est pas\ncorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Il est impossible de jouer avec {STR_VAR_1}\njoueurs en mode COMBAT SOLO.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Il est impossible de jouer avec {STR_VAR_1}\njoueur(s) en mode COMBAT DUO.$"

CableClub_Text_NeedFourPlayers:
	.string "Il faut être quatre joueurs pour jouer\nà ce mode de combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Veuillez confirmer le nombre de joueurs\net recommencer.$"

Text_TerminateLinkConfirmation:
	.string "La connexion prendra fin si vous\nquittez la pièce. Sortir?$"

Text_TerminateLinkPleaseWait:
	.string "Fin de la connexion. On vous conduira à\nla sortie de la pièce.\lVeuillez patienter.$"

CableClub_Text_TooBusyToNotice:
	.string "Ce DRESSEUR est trop occupé pour voir…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Bravo! Tu peux regarder la CARTE\nDRESSEUR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Bravo! Tu peux regarder la CARTE\nDRESSEUR de {STR_VAR_1}!\pC'est une carte en {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Veuillez prendre place et commencer\nà combattre.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Veuillez prendre place et commencer\nl'échange.$"

RecordCorner_Text_ThanksForComing:
	.string "Merci de votre visite.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Les données sur la CARTE DRESSEUR\nvont être écrasées.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "A une prochaine fois!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Je suis terriblement désolée.\pNous ne sommes pas équipés pour\neffectuer des échanges avec des\lDRESSEURS d'une région si lointaine.$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Au moins un POKéMON ne peut\npas être pris.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Veuillez prendre place et attendre.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} envoie un\n{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Veuillez nous excuser.\nLa connexion a été annulée.\pVous ne pouvez pas échanger vos\ndonnées avec des jeux\lRubis ou Saphir japonais.\pDe même, vous ne pouvez pas échanger\nvos données avec un jeu Emeraude\pjaponais et des jeux Rubis et Saphir\nnon japonais en même temps.$"

CableClub_Text_AdapterNotConnected:
	.string "L'adaptateur sans fil GBA n'est pas\nconnecté correctement.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Les participants doivent se\nprésenter à la réception.$"

@ Unused
CableClub_Text_Hello:
	.string "Hello!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere::
	.string "Vous pouvez y faire des échanges\nde POKéMON avec un ami.$"

CableClub_Text_YouMayBattleHere::
	.string "Vous pouvez affronter vos amis ici.$"

CableClub_Text_CanMakeBerryPowder::
	.string "De deux à cinq DRESSEURS peuvent\nfaire de la POUDRE BAIE ensemble.$"

CableClub_Text_CanMixRecords::
	.string "Les données de deux à quatre joueurs\npeuvent être échangées.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "A guide to the WIRELESS CLUB's\nvarious services.$"

CableClub_Text_CancelSelectedItem::
	.string "Annuler le MENU sélectionné.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Which battle mode would you like?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Returns to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Pour utiliser le BROYEUR DE BAIES,\nil faut avoir au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Pour entrer dans la SALLE UNION,\nil faut avoir au moins deux PKMN.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Un PKMN tenant la BAIE {STR_VAR_1} ne\npeut entrer dans la SALLE UNION.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "C'est la SALLE UNION du\nCLUB SANS FIL POKéMON.\pVotre adaptateur sans fil GBA\nn'est pas connecté correctement.\pRevenez plus tard.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\nExcuse me!$"

CableClub_Text_PlayerIsWaiting:
	.string "On dirait que {STR_VAR_1} est en\ntrain de jouer.\lAllez-y!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Je peux vous expliquer les règles\ndu jeu, si vous le souhaitez.\pVous voulez des infos sur\nquel jeu?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "SAUT POKéMON\pFaites sauter votre POKéMON à\nla corde avec le bouton A.\pSeuls les POKéMON jusqu'à\nenviron 70 cm peuvent participer.\pLes POKéMON capables seulement\nde nager, creuser ou voler\pne sont pas vraiment bons au saut\net ne peuvent donc pas participer.\pDes choses intéressantes arrivent\nsi tout le monde saute en rythme.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "ATTRAPE-BAIES DODRIO\pFaites bouger les têtes de DODRIO\npour attraper les BAIES.\pAppuyez sur gauche, haut et droite\nsur la manette {PLUS}.\pPour jouer à ce jeu, vous devez\navoir un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si vous voulez commencer un jeu,\nallez voir le vieil homme à côté.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Salut! Voulez-vous jouer en\nutilisant le système de\lcommunication sans fil?\pVous pouvez patienter encore\nun petit peu? $"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Très bien, à bientôt.$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'adaptateur sans fil GBA n'est\npas connecté.\pRevenez quand il sera branché!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Très bien, à quel jeu\nvouliez-vous jouer?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quel POKéMON choisissez-vous?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Parfait, ça va bientôt commencer. Ne\nvous faites pas battre par les autres!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Are you leaving now?\nDo come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Aucun de vos POKéMON ne peut\nparticiper…\pVoulez-vous savoir quels POKéMON\npeuvent participer?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "Le SAUT POKéMON est ouvert aux\nPOKéMON jusqu'à environ 70 cm.\pLes POKéMON ne pouvant pas sauter\nne peuvent pas participer.\pComme ceux qui ne peuvent que\nnager, voler ou creuser.\pVoilà, c'est tout ce qu'il faut\nsavoir.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "ATTRAPE-BAIES DODRIO est un jeu où\nseuls les DODRIO peuvent participer.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Could you retry this from the start\nagain, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenue au CLUB SANS FIL\nPOKéMON.\pVous pouvez communiquer avec\nvos amis à partir d'ici.\pA quelle salle voulez-vous\naccéder?$"

CableClub_Text_TradePokemon:
	.string "Voulez-vous échanger un POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "A quel mode de combat\nvoulez-vous jouer?$"

CableClub_Text_AccessRecordCorner:
	.string "Voulez-vous accéder au CENTRE\nDE DONNEES?$"

CableClub_Text_UseBerryCrush:
	.string "Voulez-vous utiliser le\nBROYEUR DE BAIES?$"

CableClub_Text_ExplainBattleModes:
	.string "Il existe trois modes de combat.\pEn COMBAT SOLO, deux DRESSEURS\navec au moins un POKéMON chacun\lcombattent.\pChaque DRESSEUR ne peut envoyer\nqu'un seul POKéMON à la fois au\lcombat. \pEn COMBAT DUO, deux DRESSEURS\navec au moins deux POKéMON chacun\lcombattent.\pChaque DRESSEUR envoie au combat\ndeux POKéMON en même temps.\pEn COMBAT MULTI, quatre DRESSEURS\navec au moins un POKéMON chacun\lcombattent.\pChaque DRESSEUR ne peut envoyer\nqu'un seul POKéMON à la fois au\lcombat.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Veuillez choisir lequel de vous\ndeux sera le MENEUR.\pL'autre joueur devra ensuite\nchoisir «JOINDRE».$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Veuillez choisir lequel d'entre\nvous sera le MENEUR du GROUPE.\pLes autres joueurs devront ensuite\nchoisir «JOINDRE».$"

CableClub_Text_ChooseGroupLeader:
	.string "Veuillez choisir lequel d'entre\nvous sera le MENEUR du GROUPE.\pLes autres joueurs devront ensuite\nchoisir «JOINDRE».$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenue à la SALLE UNION du\nCLUB SANS FIL POKéMON.\pVous pouvez y communiquer avec\nd'autres DRESSEURS. Même avec\lceux que vous ne connaissez pas.$"

CableClub_Text_UnionRoomInfo:
	.string "Les DRESSEURS dans la SALLE\nUNION sont ceux autour de vous qui\lont aussi pénétré dans la salle.\pVous pouvez faire plein de choses\nici, comme par exemple discuter.\pVous pouvez faire entrer 2 POKéMON\njusqu'au niveau 30 pour un combat\pun contre un. Vous pouvez aussi\nparticiper à des tchats\préunissant de 2 à 5 personnes.\pOu vous pouvez encore enregistrer\nun POKéMON pour un échange.\pVoulez-vous entrer dans la SALLE?$"

CableClub_Text_EnjoyUnionRoom:
	.string "J'espère que vous aimerez votre\nvisite dans la SALLE UNION.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Bonjour!\nJe suis ZADIA.\pC'est la première fois que je\nvous vois ici.\pJe vais vous montrer comment le\nsystème sans fil fonctionne.\pJe dois d'abord vous faire visiter\ncet étage du CENTRE POKéMON.\pPar ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Au niveau supérieur, il y a\ndeux salles.\pTout d'abord, la salle à gauche\nest la SALLE UNION.\pVous pouvez vous connecter avec\nles DRESSEURS autour de vous\lqui sont dans la SALLE UNION.\pVous pouvez parler, faire des\néchanges ou combattre avec eux.\pEnsuite, la salle à droite\nest la SALLE LINK DIRECT. \pVous pouvez combattre ou faire\ndes échanges avec vos amis.\pSi l'adaptateur sans fil n'est pas\nutilisé, vous pouvez toujours vous\lconnecter avec un câble Game Link.\pSi c'est le cas, allez directement\ndans la SALLE LINK DIRECT.\pJ'espère que vous apprécierez\nle système sans fil.$"

CableClub_Text_AskAboutLinking:
	.string "Bonjour {PLAYER}!\pJe suis ZADIA, je m'occupe du 1er\nétage du CENTRE POKéMON.\pY a-t-il quelque chose que vous\naimeriez savoir sur la connexion?$"

CableClub_Text_ExplainWirelessClub:
	.string "Laissez-moi vous décrire le\nCLUB SANS FIL POKéMON.\pAu niveau supérieur, il y a\ndeux salles.\pTout d'abord, la salle à gauche\nest la SALLE UNION.\pVous pouvez vous connecter avec\nles DRESSEURS autour de vous\lqui sont dans la SALLE UNION.\pVous pouvez parler, faire des\néchanges ou combattre avec eux.\pEnsuite, la salle à droite\nest la SALLE LINK DIRECT. \pVous pouvez combattre ou faire\ndes échanges avec vos amis.\pDans certains cas, vous ne\npourrez vous connecter avec\lvos amis dans aucune des salles.\pSi c'est le cas, rapprochez-vous\nde vos amis.\pSi l'adaptateur sans fil n'est pas\nutilisé, vous pouvez toujours vous\lconnecter avec un câble Game Link.\pSi c'est le cas, allez directement\ndans la SALLE LINK DIRECT.\pJ'espère que vous apprécierez\nle système sans fil.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "J'espère que vous apprécierez\nle système sans fil.$"
