Text_PictureBookShelf:
	.string "Ce sont des albums de POKéMON.$"

Text_BookShelf:
	.string "Il y a toutes sortes de livres.$"

Text_PokemonCenterBookShelf:
	.string "Des magazines POKéMON!\nNOS AMIS LES POKéMON…\pMANUEL POKéMON…\nGRAINE DE POKéMON…$"

Text_Vase:
	.string "Ce vase semble avoir de la valeur!\pEn regardant à l'intérieur, on\ns'aperçoit qu'il est vide.$"

Text_EmptyTrashCan:
	.string "C'est vide.$"

Text_ShopShelf:
	.string "Les étagères regorgent de toutes\nsortes de produits POKéMON.$"

Text_Blueprint:
	.string "Voilà un curieux plan!\nÇa a l'air compliqué.$"
