gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n{STR_VAR_3} de {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "CATEGORIE NORMAL$"

gContestRankSuper::
	.string "CATEGORIE SUPER$"

gContestRankHyper::
	.string "CATEGORIE HYPER$"

gContestRankMaster::
	.string "CATEGORIE MASTER$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "SANG-FROID$"

gContestBeauty::
	.string "BEAUTE$"

gContestCuteness::
	.string "GRACE$"

gContestSmartness::
	.string "INTELLIGENCE$"

gContestToughness::
	.string "ROBUSTESSE$"

gContestPaintingCool1::
	.string "Le super cool,\nl'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hé!\nLe joli POKéMON {STR_VAR_1} $"

gContestPaintingCool3::
	.string "L'extraordinaire, le merveilleux et\nsuperbe {STR_VAR_1} $"

gContestPaintingBeauty1::
	.string "La splendeur de ce siècle, le\nmagnifique {STR_VAR_1} $"

gContestPaintingBeauty2::
	.string "L'éblouissant et somptueux\nsourire de {STR_VAR_1} $"

gContestPaintingBeauty3::
	.string "L'idole du CENTRE POKéMON:\nl'incomparable {STR_VAR_1} $"

gContestPaintingCute1::
	.string "Le gentil et adorable {STR_VAR_1} $"

gContestPaintingCute2::
	.string "Portrait de la victoire du joli\n{STR_VAR_1} $"

gContestPaintingCute3::
	.string "Fais-nous un clin d'œil!\nMignon POKéMON {STR_VAR_1} $"

gContestPaintingSmart1::
	.string "Le maestro de l'intelligence:\nle sage POKéMON {STR_VAR_1} $"

gContestPaintingSmart2::
	.string "Le POKéMON élu:\nle seul et l'unique {STR_VAR_1} $"

gContestPaintingSmart3::
	.string "Toute l'élégance\nde l'excellent {STR_VAR_1} $"

gContestPaintingTough1::
	.string "Tout en muscles, le fou\nde vitesse {STR_VAR_1} $"

gContestPaintingTough2::
	.string "C'est incontestablement le\nplus fort, {STR_VAR_1} $"

gContestPaintingTough3::
	.string "Le puissant et robuste POKéMON\n{STR_VAR_1} $"
