EventTicket_Text_ShowOldSeaMap:
	.string "Le ferry allant à POIVRESSEL est…\pPardon? Est-ce que nous pouvons aller\nà cet endroit indiqué sur la carte?\pJe connais quelqu'un qui pourra t'aider.\nUn instant.$"

EventTicket_Text_ThatPass:
	.string "Le ferry allant à POIVRESSEL est…\pOh?\nCe PASSE…$"

EventTicket_Text_ShowEonTicket:
	.string "Hé, mon p'tit, c'est toi qui as apporté\nce drôle de PASSE?\pJ'vais t'dire, tu te diriges vers une\nîle minuscule beaucoup plus au sud.\pImpossible de dire ce qui t'attend\nlà-bas, mon p'tit.\pÇa me donne la chair de poule!\pTout le monde à bord!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Dis, mon p'tit, y a absolument rien à voir\nsur cette île perdue.\pOn retourne à NENUCRIQUE?$"

EventTicket_Text_SailHome:
	.string "C'est d'accord, mon p'tit!\nOn est partis!$"

EventTicket_Text_AsYouLike:
	.string "D'accord, mon p'tit, comme tu veux.$"

SouthernIsland_Interior_Text_Sign:
	.string "«Les rêves ne sont qu'une autre\nréalité. Ne jamais l'oublier…»$"

SouthernIsland_Exterior_Text_Sign:
	.string "«Ceux dont les souvenirs s'estompent\ncherchent à les graver dans leur cœur.»$"
