EventTicket_Text_OldSeaMapTooFar:
    .string "Quoi, mon p'tit?\pTu as une vieille carte toute\nabîmée?\pVoyons ça.\n… … … … … …\pOh là là. Ce n'est pas la porte à côté!\nJ'ai bien peur de ne pas pouvoir t'aider…$"

EventTicket_Text_BrineyHoldOnASecond:
    .string "M. MARCO: Attends!\pJe lui dois tellement…\nBien sûr que nous y allons!$"

EventTicket_Text_BrineyLetsSail:
    .string "{PLAYER}{KUN}, je suis vraiment désolé.\pTu viens me demander de l'aide et\non t'envoie promener.\pLaisse-moi me rattraper!\pAllez, on lève l'ancre!\pDirection l'île qui se trouve sur\nla VIEILLECARTE!$"

EventTicket_Text_OddTicketGetOnBoard:
    .string "C'est un drôle de ticket que tu as là!\pL'île où tu veux aller est très loin\nd'ici, tu sais…\pPersonne ne sait ce qui s'y trouve,\nd'ailleurs…\pJe dois dire que ça m'intrigue,\nmon p'tit!!!\pMonte, va.\nOn lève l'ancre!$"

FarawayIsland_Entrance_Text_SailorReturn:
    .string "M. MARCO est parfois un peu\nimprévisible…\pTu veux retourner à NENUCRIQUE?$"

BirthIsland_Harbor_Text_SailorReturn:
    .string "Cette île a vraiment une drôle de forme!\nTu veux retourner à NENUCRIQUE?$"

EventTicket_Text_OddTicketsWhereTo:
    .string "Ce sont de drôles de tickets que\ntu as là!\p… … …\nHum.\pLes îles où tu peux te rendre avec eux\nsont très loin d'ici, tu sais…\pPersonne ne sait ce qui s'y trouve,\nd'ailleurs…\pJe dois dire que ça m'intrigue,\nmon p'tit!!\pMonte, va.\nOù va-t-on en premier?$"

NavelRock_Harbor_Text_SailorReturn:
    .string "Est-ce… Est-ce que tu as entendu ça?\nCe grondement sourd là-dessous?\pOn est peut-être en danger.\nTu crois qu'on devrait partir?$"

FarawayIsland_Entrance_Text_Sign:
    .string "Le texte est presque effacé. Ça a dû\nêtre écrit il y a très longtemps…\p«… bre… 6… jou…\nSi un humain devai… poser à nouveau le\lpied… cette île, que ce soit… personne\lde cœur… Dans cet espoir, je m'en vai…»$"

FarawayIsland_Interior_Text_Mew:
    .string "Miou…$"
