@ Battle Tower
gText_AnabelWonSilver::
	.string "C'est très décevant…$"

gText_AnabelDefeatSilver::
	.string "D'accord, je vois…$"

gText_AnabelWonGold::
	.string "Je suis désolée…$"

gText_AnabelDefeatGold::
	.string "Merci…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Tu n'as pas honte?\nTout le monde nous regarde!$"

gText_TuckerDefeatSilver::
	.string "Grr…\nMais…$"

gText_TuckerWonGold::
	.string "Ce n'est pas pour rien qu'on m'appelle\nla STAR DU DOME!$"

gText_TuckerDefeatGold::
	.string "Ha, ha, ha!\nTu m'amuses!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "On t'a donné une bonne leçon, non?$"

gText_NolandDefeatSilver::
	.string "Joli travail!\nTu te débrouilles plutôt bien!$"

gText_NolandWonGold::
	.string "Hé, hé, hé!\nC'est déjà fini?$"

gText_NolandDefeatGold::
	.string "Je n'y crois pas…$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Oh, j'ai gagné…$"

gText_LucyDefeatSilver::
	.string "Oh, j'ai perdu…$"

gText_LucyWonGold::
	.string "Oui!$"

gText_LucyDefeatGold::
	.string "Grrr…$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Tu n'étais pas à fond!\nTu dois te surpasser!$"

gText_GretaDefeatSilver::
	.string "Pas possible!\nChapeau!$"

gText_GretaWonGold::
	.string "Hé, hé!\nMais qu'est-ce que tu espérais?$"

gText_GretaDefeatGold::
	.string "Quoi?\nMais c'est impossible…$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Tes POKéMON sont nuls!\nEt toi, tu es une mauviette!$"

gText_SpenserDefeatSilver::
	.string "Ah…\nJe ne m'attendais pas à ça…$"

gText_SpenserWonGold::
	.string "Ha, ha, ha!\nNous ne craignons personne!$"

gText_SpenserDefeatGold::
	.string "Non!\nAhhhh!!!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hé, quel est ton problème?\nUn peu de nerf!$"

gText_BrandonDefeatSilver::
	.string "Bravo! Tu as été superbe!\nCette victoire, tu la mérites!$"

gText_BrandonWonGold::
	.string "Ne baisse pas les bras!\nTu dois croire en toi!$"

gText_BrandonDefeatGold::
	.string "Tu as réussi!\nTes efforts ont enfin payé!$"
