LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Vous êtes à la LOTERIE POKéMON.\pTous les clients du CENTRE COMMERCIAL\npeuvent retirer un BILLET DE LOTERIE\lPOKéMON.\pSi le numéro sur le BILLET DE LOTERIE\ncorrespond au numéro ID d'un de vos\lPOKéMON, vous recevrez un beau cadeau.\pVoulez-vous retirer un BILLET DE\nLOTERIE POKéMON?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Revenez demain.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "A bientôt.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Veuillez prendre un BILLET DE LOTERIE.\n…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Le numéro du BILLET DE LOTERIE est\n{STR_VAR_1}.\pJe vais voir si ce numéro correspond\nà l'un des numéros ID de vos POKéMON.\pVeuillez patienter.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Félicitations!\pLe numéro ID de {STR_VAR_1}, qui est\ndans votre équipe, correspond à celui\ldu BILLET DE LOTERIE!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Félicitations!\pLe numéro ID de {STR_VAR_1}, qui est\nstocké sur le PC, correspond à\lcelui du BILLET DE LOTERIE!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Quel dommage!\nAucun des numéros ne correspond.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Deux chiffres correspondent, vous\nremportez le troisième prix!\pVous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Trois chiffres correspondent, vous\nremportez le deuxième prix!\pVous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quatre chiffres correspondent, vous\nremportez le premier prix!\pVous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Magnifique, tous les chiffres\ncorrespondent!\pVous avez gagné le super prix!\nVous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\nOn dirait que vous n'avez plus de place.\pFaites de la place dans votre SAC et\nrevenez me voir.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\nOui, je vous attendais.\pNous vous avons gardé votre prix.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "A bientôt.$"
