MatchCall_WildBattleText1::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}.\pJ'ai vu un {STR_VAR_2}, il y a peu.\nMais impossible de l'attraper!\pJ'étais à deux doigts de réussir,\npourtant! Allez, au revoir!$"

MatchCall_WildBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pIl n'y a pas très longtemps, j'ai\nessayé d'attraper un {STR_VAR_2}.\pMais il s'est enfui!\nTu parles que j'ai été déçue!\pAu revoir!$"

MatchCall_WildBattleText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\pJe viens d'essayer d'attraper\nun {STR_VAR_2}, mais je l'ai raté.\pC'est rageant, j'étais à\ndeux doigts d'y arriver!\pBon, ça m'a gâché la journée…\nAllez, à plus!$"

MatchCall_WildBattleText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pTu connais le POKéMON {STR_VAR_2}?\nJ'ai failli en attraper un…\lJe pensais vraiment l'avoir!\pSi j'en revois un, je ne le\nlouperai pas!\pAllez, à plus!$"

MatchCall_WildBattleText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\lAlors, des nouveaux POKéMON?\pMoi, j'ai failli en attraper un\nrécemment, mais il s'est enfui.\pBon, à plus!$"

MatchCall_WildBattleText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}.\lTu as attrapé des POKéMON?\pL'autre jour, j'en ai presque eu un,\nmais il m'a filé entre les doigts!\pAllez, à bientôt!$"

MatchCall_WildBattleText7::
	.string "{PLAYER}{KUN}, c'est toi?\nSalut, {STR_VAR_1} à l'appareil.\pTu sais quoi? Je n'arrive pas\nà attraper de {STR_VAR_2}…\pSacré nom d'un chien!\nIl n'y a rien à faire!$"

MatchCall_WildBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\pTu attrapes beaucoup de\nPOKéMON en ce moment?\pJ'ai failli en attraper un il n'y a\npas longtemps, mais j'ai échoué.\pJe ne baisse pas les bras!\nA bientôt!$"

MatchCall_WildBattleText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pAlors, tu agrandis ta collection\nde POKéMON?\pJ'en ai par-dessus la tête des\nPOKéMON! Ils m'échappent tous!\pA plus!$"

MatchCall_WildBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pJe voulais te dire… J'ai failli\nattraper un {STR_VAR_2}…\pMais je l'ai laissé filer…\pIl faut que je persévère, je sais.\nA bientôt, j'espère.$"

MatchCall_WildBattleText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\lComment ça va?\pJ'ai essayé d'attraper un\n{STR_VAR_2} sauvage, mais il a filé!\pJe perds un peu confiance…$"

MatchCall_WildBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lTu attrapes toujours des POKéMON?\pJ'essaie de m'y mettre, mais\nc'est loin d'être facile!\pLes POKéMON sont malins!$"

MatchCall_WildBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lTu as de nouveaux POKéMON?\pJ'ai moi-même essayé, mais\nce fut un échec, je dois dire.\pLes POKéMON sont malins!$"

MatchCall_WildBattleText14::
	.string "Bonjour, {PLAYER}{KUN}, comment vas-tu?\nC'est {STR_VAR_1}.\pJe viens d'essayer d'attraper un\njoli petit {STR_VAR_2}.\pMais il s'est enfui!\nCrois-moi, j'ai été déçue!\pAu revoir!$"

MatchCall_WildBattleText15::
	.string "Bonjour, {PLAYER}!\nIci {STR_VAR_1}!\pJe pense me mettre à attraper\ndes POKéMON, tu sais.\pMais le problème, c'est que je n'en\nvois aucun!\pC'est étrange, non?\nBon, je te laisse. Au revoir!$"

MatchCall_NegativeBattleText1::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}.\pJ'ai essayé de me battre contre un\nautre DRESSEUR, mais j'ai perdu.\pJ'étais très déçu, tu sais.\nAllez, salut!$"

MatchCall_NegativeBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pJ'ai affronté quelqu'un d'autre\naprès notre combat.\pJ'ai été pas mal, mais j'ai perdu.\nJe ferai mieux la prochaine fois.$"

MatchCall_NegativeBattleText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\pJe viens de perdre un combat.\pJe suppose que mon équipe\nn'est pas encore au point!$"

MatchCall_NegativeBattleText4::
	.string "Salut, {PLAYER}.\n{STR_VAR_1} à l'appareil.\pJ'ai refait un combat hier, mais\nje n'en suis pas sorti vainqueur.\pJe dois entraîner mon équipe\ndavantage. Allez, à plus!$"

MatchCall_NegativeBattleText5::
	.string "Salut, {PLAYER}!\n{STR_VAR_1} à l'appareil.\pTout se passe bien?\pJ'ai fait quelques combats, mais\nje n'ai pas gagné souvent.\pJe ne suis pas encore au point!\nBon, à plus!$"

MatchCall_NegativeBattleText6::
	.string "Salut, {PLAYER}.\nIci {STR_VAR_1}.\pTout va comme tu veux?\pJe mets toute mon énergie\nau combat, mais je perds souvent.\pJe ne suis pas encore dans l'esprit.\nAllez, à bientôt!$"

MatchCall_NegativeBattleText7::
	.string "Ici {STR_VAR_1}.\nComment ça se passe?\pJ'ai perdu un combat hier.\nJe n'arrête pas d'y penser.\pIl faut que je me reprenne…\nSalut!$"

MatchCall_NegativeBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\pComment vont tes POKéMON?\nJ'ai perdu un combat, l'autre jour.\pJe ne baisse pas les bras!\nAllez, à bientôt!$"

MatchCall_NegativeBattleText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pEcoute, j'ai quelque chose à\nte dire!\pJ'ai fait un combat de POKéMON hier\net j'ai perdu au dernier moment.\pQu'est-ce que c'est frustrant!$"

MatchCall_NegativeBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pJ'ai fait un combat aujourd'hui.\nMais j'ai perdu…\pMes POKéMON ne sont pas encore\nau top niveau. A bientôt, j'espère.$"

MatchCall_NegativeBattleText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\lComment vont tes POKéMON?\pMoi, je viens de perdre un combat.\nC'est pas la joie…\pBon, au revoir!$"

MatchCall_NegativeBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lTu continues les combats?\pJe perds souvent ces derniers\ntemps. \pJe dois renforcer mon équipe!\nA bientôt.$"

MatchCall_NegativeBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\pJ'espère que tu te portes bien.\pJ'ai fait un combat tout\nrécemment.\pPrends-en de la graine, {PLAYER}{KUN}!\nIl faut garder la forme! Au revoir!$"

MatchCall_NegativeBattleText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pTout se passe comme tu veux?\pTu sais, tu devrais rentrer\nchez toi de temps en temps.\pAu revoir!$"

MatchCall_PositiveBattleText1::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}.\pJ'ai combattu contre un autre\nDRESSEUR et j'ai gagné!\pMon {STR_VAR_2} s'est vraiment\ndémené! C'est super!$"

MatchCall_PositiveBattleText2::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pJ'ai gagné un combat hier,\nc'était super!$"

MatchCall_PositiveBattleText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\lÇa va, les combats?\pMoi, j'en ai fait un l'autre jour\net mon {STR_VAR_2} a été épatant!\pSi on refait un combat, je ne\nperdrai pas, {PLAYER}!$"

MatchCall_PositiveBattleText4::
	.string "Salut, {PLAYER}.\nC'est {STR_VAR_1}.\pJ'ai fait un combat, aujourd'hui.\nJ'ai gagné, mais de justesse!\pMon {STR_VAR_2} a été super, en\ntout cas.$"

MatchCall_PositiveBattleText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pComment va la vie?\nToujours à faire des combats?\pTiens, j'en ai gagné un il n'y a pas\nlongtemps grâce à mon {STR_VAR_2}!\pLa prochaine fois, c'est toi que\nje battrai! Bon, à plus!$"

MatchCall_PositiveBattleText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}.\pComment va?\pPour moi tout baigne, je viens\nde gagner un combat.\pSi jamais on se recroise,\nje ne perdrai pas!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\nIci {STR_VAR_1}.\pJ'adore mon {STR_VAR_2}, il vient\njuste de me faire gagner!\pJ'ai hâte de refaire un combat\ncontre toi.$"

MatchCall_PositiveBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\pJ'espère que tu vas bien. Tu sais,\nje viens de gagner un combat!\pMon {STR_VAR_2} a été brillant!\nIl fallait que je te le dise!\pAu revoir!$"

MatchCall_PositiveBattleText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pComment vont tes POKéMON?\nNous, on vient de gagner un combat!\pMon {STR_VAR_2} a été absolument\nspectaculaire.\pQuel dommage que tu n'aies pas\nvu ça! Au revoir!$"

MatchCall_PositiveBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pComment va la vie?\pMes POKéMON sont en super forme,\nces derniers temps.\pIls viennent de me faire gagner un\ncombat. A bientôt, j'espère.$"

MatchCall_PositiveBattleText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pTu as fait des combats, récemment?\nMoi, j'en ai gagné un aujourd'hui!\pJe suis sur la bonne voie!\nAllez, au revoir!$"

MatchCall_PositiveBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pTout va bien, mon petit?\nJe suis frais comme un gardon!\pJe n'arrête pas de gagner des\ncombats, tous les jours!\lContre des jeunes gens, en plus!$"

MatchCall_PositiveBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\pJ'espère que tout va bien.\nMoi j'ai la pêche!\pJ'enchaîne les victoires aux\ncombats! Et les petits jeunes\lne me font pas peur, tu sais!\pAu revoir!$"

MatchCall_PositiveBattleText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pJ'ai fait un combat il y a peu et\nmon {STR_VAR_2} a été formidable!\pJ'aurais aimé que tu voies ça,\n{PLAYER}{KUN}. Au revoir!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Salut, {PLAYER}!\nC'est {STR_VAR_1}.\pQuoi, tu es près de…\n{STR_VAR_2}, tu dis?\pMais il faut qu'on fasse un combat!\nJe t'attends, à tout de suite!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Salut, {PLAYER}!\nC'est {STR_VAR_1}.\p{STR_VAR_2}? C'est là que tu\nes?\pOn fait un combat?\nAllez, je t'attends!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\p{STR_VAR_2}, tu dis?\nC'est là que tu te trouves?\pQue le monde est petit!\nOn fait un combat?\pCette fois, je ne perdrai pas!\nJe ne bouge pas, je t'attends!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pOù tu es?\n{STR_VAR_2}? Ah, oui?\pIl faut absolument qu'on fasse un\ncombat, alors! Je t'attends!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\lÇa roule?\pOù es-tu?\n{STR_VAR_2}?\pSi on en profitait pour refaire un\ncombat?\pJ'espère bien que tu vas venir!\nJe t'attends!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}.\lJe viens aux nouvelles.\p{STR_VAR_2}, vraiment? On\nest tout près, alors!\pC'est l'occasion ou jamais de\nrefaire un combat!\pJe trépigne d'impatience.\nA tout de suite, je t'attends!$"

MatchCall_SameRouteBattleRequestText7::
	.string "Heu… {PLAYER}{KUN}?\nIci {STR_VAR_1}…\p{STR_VAR_2}? Tu es dans le\ncoin, alors!\pFaisons un combat!\nTu viens?\pJe vais te montrer mes POKéMON.\nDépêche-toi, je t'attends.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\pTu es près de…\n{STR_VAR_2}, c'est ça?\pÇa te dirait de faire un petit\ncombat contre moi?\pAllez, je t'attends.\nA très bientôt!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pLa forme?\n{STR_VAR_2}? Pas possible!\pNe ratons pas cette occasion.\nOn fait un combat?\pBon allez, je t'attends!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pTu es où? Près de… \n{STR_VAR_2}?!? J'y suis!\pJ'ai très envie de te voir.\nOn fait un combat?\pJe suis prête!\nNe me fais pas attendre…$"

MatchCall_SameRouteBattleRequestText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOù est-ce que tu es?\n{STR_VAR_2}?\pIl faut qu'on se rencontre pour\nun combat, qu'en dis-tu?\pD'accord, je ne bouge pas.\nA tout de suite!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lOù es-tu, mon petit?\p{STR_VAR_2}?\nJe ne suis pas loin!\pEt si on faisait un combat?\nC'est l'occasion ou jamais!\pJe t'attends, mon petit.\nA bientôt!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\pOù te trouves-tu?\n{STR_VAR_2}?\pEcoute, je suis tout près. Tu viens\nme voir pour faire un combat?\pBien, je t'attends.\nA tout de suite.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pOù ça? {STR_VAR_2}?\nMais c'est tout près!\pTu ne crois pas qu'on devrait se\nrencontrer pour un combat?\pD'accord, je t'attends.\nAu revoir!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Salut, {PLAYER}!\nC'est {STR_VAR_1}.\pTu sais quoi? J'ai envie de faire un\ncombat contre toi!\pBon, je suis aux alentours de\n{STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Salut, {PLAYER}!\nC'est {STR_VAR_1}.\pDis, tu veux bien refaire un\ncombat contre moi?\pTu me trouveras près de\n{STR_VAR_2}. A plus!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\pMes POKéMON ont bien progressé\ndepuis la dernière fois.\pJ'aimerais bien qu'ils se mesurent\nde nouveau aux tiens, {PLAYER}.\pOn refait un combat?\pD'accord, je suis près de\n{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\lÇa va, toi?\pMes POKéMON sont bien meilleurs,\ntu sais.\pTu veux bien qu'on refasse un\ncombat?\pD'accord, je t'attends aux\nalentours de {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pMes POKéMON ont bien progressé,\nje suis drôlement fier d'eux.\pJ'aimerais refaire un combat\ncontre toi.\pJe t'attends du côté de\n{STR_VAR_2}, alors. A plus!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}.\lJ'espère que ça roule pour toi.\pJe me disais que j'aimerais bien\nfaire un autre combat contre toi.\pEcoute, si ça te dit, on peut se\nvoir près de {STR_VAR_2}.\pPeut-être à tout à l'heure!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "Heu… {PLAYER}{KUN}?\nIci {STR_VAR_1}…\lAlors? Tes POKéMON vont bien?\pLes miens sont de plus en plus\nforts! J'aimerais que tu les voies.\pJe suis près de {STR_VAR_2}.\nPasse, si tu veux combattre.\pAu revoir.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\pJ'espère que tout va bien pour toi.\nMes POKéMON sont en super forme.\pSi tu passes dans le coin,\nj'aimerais bien qu'on combatte.\pJe suis près de {STR_VAR_2}.\nA bientôt, j'espère!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\lComment vont tes POKéMON?\pLes miens progressent à vue\nd'œil, {PLAYER}{KUN}.\pJe suis près de {STR_VAR_2}.\nPasse faire un combat, si tu veux.\pJ'espère te voir bientôt!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\lComment vas-tu?\pMes POKéMON ont fait d'énormes\nprogrès.\pJ'aimerais beaucoup refaire un\ncombat contre toi, {PLAYER}{KUN}.\pJe suis près de {STR_VAR_2}.\nPasse me voir à l'occasion.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pMes POKéMON débordent de vie.\nJe pense qu'ils ont envie de revoir\ltes POKéMON, {PLAYER}{KUN}.\pJe suis vers {STR_VAR_2}.\nJ'espère que tu vas passer.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pJe voulais te dire que mes POKéMON\nsont devenus très forts.\pJ'aimerais bien qu'on refasse un\ncombat tous les deux, {PLAYER}{KUN}.\pOn est aux alentours de\n{STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lComment vont tes POKéMON?\pMes POKéMON vont tellement bien\nqu'ils battraient n'importe qui!\pJ'aimerais faire un nouveau combat\ncontre toi, pour les tester.\pSi tu passes près de\n{STR_VAR_2}, viens nous voir.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lJ'espère que tu vas bien.\pOui, mes POKéMON ont beaucoup\nappris depuis la dernière fois.\pTu ne crois pas qu'on devrait\nrefaire un combat, {PLAYER}{KUN}?\pOn est près de {STR_VAR_2},\nen ce moment.\pJ'espère que tu vas venir nous\nvoir bientôt!$"

MatchCall_PersonalizedText1::
	.string "C'est {STR_VAR_1}, l'amoureux de la\nmontagne!\pTu as passé du temps en montagne\ndepuis la dernière fois?\pJ'y suis souvent mais je te croise\nrarement…\pLa prochaine fois, on pourrait se\nvoir près de {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "C'est {STR_VAR_1}.\nBonjour.\pJ'ai parlé de toi à un nouveau\nDRESSEUR.\pJ'ai dit que je connaissais un bon\nDRESSEUR qui s'occupe de ses\lPOKéMON avec grand soin.\pD'ici peu, tout le monde t'admirera.\nTu vas devenir célèbre!\pJ'espère qu'on se reverra!$"

MatchCall_PersonalizedText3::
	.string "C'est {STR_VAR_1}. Bonjour!\pJe me trouve dans un endroit\nmagnifique aux senteurs exquises!\pQuelqu'un a dû planter des BAIES.\pAu revoir!$"

MatchCall_PersonalizedText4::
	.string "Bonjour! Trente ans de fouilles,\n{STR_VAR_1} à ton service!\pOn dirait que tu as la bougeotte,\ntu es toujours en vadrouille.\pTu as découvert des ruines en\nchemin? Si tu en vois, pense à moi!\pJe te laisse, j'ai des ruines à\nfouiller.$"

MatchCall_PersonalizedText5::
	.string "C'est {STR_VAR_1}!\pDevine ce que je fais!\nJ'admire les vagues sur la plage!\pOh… Les reflets du soleil sur l'eau\nsont magnifiques. Ça scintille!\lJe commence à avoir faim. Au revoir!$"

MatchCall_PersonalizedText6::
	.string "Miam, miam…\nOh, salut! C'est {STR_VAR_1}.\lJ'adore manger sur la plage.\pMes POKéMON et moi allons bien.\nOn est gonflés à bloc!\lJe vais faire trempette. Au revoir!$"

MatchCall_PersonalizedText7::
	.string "Salut, c'est {STR_VAR_1}…\pCette histoire de TOPDRESSEUR\nm'est un peu montée à la tête…\pTout le monde croit que je suis un\nDRESSEUR parfait. Je ne veux pas\lles décevoir.\pJe suppose que c'est le revers\nde la médaille.\pIl faut que je m'entraîne dur…\nEt avec le sourire, en plus!\pIl n'y a vraiment qu'à toi que je\npouvais dire ça.\pMerci, ça m'a fait du bien de te\nparler!$"

MatchCall_PersonalizedText8::
	.string "Salut, toi! C'est {STR_VAR_1}!\nÇa va?\pJ'essaie de bien m'occuper de mes\nPOKéMON. Tu es mon modèle.\pLa prochaine fois qu'on se battra,\nje ferai tout pour gagner.\pC'est super d'avoir des amis\nDRESSEURS! A bientôt!$"

MatchCall_PersonalizedText9::
	.string "C'est {STR_VAR_1}…\nAttention, derrière toi…\lIl y avait quelque chose, non?\pLa puissance des POKéMON qui\nreposent au MONT MEMORIA…\pElle me parle de toi…\pTu dois partir immédiatement!\nSurtout, ne te retourne pas…\pAu revoir…$"

MatchCall_PersonalizedText10::
	.string "C'est {STR_VAR_1}.\nComment tu vas?\pC'est pratique de pouvoir garder\nle contact comme ça!\pAvant, quand je voulais parler avec\nquelqu'un, je devais demander à\lmon père de me déposer en voiture…\pBon, je te laisse.\nContente d'avoir parlé avec toi!$"

MatchCall_PersonalizedText11::
	.string "C'est {STR_VAR_1}!\nJ'ai quelque chose à te dire.\pJ'aime beaucoup le PARC SAFARI,\nmais je m'y perds tout le temps!\pLes herbes sont trop hautes!\nEn plus, c'est immense!\pJ'avais besoin de confier ça à\nquelqu'un!\pBon, je retourne au PARC SAFARI!\nAu revoir!$"

MatchCall_PersonalizedText12::
	.string "Bonjour, ici {STR_VAR_1}.\nOui, je suis riche. C'est bien vrai.\pJe suis encore plus riche que la\ndernière fois.\pSinon, mes POKéMON vont bien.\nIls ont beaucoup progressé.\pJ'ai l'impression que ce monde\na été créé pour moi!\pJe sais ce que tu penses.\nMais c'est vrai!\pJe te prie de m'excuser.\nJe dois me rendre à une réception.$"

MatchCall_PersonalizedText13::
	.string "C'est moi, {STR_VAR_1}…\pDevine ce que je vois…\nDeux {STR_VAR_2} en plein combat!\pJe vais essayer d'attraper le\ngagnant… Oui, tiens…\pBon… Il faut que j'y aille.\nJe te laisse.$"

MatchCall_PersonalizedText14::
	.string "C'est {STR_VAR_1}!\pTu sais, j'en ai un peu marre de\nl'EPAVE.\pMais puisque j'y suis et que\nj'aimerais te battre une fois, je\lvais y rester encore un peu.\pJe ne veux pas te forcer, mais\npourquoi tu ne viens pas?\pJe pense qu'aujourd'hui je vais\ndéfier l'homme d'à côté. J'ai\lenvie d'un petit combat.\pAu revoir!$"

MatchCall_PersonalizedText15::
	.string "C'est {STR_VAR_1}!\nLe garçon amphibie!\pTu sais ce que je crois?\pQue c'est en mer qu'on trouve les\nmeilleurs DRESSEURS!\pTu devrais prendre exemple sur moi\net venir t'entraîner en mer…\pWaouh!!! Une vague géante arrive!\nJe vais la surfer!\pC'est génial de s'entraîner ici!\nIl faut que je te laisse!$"

MatchCall_PersonalizedText16::
	.string "C'est {STR_VAR_1}! J'ai donné des\ncours de karaté à mes POKéMON.\pIls sont devenus meilleurs que moi!\nIls apprennent vite!\pMais grâce à eux, je ne perdrai\nplus un seul combat de POKéMON!\pIl faut qu'on en refasse un,\nau fait! Yah!!!$"

MatchCall_PersonalizedText17::
	.string "C'est moi, {STR_VAR_1}.\nComment se déroule ton voyage?\pWaouh, vraiment?\nÇa a l'air super intéressant!\pJe pourrais bien en faire une\nchanson!\p…\nJ'ai un début de mélodie en tête.\pIl faut que j'aille mettre tout ça\npar écrit, sinon je vais oublier!$"

MatchCall_PersonalizedText18::
	.string "C'est {STR_VAR_1}…\nVoici ma nouvelle chanson.\pTralala, {STR_VAR_2}, {STR_VAR_2}!\nMon petit {STR_VAR_2}!\lMon mignon {STR_VAR_2}!\lTralala, {STR_VAR_1}, {STR_VAR_2}…\l{STR_VAR_1} et {STR_VAR_2}…\pC'est le refrain!$"

MatchCall_PersonalizedText19::
	.string "C'est moi {STR_VAR_1},\nle pro du camping!\pLa dernière fois, je n'ai pas réussi\nà te battre.\pOn ne peut pas être bon en tout!\pMais quand je fais du camping,\nj'aime bien faire des combats.\pViens nous voir à l'occasion!\nSur ce, je vais camper. Salut!$"

MatchCall_PersonalizedText20::
	.string "C'est moi, {STR_VAR_1}!\pPour être honnête, j'aimerais bien\naller randonner ailleurs.\pMais il y a tellement de jolies\nfilles sur le MONT CHIMNEE…\pSi tu connais des montagnes avec\nplein de jolies filles, dis-le-moi!\pHé, hé, hé! Au revoir!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n… … … … … …\lC'est {STR_VAR_1}…\p… … … … … …\n… … … … … …\lC'est tout pour aujourd'hui…$"

MatchCall_PersonalizedText22::
	.string "C'est {STR_VAR_1}. J'avais envie\nde te parler.\pDe jour en jour, mon désir de te\nbattre grandit.\pMais tu dois avoir beaucoup de\nrivaux…\pJ'espère avoir bientôt la chance\nd'être ton adversaire. Au revoir!$"

MatchCall_PersonalizedText23::
	.string "C'est {STR_VAR_1}.\pTu sais, quand un bon DRESSEUR\npasse près de moi, je le sens.\pOù es-tu en ce moment, {PLAYER}{KUN}?\nJe crois avoir senti ta présence…\pJ'espère te voir bientôt.\nAu revoir!$"

MatchCall_PersonalizedText24::
	.string "Bonjour, c'est {STR_VAR_1}.\nTu as l'air d'aller bien, {PLAYER}{KUN}.\pJ'ai beaucoup voyagé, je suis allé\nun peu partout…\lC'est cette région que je préfère.\pJe compte y rester encore un peu.\nJ'espère qu'on se reverra avant\lque je parte.\pJe n'ai pas oublié tes techniques\nimpressionnantes.\pJ'espère qu'on aura le temps de\nrefaire un combat.$"

MatchCall_PersonalizedText25::
	.string "Sniff… C'est… {STR_VAR_1}…\nSniff…\pROXANNE m'a grondé en classe\naujourd'hui.\pMais je l'aime bien quand même.\pElle me permet de prendre\nconscience de mes erreurs.\pBien sûr que je retourne à\nl'ECOLE DE DRESSEURS demain!\pAu revoir!$"

MatchCall_PersonalizedText26::
	.string "C'est {STR_VAR_1}!\pROXANNE m'a permis de me battre\ncontre elle hier.\pJ'ai perdu… Faut pas poser\nce genre de questions!\pMais j'étais contente qu'elle me\nlaisse me mesurer à elle.\pJe l'admire encore plus maintenant!\pJe vais travailler encore plus dur!\nD'ailleurs, il faut que j'y aille!$"

MatchCall_PersonalizedText27::
	.string "Bonjour, c'est ANNA! Je suis avec\nma charmante partenaire, EVA.\pJ'adore m'occuper d'EVA et de\nmes POKéMON. Ils sont mignons!\pC'est comme s'ils faisaient partie\nde ma famille!\pSalut, EVA!\nTu as acheté le pain?\pQuoi? Mais non, je ne te traite pas\ncomme une esclave, voyons!\pTu as perdu, alors c'est à toi\nd'acheter le pain, c'est tout!\pJe t'aime trop! Je ne te traiterai\njamais comme une esclave!\pJe dois y aller,\non va manger!$"

MatchCall_PersonalizedText28::
	.string "J'adore les POKéMON!\nC'est {STR_VAR_1} du FAN CLUB!\pUn truc incroyable s'est passé!\nMes petits POKéMON…\pOups! Je ne peux pas en dire plus,\nc'est un secret! De toute façon,\lje ne trouverais pas les mots.\pOh, mon petit {STR_VAR_2} me\nréclame un {POKEBLOCK}!\pCe n'est pas beau de réclamer!!!\nMais il est si mignon, celui-là…\pDésolé, le devoir m'appelle! Je\nt'en dirai plus la prochaine fois!$"

MatchCall_PersonalizedText29::
	.string "Oh, oh!\pC'est {STR_VAR_1}! J'ai plein de\nchoses à te raconter!\pTiens, écoute ça! C'est sur mon\ntout petit {STR_VAR_2} chéri.\pDès que quelqu'un s'approche,\nil saute dans mes bras, le pauvre\lpetit bébé!\pOh… Si ce n'est pas ça le bonheur,\nje me demande ce que c'est…\pJe suis si heureuse!\pIl fallait absolument que je parle\nde ça à quelqu'un.\pBon, je dois te laisser.\nAu revoir!$"

MatchCall_PersonalizedText30::
	.string "Je suis… {STR_VAR_1}.\nLes gens m'appellent l'EXPERT.\pIl y a une chose que je sais. Sans\nmes POKéMON, je ne serais rien.\pSans eux, aucun DRESSEUR ne\npourrait devenir un EXPERT.\pOh! Des fois je dis des trucs\nprofonds, dis donc!\pSur ces bonnes paroles, je te\ndis au revoir!$"

MatchCall_PersonalizedText31::
	.string "C'est {STR_VAR_1}.\nJe suis contente de te parler!\pJe fais trempette dans les sources\nchaudes, le bonheur!\pJ'ai combattu contre beaucoup\nde DRESSEURS mais tu restes\lle meilleur.\pEt je suis sûre que tu as encore\nprogressé depuis la dernière fois!$"

MatchCall_PersonalizedText32::
	.string "Hé, salut! C'est {STR_VAR_1}!\nQuoi de neuf?\pC'est peut-être une impression,\nmais quand je gagne, je me sens\lmieux dans mes baskets.\pNon, vraiment!\nComment expliquer…\lOn dirait qu'elles sont plus larges…\lEt plus moelleuses, aussi.\pPendant notre combat, {PLAYER}{KUN},\nmes baskets étaient trop serrées!\p… … … … … …\nQuoi, tu m'as cru? Hé, hé, hé!\lTu crois tout ce qu'on te dit, toi!$"

MatchCall_PersonalizedText33::
	.string "Salut, toi!\nC'est {STR_VAR_1}!\pComme d'habitude, je m'adonne\naux plaisirs de la pêche!\pC'est dommage qu'on ne puisse\npêcher que dans la mer et la\lrivière.\pOui, dans les lacs aussi. Mais\nj'aimerais pouvoir pêcher partout!\pOh, je dois te laisser! Ha, ha, ha!\nÇa mord sur une autre ligne!\pJe veux dire, j'ai une prise!\nAu revoir!$"

MatchCall_PersonalizedText34::
	.string "Bonjour, c'est {STR_VAR_1}.\nTout baigne?\pTu sais, quand j'étais petit,\nj'étais plutôt du genre tranquille.\pJ'aimais prendre mon temps,\nje fuyais le stress.\pEh bien maintenant, je suis un\nTRIATHLETE.\pTu ne sais jamais ce que la vie te\nréserve.\pAujourd'hui, tu es un DRESSEUR.\nMais que seras-tu demain?\pTu pourrais très bien avoir envie\nd'enseigner? Ou de peindre?\pPenses-y!\nAllez, à plus.$"

MatchCall_PersonalizedText35::
	.string "C'est {STR_VAR_1}!\nJe suis à vélo.\pJ'adore nager et courir, mais le\nvélo, c'est mon dada!\pA vélo, je ne fais qu'un avec le\nvent.\pJe me sens euphorique!\nC'est comme si je volais!\pJe veux réaliser un nouveau record\nsur la PISTE CYCLABLE, aujourd'hui!\pToi aussi, tu devrais essayer!\nAu revoir!$"

MatchCall_PersonalizedText36::
	.string "Salut, c'est {STR_VAR_1}! Je suis en\nplein triathlon!\pMais c'est pas ça qui m'empêche\nd'appeler les amis!\pTu sais, j'adore m'entraîner avec\nles POKéMON!\pOn se comprend sans dire un seul\nmot. C'est simple, on ne fait qu'un!\pÇa me transporte de joie!\pMince… Il faut que je raccroche…\nC'est… pas facile…\lJe m'essouffle… Au revoir…$"

MatchCall_PersonalizedText37::
	.string "Salut, {STR_VAR_1}.\nSi tu veux améliorer ton endurance,\lentraîne-toi en altitude!\pEssaie de gravir une montagne en\ncourant. Tu vas vite t'essouffler!\pJustement, je commence à\nmanquer d'oxygène! Je te laisse!$"

MatchCall_PersonalizedText38::
	.string "C'est {STR_VAR_1}. Bonjour!\pJe n'arrête pas de nager, mais je ne\ntrouve pas ETERNARA.\pJ'ai l'impression de tourner en\nrond.\pNon, non, c'est impossible…\nAllez, à bientôt!$"

MatchCall_PersonalizedText39::
	.string "Salut, {STR_VAR_1}…\nBlop!\pBloup, bloup, bloup…\pBlop!\pDésolé, j'ai mis de la crème solaire.\pMon POKéNAV m'a glissé des mains\net il est tombé dans l'eau!\pLe POKéNAV de DEVON est solide!\nEn tout cas, il est étanche!\pBon, je vais faire bronzette!\nDésolé, je dois te laisser.$"

MatchCall_PersonalizedText40::
	.string "Bonjour, c'est {STR_VAR_1}.\pMon épreuve de triathlon préférée,\nc'est la nage.\pMais j'ai peur d'un truc. Je ne\nrisque pas de ressembler à un\lpruneau à force d'être dans l'eau?\pJ'aime le triathlon! J'aime dépasser\nmes peurs! Au revoir!$"

MatchCall_PersonalizedText41::
	.string "Salut, {PLAYER}{KUN}.\n{STR_VAR_1} à l'appareil.\pComment vont tes POKéMON?\pMes POKéMON DRAGON pètent le feu!\nA la prochaine!$"

MatchCall_PersonalizedText42::
	.string "C'est {STR_VAR_1}.\pMon {STR_VAR_2} a beaucoup changé\ndepuis la dernière fois.\pTu ne pourras plus me battre.\nVivement qu'on se revoie!\pAu revoir!$"

MatchCall_PersonalizedText43::
	.string "C'est {STR_VAR_1} à l'appareil.\pJ'ai continué mes recherches sur\nl'art de la dissimulation.\pJ'ai fait tellement de progrès que\nplus personne ne me voit!\lJe me sens terriblement seul…\pComme la fumée, je me dissipe!\nAu revoir!$"

MatchCall_PersonalizedText44::
	.string "C'est {STR_VAR_1}.\nJe n'ai pas arrêté de m'entraîner\ldepuis la dernière fois.\pMon {STR_VAR_2} est devenu super\nfort.\pJe m'entraîne sur la plage. Je\ntrouve ça plus efficace. Au revoir!$"

MatchCall_PersonalizedText45::
	.string "Comment ça va?\nC'est {STR_VAR_1}.\pCes cendres volcaniques n'en\nfinissent pas de tomber!\pSi ça continue, on ne verra plus les\nmotifs de mon parasol…\pJ'espère te voir bientôt!$"

MatchCall_PersonalizedText46::
	.string "Bonjour, c'est {STR_VAR_1}.\pTu sais que c'est plus facile de\nfaire la planche dans la mer que\ldans la piscine?\pOn y flotte beaucoup mieux.\pMais quand tu fais la planche,\nfais attention de ne pas te laisser\lemporter au large.\pMais au fait, où je suis là???\nHeu… Il faut que je te laisse!$"

MatchCall_PersonalizedText47::
	.string "Bonjour {PLAYER}{KUN}!\nC'est {STR_VAR_1}.\lJe suis en montagne.\pMais le sol est plein de bosses.\nJe ne peux pas planter ma tente…\pOh, j'ai une super idée!\pJe vais demander à mes POKéMON\nde damer le sol!\pJe vais essayer!\nAu revoir!$"

MatchCall_PersonalizedText48::
	.string "Bonjour, c'est {STR_VAR_1}!\pJ'élève des POKéMON avec AWA!\nOn prend ça très au sérieux!\pSi on y met encore plus d'énergie,\non deviendra les meilleures!$"

MatchCall_PersonalizedText49::
	.string "Ici {STR_VAR_1}!\pJe suis un MARIN, même si je ne suis\npas en mer en ce moment…\pUn MARIN à terre, c'est comme un\npoisson sans eau!\pDès que je rejoins la terre ferme,\nje deviens un peu nostalgique.\pAllez, à la prochaine!$"

MatchCall_PersonalizedText50::
	.string "C'est {STR_VAR_1}.\nTu as de nouveaux POKéMON?\pSi tu en attrapes un nouveau,\nviens me le montrer!\pJe promets de ne pas être jaloux.\nA bientôt, j'espère!$"

MatchCall_PersonalizedText51::
	.string "C'est {STR_VAR_1}.\pElèves-tu tes POKéMON\ncorrectement?\pLà où je me trouve, l'air est pur.\nC'est ce qu'il y a de mieux pour les\lPOKéMON.\pSi tu veux les élever de façon\noptimale, viens sur la\l{STR_VAR_2}!$"

MatchCall_PersonalizedText52::
	.string "Bonjour, c'est {STR_VAR_1}.\pJ'ai donné un {POKEBLOCK} à mon\n{STR_VAR_2}. Il a beaucoup aimé.\pLes POKéMON ont tous leurs\npréférences en matière de {POKEBLOCK}S.\pJe trouve ça fascinant.\nAu revoir.$"

MatchCall_PersonalizedText53::
	.string "C'est {STR_VAR_1}.\pGrâce aux POKéMON, tu peux\nsurvivre en pleine nature.\pJe crois que les gens devraient\ncoopérer plus avec les POKéMON.\pOn a tout à y gagner.\nLes POKéMON, c'est l'avenir.\pMais tu ne fais pas partie des gens\nà convaincre. Tu penses POKéMON!$"

MatchCall_PersonalizedText54::
	.string "Salut, c'est {STR_VAR_1}.\nJe suis toujours prête! Et toi?\p{PLAYER}{KUN}, as-tu assez d'objets?\nTes POKéMON sont-ils en forme?\pPour éviter les mauvaises\nsurprises, il faut être toujours\lprêt! C'est le secret!\pJe vais vérifier mes provisions!\nLa vigilance épargne bien des\lproblèmes!$"

MatchCall_PersonalizedText55::
	.string "C'est {STR_VAR_1}!\nOui, {STR_VAR_1}!\pIl y a beaucoup de passage sur\n{STR_VAR_2}. Je me bats\lcontre un tas de DRESSEURS.\pAujourd'hui, j'ai gagné cinq\ncombats et n'en ai perdu que trois!\pTu as passé une bonne journée?\nBon, tu me raconteras ça plus tard!$"

MatchCall_PersonalizedText56::
	.string "C'est moi, {STR_VAR_1}.\pMes POKéMON INSECTE sont\nfranchement cool, non?\pJe les ai ramenés à l'école pour les\nmontrer à une fille.\pEh ben, elle s'est mise à\nhurler! Trop bête, la fille!\pMoi, je pensais qu'elle les\naimerait… C'est dommage.\pSniff…\nAu revoir!$"

MatchCall_PersonalizedText57::
	.string "Ouf…\pBonjour! C'est {STR_VAR_1}!\pParler…\ntout en escaladant…\lce n'est pas facile… Ha! Ha!\pArg! Ouf…\nÇa grimpe!\lOn parlera… une autre fois…\lOuf…$"

MatchCall_PersonalizedText58::
	.string "Oh, salut!\pJe cherche des trésors avec\nRITA!\pOn n'est pas sûrs de trouver quoi\nque ce soit, tu sais…\pLe plus important pour moi,\nc'est d'être avec RITA.\pQuoi encore, RITA!?!\nPourquoi tu fais cette tête-là?\pMais non, je ne t'ignore pas, ma\npuce! Il n'y a que toi dans ma vie!\pJe dois raccrocher, {PLAYER}…$"

MatchCall_PersonalizedText59::
	.string "C'est {STR_VAR_1}!\pJe suis retourné à l'ARENE de\nMYOKARA pour m'entraîner.\pBASTIEN, le CHAMPION D'ARENE,\nest devenu bien meilleur.\pIl a parlé des vagues sauvages…\nOu un truc dans le genre.\pMais il est toujours aussi cool.\nEt il plaît toujours autant aux\lfilles! Il en a de la chance.\pTiens… Je me demande si son ami\nALDO est comme lui.\pC'est sûrement aussi le genre à\nfaire craquer les filles…\pBon, il faut que j'arrête.\nLa jalousie est un vilain défaut!\pAllez, oublie ce que je viens de\ndire!$"

MatchCall_PersonalizedText60::
	.string "C'est un plaisir de discuter avec\nun jeune DRESSEUR comme toi.\pTa passion pour les POKéMON va\ndurer, c'est évident.\pTu pourrais peut-être devenir\nnotre partenaire?\pBien sûr, {PLAYER}{KUN}.\nLa compagnie de tes fidèles\lPOKéMON te suffit amplement.\pTu sais comment faire durer une\nrelation.\pHa, ha, ha!\nNe te décourage jamais!$"

MatchCall_PersonalizedText61::
	.string "Bonjour, c'est {STR_VAR_1}!\nNous venons de gagner un combat!\pNous ne gagnons pas souvent, mais\nc'était contre un NAGEUR facile.\pMa sœur était hors d'elle!\pElle voulait jouer à la fille faible\net sans défense pour le séduire!\pQu'on gagne ou qu'on perde, elle\nn'est jamais contente!\p{PLAYER}{KUN}, tu ne pourrais pas\nessayer de lui parler?\pAllez, au revoir!$"

MatchCall_PersonalizedText62::
	.string "Bonjour, c'est {STR_VAR_1}.\nJe suis parti en mer hier.\pJe pensais y trouver quelque\népave à explorer.\pMais la marée m'a ramené chez moi\nsur la terre ferme.\pJe suis toujours mauvais au\ncombat… Mais je persévère!\pJe serai sûrement meilleur quand\nj'aurai trouvé des ruines!\pC'est tout ce que je voulais te\ndire! Au revoir!$"

MatchCall_PersonalizedText63::
	.string "Ohé, du bateau!\nC'est moi, {STR_VAR_1}!\lJe suis sur le CHENAL 108 en ce\lmoment! Enfin, comme d'habitude!\pAujourd'hui, j'ai vu une NAGEUSE\nde rêve!\pJ'ai crié pour attirer son\nattention, tu me connais!\pElle m'a fusillé du regard!\pC'était les nouvelles du\nCHENAL 108 par {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "C'est {STR_VAR_1}!\pJe suis très occupée, mais je\nvoulais te dire que j'avais battu\lcinq DRESSEURS aujourd'hui.\pSi je continue comme ça, je te\nbattrai sûrement la prochaine fois.\pJe crois que toi et moi sommes de\nbons adversaires!$"

MatchCall_BattleFrontierStreakText1::
	.string "Bonjour! C'est {STR_VAR_1}.\nJe suis au courant!\pTu as obtenu {STR_VAR_3} victoires à la\nsuite! Où? {STR_VAR_2}!\pEh bien, chapeau! Au revoir!$"

MatchCall_BattleFrontierStreakText2::
	.string "Bonjour, c'est {STR_VAR_1}.\nJe suis au courant!\p{STR_VAR_3} victoires consécutives! Mais\noù? {STR_VAR_2}! Excellent.\pIl faut que je prenne exemple sur\ntoi. Au revoir!$"

MatchCall_BattleFrontierStreakText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\pJ'ai eu vent de tes exploits! Mais\noù? {STR_VAR_2}? Joli!\p{STR_VAR_3} victoires consécutives…\nQuel record!\pJe ferais bien de prendre exemple\nsur toi! Au revoir!$"

MatchCall_BattleFrontierStreakText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pIl paraît que tu as obtenu {STR_VAR_3}\nvictoires consécutives. Mais où?\l{STR_VAR_2}?\pBon, il faut que je me remette\nsérieusement à l'entraînement!$"

MatchCall_BattleFrontierStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pJe sais que tu as gagné {STR_VAR_3}\ncombats à la suite, mais où?\l{STR_VAR_2}! Incroyable!\pIl faut que je me concentre plus\nsur mes POKéMON. A bientôt!$"

MatchCall_BattleFrontierStreakText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}. Comment vas-tu?\pJe sais que tu as obtenu {STR_VAR_3}\nvictoires à la suite dans la ZONE\lDE COMBAT. Où exactement? {STR_VAR_3}!\pJe devrais en prendre de la graine\net élever mon équipe mieux que ça.$"

MatchCall_BattleFrontierStreakText7::
	.string "Heu… {PLAYER}{KUN}?\nIci {STR_VAR_1}…\pTu as combattu dans la ZONE DE\nCOMBAT, non? {STR_VAR_2}?\pC'est vrai que tu as gagné {STR_VAR_3}\ncombats à la suite?\pJe viens d'apercevoir un POKéMON\nrare! Je te laisse!$"

MatchCall_BattleFrontierStreakText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\lÇa a l'air d'aller pour toi.\pTu as gagné {STR_VAR_3} combats à la suite\ndans la ZONE DE COMBAT.\l{STR_VAR_2}, n'est-ce pas?\pC'est très impressionnant!\nContinue sur cette voie.$"

MatchCall_BattleFrontierStreakText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pOn m'a parlé de tes {STR_VAR_3} victoires\nà la suite dans la ZONE DE COMBAT!\l{STR_VAR_2}, c'est ça?\pC'est formidable!\nBon, je ferais bien de t'imiter!$"

MatchCall_BattleFrontierStreakText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pC'est vrai que tu as gagné {STR_VAR_3}\ncombats à la suite dans la ZONE DE\lCOMBAT? {STR_VAR_2}!?!\pJe vais essayer de suivre ton\nexemple. Je dois m'améliorer.$"

MatchCall_BattleFrontierStreakText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOn va devoir t'appeler sa Majesté\n{STR_VAR_2} bientôt, non?\pTu as gagné {STR_VAR_3} combats à la\nsuite!\pC'est vraiment bien!\nJe devrais essayer, moi aussi!$"

MatchCall_BattleFrontierStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lÇa va?\pTu as gagné {STR_VAR_3} combats à\nla suite dans un endroit appelé\l{STR_VAR_2}, il paraît.\pC'est assez impressionnant.\nAu revoir!$"

MatchCall_BattleFrontierStreakText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lJ'espère que tout va bien.\pIl paraît que tu as gagné {STR_VAR_3}\ncombats à la suite dans un endroit\ldu nom de {STR_VAR_2}.\pQuelle énergie! Je t'admire.\nA bientôt.$"

MatchCall_BattleFrontierStreakText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pOn m'a parlé de toi! Tu as gagné {STR_VAR_3}\ncombats à la suite dans la ZONE DE\lCOMBAT! {STR_VAR_2}!?!\pTu es un modèle pour moi!\nAu revoir!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Bonjour, c'est {STR_VAR_1}.\nJe suis au courant!\pTu as fait des tiennes dans la ZONE\nDE COMBAT! {STR_VAR_2}?\lMagnifique!\p{STR_VAR_3} victoires consécutives,\nn'est-ce pas? Bravo!\lAllez, au revoir!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Bonjour, c'est {STR_VAR_1}!\nJ'ai entendu parler de toi!\pDans quel bâtiment de la ZONE DE\nCOMBAT as-tu gagné {STR_VAR_3} combats\là la suite? {STR_VAR_2}!\pC'est très fort, ça!\nJe devrais prendre exemple!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\pTu as fait des ravages dans la ZONE\nDE COMBAT? {STR_VAR_2}?\lJe ne savais pas.\pMais je sais que tu as obtenu\n{STR_VAR_3} victoires consécutives…\pBon, il faut que je me reprenne!\nAu revoir!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour, ça va?\pTu as obtenu {STR_VAR_3} victoires\nconsécutives dans la ZONE DE\lCOMBAT, non? {STR_VAR_2}?\pJe vais de ce pas m'entraîner,\ntiens… Au revoir!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pC'est vrai que tu as gagné {STR_VAR_3}\ncombats à la suite dans ce\lbâtiment… {STR_VAR_2}?\pMoi? On fait aller.\nA bientôt!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Salut, {PLAYER}{KUN}.\nIci {STR_VAR_1}. Comment ça va?\pIl paraît que tu as obtenu {STR_VAR_3}\nvictoires à la suite dans ce\lbâtiment… {STR_VAR_2}.\pJe ne peux pas en dire autant de\nmoi. Au revoir!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "Heu… {PLAYER}{KUN}?\nIci {STR_VAR_1}…\pC'est vrai que tu as relevé le défi\nde ce bâtiment, là…\l{STR_VAR_2}?\pEt que tu as gagné {STR_VAR_3}\ncombats à la suite?\pJe viens de voir un POKéMON rare!\nJe te laisse!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\lÇa a l'air d'aller pour toi.\pTu as gagné {STR_VAR_3} combats à la\nsuite dans la ZONE DE COMBAT.\lMais où? {STR_VAR_2}!\pC'est très impressionnant!\nContinue sur cette voie.$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pJ'ai appris que tu avais obtenu\n{STR_VAR_3} victoires consécutives au\lbâtiment {STR_VAR_2}!\pC'est formidable!\nBon, je ferais bien de t'imiter!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Coucou, {PLAYER}{KUN}…\nC'est moi, {STR_VAR_1}.\pDans quel bâtiment de la ZONE DE\nCOMBAT as-tu gagné {STR_VAR_3} combats\là la suite? {STR_VAR_2}?\pJe vais essayer de suivre ton\nexemple. Je dois m'améliorer.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOn va devoir t'appeler sa Majesté\n{STR_VAR_2} bientôt, non?\pTu as gagné {STR_VAR_3} combats à la\nsuite, non?\pC'est vraiment bien!\nJe devrais essayer, moi aussi!$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lÇa va?\pDis, as-tu gagné {STR_VAR_3} combats à\nla suite dans un endroit appelé\l{STR_VAR_2}? C'était toi!\pC'est assez impressionnant.\nAu revoir!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lJ'espère que tout va bien.\pAurais-tu par hasard gagné {STR_VAR_3}\ncombats à la suite dans un endroit\ldu nom de {STR_VAR_2}?\pQuelle énergie! Je t'admire.\nA bientôt.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lJ'ai entendu parler de toi!\pTu viens de gagner {STR_VAR_3} combats à\nla suite dans un endroit appelé\l{STR_VAR_2}, n'est-ce pas?\pTu es un modèle pour moi!\nAu revoir!$"

MatchCall_BattleDomeText1::
	.string "{PLAYER}?\nBonjour, c'est {STR_VAR_1}!\lJe suis au courant!\pTu as remporté {STR_VAR_3} fois le titre\ndu bâtiment {STR_VAR_2}!\pC'est incroyable. Je devrais avoir\nhonte de moi! Au revoir!$"

MatchCall_BattleDomeText2::
	.string "Bonjour, c'est {STR_VAR_1}!\nJe suis au courant!\pTu as remporté {STR_VAR_3} fois le titre\ndu bâtiment {STR_VAR_2}!\pC'est super! J'aimerais bien\nremporter ce titre au moins\lune fois!$"

MatchCall_BattleDomeText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\lComment ça va?\pIl paraît que tu as remporté {STR_VAR_3}\nfois le titre du bâtiment\l{STR_VAR_2}!\pNe t'arrête pas là!\nAu revoir!$"

MatchCall_BattleDomeText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pJ'ai entendu dire que tu as\nremporté le titre du bâtiment\l{STR_VAR_2} {STR_VAR_3} fois.\pJe vois que tes efforts portent\nleurs fruits! Je dois persévérer!$"

MatchCall_BattleDomeText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pOn m'a dit que tu avais remporté\n{STR_VAR_3} fois haut la main le titre du\lbâtiment {STR_VAR_2}.\pMoi aussi, je devrais m'y mettre!\nA bientôt!$"

MatchCall_BattleDomeText6::
	.string "Salut, {PLAYER}{KUN}?\n{STR_VAR_1} à l'appareil. Ça va?\pJe sais que tu as remporté le titre\ndu bâtiment {STR_VAR_2}\l{STR_VAR_3} fois.\pJe ferais bien de me concentrer sur\nmes POKéMON.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\nIci {STR_VAR_1}.\pTu as obtenu le titre du bâtiment\n{STR_VAR_2} {STR_VAR_3} fois,\ln'est-ce pas?\pPas mal du tout. Au fait, as-tu\nattrapé des POKéMON rares\laujourd'hui?\pVraiment?\nBien, au revoir.$"

MatchCall_BattleDomeText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\lÇa a l'air d'aller pour toi.\pJ'ai appris que tu avais remporté le\ntitre du bâtiment\l{STR_VAR_2} {STR_VAR_3} fois.\pJe vais élever mes POKéMON de la\nmême façon que toi. Au revoir!$"

MatchCall_BattleDomeText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pJe sais tout! Félicitations, tu as\nremporté le titre du bâtiment\l{STR_VAR_2} {STR_VAR_3} fois!\pC'est formidable!\nBon, je ferais bien de t'imiter!$"

MatchCall_BattleDomeText10::
	.string "Bonjour {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pTu as obtenu le titre du bâtiment\n{STR_VAR_2} {STR_VAR_3} fois,\lc'est bien vrai?\pJe vais essayer de suivre ton\nexemple. Je dois m'améliorer.$"

MatchCall_BattleDomeText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOn va devoir t'appeler sa Majesté\n{STR_VAR_2} bientôt, non?\pTu en as remporté le titre {STR_VAR_3} fois,\nnon?\pJe me demande si je remporterai\nun titre un jour…\pMais ça m'étonnerait…\nBon, au revoir!$"

MatchCall_BattleDomeText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lÇa va?\pTu as gagné {STR_VAR_3} fois le\ntitre d'un endroit appelé\l{STR_VAR_2}?\pC'est assez impressionnant.\nAu revoir!$"

MatchCall_BattleDomeText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lJ'espère que tout va bien.\pIl paraît que tu as obtenu {STR_VAR_3} fois\nle titre du bâtiment\l{STR_VAR_2}?\pQuelle énergie! Je t'admire.\nA bientôt.$"

MatchCall_BattleDomeText14::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\lJ'ai entendu parler de toi!\pTu as remporté {STR_VAR_3} fois le titre du\nbâtiment {STR_VAR_2}!\pTu es un modèle pour moi!\nAu revoir!$"

MatchCall_BattlePikeText1::
	.string "Bonjour, {PLAYER}!\nC'est {STR_VAR_1}!\lJe suis au courant!\pTu as traversé {STR_VAR_3} salles\ndu {STR_VAR_2}!\pC'est superbe!\nAu revoir!$"

MatchCall_BattlePikeText2::
	.string "Bonjour, c'est {STR_VAR_1}!\nJ'ai entendu parler de toi!\pIl paraît que tu as traversé {STR_VAR_3}\nsalles du {STR_VAR_2}.\pMoi, il faut que je redouble\nd'efforts! Au revoir!$"

MatchCall_BattlePikeText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\lComment ça va?\pIl paraît que tu as traversé\n{STR_VAR_3} salles du {STR_VAR_2}!\pEssaie de faire encore mieux\nla prochaine fois! Au revoir!$"

MatchCall_BattlePikeText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pAlors comme ça, tu as traversé\n{STR_VAR_3} salles du {STR_VAR_2}?\pJe ferais bien de m'occuper un peu\nmieux de mes POKéMON!$"

MatchCall_BattlePikeText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pIl paraît que tu as traversé\n{STR_VAR_3} salles du {STR_VAR_2}!\pMoi aussi, je devrais m'y mettre!\nA bientôt!$"

MatchCall_BattlePikeText6::
	.string "Hé, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Comment vas-tu?\pJ'ai entendu dire que tu avais\ntraversé {STR_VAR_3} salles du\l{STR_VAR_2}.\pJe ferais bien de me concentrer\nsur mes POKéMON.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\nIci {STR_VAR_1}.\pTu as osé entrer dans le\n{STR_VAR_2}? Et tu as\ltraversé {STR_VAR_3} salles?\pPas mal du tout.\pJe viens de voir un POKéMON rare!\nJe te laisse!$"

MatchCall_BattlePikeText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\lÇa a l'air d'aller pour toi.\pIl paraît que tu as traversé\n{STR_VAR_3} salles du {STR_VAR_2}!\pC'est très impressionnant!\nJe vais élever mes POKéMON de la\lmême façon que toi. Au revoir!$"

MatchCall_BattlePikeText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pJe suis au courant! Tu as traversé\n{STR_VAR_3} salles du {STR_VAR_2}!\pC'est formidable!\nBon, je ferais bien de t'imiter!$"

MatchCall_BattlePikeText10::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pTu as réussi à traverser\n{STR_VAR_3} salles du {STR_VAR_2}?\pJe vais essayer de suivre ton\nexemple. Je dois m'améliorer.$"

MatchCall_BattlePikeText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOn va devoir t'appeler sa Majesté\n{STR_VAR_2} bientôt, non?\pTu as traversé quoi? {STR_VAR_3} salles?\nCe n'est pas rien!\pJe me demande si je remporterai\nun titre un jour…\pMais ça m'étonnerait…\nBon, au revoir!$"

MatchCall_BattlePikeText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lÇa va?\pTu as traversé {STR_VAR_3} salles d'un\ncertain {STR_VAR_2}?\pC'est assez impressionnant.\nAu revoir!$"

MatchCall_BattlePikeText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lJ'espère que tout va bien.\pC'est vrai ce qu'on dit? Tu as\ntraversé {STR_VAR_3} salles du\l{STR_VAR_2}?\pQuelle énergie! Je t'admire.\nA bientôt.$"

MatchCall_BattlePikeText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lJ'ai entendu parler de toi!\pTu as traversé {STR_VAR_3} salles du\n{STR_VAR_2}, non?\pTu es un modèle pour moi!\nAu revoir!$"

MatchCall_BattlePyramidText1::
	.string "{PLAYER}?\nBonjour, c'est {STR_VAR_1}!\lJe suis au courant!\pTu as accédé à {STR_VAR_3} niveaux\nde la {STR_VAR_2}?\pC'est super, ça!\nJe devrais essayer d'y aller.$"

MatchCall_BattlePyramidText2::
	.string "Bonjour, c'est {STR_VAR_1}!\nJ'ai entendu parler de toi!\pIl paraît que tu as accédé à\n{STR_VAR_3} niveaux de la\l{STR_VAR_2}.\pFantastique! Je devrais m'occuper\nmieux de mes POKéMON!$"

MatchCall_BattlePyramidText3::
	.string "Salut, {PLAYER}!\nC'est moi, {STR_VAR_1}.\lComment vas-tu?\pJ'ai entendu dire que tu avais\nmonté {STR_VAR_3} niveaux de la\l{STR_VAR_2}!\pEssaie de faire encore mieux\nla prochaine fois! Au revoir!$"

MatchCall_BattlePyramidText4::
	.string "Allô, {PLAYER}{KUN}?\nIci {STR_VAR_1}. Bonjour!\pIl paraît que tu as exploré {STR_VAR_3}\nniveaux de la {STR_VAR_2}.\pJe devrais en prendre de\nla graine!$"

MatchCall_BattlePyramidText5::
	.string "Salut, {PLAYER}{KUN}!\n{STR_VAR_1} à l'appareil.\pOn m'a dit que tu avais exploré {STR_VAR_3}\nniveaux de la {STR_VAR_2}.\pMoi aussi, je devrais m'y mettre!\nA bientôt!$"

MatchCall_BattlePyramidText6::
	.string "{PLAYER}{KUN}?\nIci {STR_VAR_1}. Comment ça va?\pAu fait, il paraît que tu as accédé\nà {STR_VAR_3} niveaux de la\l{STR_VAR_2}!\pJe ferais bien de me concentrer sur\nmes POKéMON.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\nIci {STR_VAR_1}.\pTu as exploré la\n{STR_VAR_2} et accédé\là {STR_VAR_3} des niveaux?\pImpec. Est-ce que tu y as vu des\nPOKéMON rares?\pNon?\nAllez, au revoir!$"

MatchCall_BattlePyramidText8::
	.string "Ça va, {PLAYER}{KUN}?\nC'est {STR_VAR_1}.\lÇa a l'air d'aller pour toi.\pJ'ai entendu dire que tu avais\nexploré {STR_VAR_3} niveaux de la\l{STR_VAR_2}.\pC'est très impressionnant!\nJe vais élever mes POKéMON de la\lmême façon que toi. Au revoir!$"

MatchCall_BattlePyramidText9::
	.string "Salut, {PLAYER}{KUN}!\nC'est {STR_VAR_1}!\pTu as conquis {STR_VAR_3} niveaux\nde la {STR_VAR_2}! Bravo!\pC'est formidable!\nBon, je ferais bien de t'imiter!$"

MatchCall_BattlePyramidText10::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\pC'est vrai ce qu'on dit?\nTu as exploré {STR_VAR_3} niveaux\lde la {STR_VAR_2}?\pJe vais essayer de suivre ton\nexemple. Je dois m'améliorer.$"

MatchCall_BattlePyramidText11::
	.string "{PLAYER}{KUN}?\nBonjour, c'est {STR_VAR_1}.\pOn va devoir t'appeler sa Majesté\n{STR_VAR_2} bientôt, non?\pTu as vraiment exploré {STR_VAR_3}\nniveaux?\lCe n'est pas rien!\pJe me demande si je remporterai\nun titre un jour…\pMais ça m'étonnerait…\nBon, au revoir!$"

MatchCall_BattlePyramidText12::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lÇa va?\pDis-moi, as-tu réellement exploré\n{STR_VAR_3} niveaux de la\l{STR_VAR_2}?\pC'est assez impressionnant.\nAu revoir!$"

MatchCall_BattlePyramidText13::
	.string "Bonjour, {PLAYER}{KUN}!\nC'est {STR_VAR_1} qui appelle!\lJ'espère que tout va bien.\pOn dit que tu as exploré {STR_VAR_3}\nniveaux de la {STR_VAR_2}?\pQuelle énergie! Je t'admire.\nA bientôt.$"

MatchCall_BattlePyramidText14::
	.string "Bonjour, {PLAYER}{KUN}.\nC'est {STR_VAR_1}.\lJ'ai entendu parler de toi!\pC'est bien toi qui as exploré\n{STR_VAR_3} niveaux de la\l{STR_VAR_2}?\pTu es un modèle pour moi!\nAu revoir!$"

MatchCall_Text_Mom1::
	.string "MAMAN: D'abord ton père,\nmaintenant toi…\pMais qu'est-ce qui vous attire\ntant chez les POKéMON?\pMoi? J'aime les POKéMON qui peuvent\nm'aider à la maison, c'est tout.$"

MatchCall_Text_Mom2::
	.string "MAMAN: Bonjour, {PLAYER}!\nTon père passe tout son temps\ldans l'ARENE de CLEMENTI-VILLE.\pIl passe de temps en temps,\navale tout ce qu'il peut et repart\limmédiatement à l'ARENE.\pJe me fais du souci pour lui. Perdre\ncontre toi a été un gros choc!$"

MatchCall_Text_Mom3::
	.string "MAMAN: {PLAYER}…\nTout va bien à la maison, mon chou.\pUse bien les semelles de tes\nCHAUSSURES DE SPORT!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Bonjour, {PLAYER}!\pJe suis en train de me remettre\nà niveau.\pJe ne vais pas rouvrir l'ARENE\ntout de suite.\pMais dès que l'ARENE sera prête,\npasse faire un combat!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: C'est toi, {PLAYER}?\nFélicitations!\lJ'ai entendu parler de toi!\pEh bien, je ne vais pas rouvrir\nl'ARENE tout de suite.\pMais dès que l'ARENE sera prête,\npasse faire un combat!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\nL'ARENE est prête!\pJ'espère que tu vas bientôt venir\nà MEROUVILLE!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: M'être battue contre toi\ndans l'ARENE de MEROUVILLE me\lremplit de fierté, {PLAYER}.$"

MatchCall_Text_Brawly1::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\pNotre combat m'a beaucoup appris.\pJe vais suivre un entraînement\nintensif avant de rouvrir l'ARENE.\pMais ça risque de durer quelque\ntemps.\pQuand tout sera prêt, j'espère que\ntu passeras refaire un combat.$"

MatchCall_Text_Brawly2::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\nBravo!\pLa nouvelle s'est répandue comme\nune traînée de poudre!\pJe vais devoir me remettre\nsérieusement à l'entraînement.\pÇa va prendre un peu de temps\navant que je rouvre l'ARENE.\pQuand tout sera prêt, j'espère que\ntu passeras refaire un combat.$"

MatchCall_Text_Brawly3::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\nJe suis prêt à rouvrir l'ARENE!\pReviens à MYOKARA quand tu veux!$"

MatchCall_Text_Brawly4::
	.string "BASTIEN: {PLAYER}{KUN}, je ne me lasserai\njamais de me battre contre toi!$"

MatchCall_Text_Wattson1::
	.string "VOLTERE: Oh, c'est toi!\pAprès notre combat, j'ai repris\nl'entraînement depuis le début.\pJ'ai besoin d'encore un petit peu\nde temps avant de rouvrir l'ARENE.\pTu vas devoir attendre avant de\nm'affronter à nouveau. Wahahaha!$"

MatchCall_Text_Wattson2::
	.string "VOLTERE: Wahahaha!\pTu as réussi, n'est-ce pas? La\nnouvelle est arrivée jusqu'à moi!\pJ'ai encore besoin de continuer\nun peu l'entraînement.\pJe ne vais pas rouvrir l'ARENE\ntout de suite.\pTu vas devoir attendre avant de\nm'affronter à nouveau. Wahahaha!$"

MatchCall_Text_Wattson3::
	.string "VOLTERE: Oh, c'est toi!\nL'ARENE est prête!\pViens à LAVANDIA quand tu veux!\nWaaaaaouh!$"

MatchCall_Text_Wattson4::
	.string "VOLTERE: Wahahahaha!\pTon énergie me fait toujours\ndu bien!$"

MatchCall_Text_Flannery1::
	.string "ADRIANE: {PLAYER}…\pAprès notre combat, j'ai réalisé\nque je manquais d'expérience.\pMais je ne baisse pas les bras\npour autant!\pJe vais m'entraîner dur avant de\nrouvrir l'ARENE.\pQuand le moment sera venu,\nnous nous battrons, {PLAYER}.$"

MatchCall_Text_Flannery2::
	.string "ADRIANE: Salut, {PLAYER}?\nFélicitations!\pLa nouvelle de ta réussite m'a\nfait chaud au cœur!\pL'entraînement se passe à\nmerveille.\pDès que l'ARENE sera prête, une\nmarque apparaîtra près de mon\lnom dans la liste du MATCH PHONE.$"

MatchCall_Text_Flannery3::
	.string "ADRIANE: Oh, {PLAYER}?\nL'ARENE est prête!\pViens à VERMILAVA! On a des\nsources chaudes et j'aimerais\lme battre de nouveau contre toi!$"

MatchCall_Text_Flannery4::
	.string "ADRIANE: {PLAYER}…\nJe vois que tu ne cesses de\lprogresser.$"

MatchCall_Text_Winona1::
	.string "ALIZEE: Bonjour, {PLAYER}!\pNotre combat m'a permis de\ncomprendre mes points faibles!\pQuand je rouvrirai l'ARENE,\nj'aurai beaucoup progressé!$"

MatchCall_Text_Winona2::
	.string "ALIZEE: Bravo, {PLAYER}!\pTout le monde à CIMETRONELLE\nsait qui est le nouveau MAITRE!\pMais… l'issue de notre prochain\ncombat sera différente, crois-moi.$"

MatchCall_Text_Winona3::
	.string "ALIZEE: C'est toi, {PLAYER}?\nJ'ai rouvert l'ARENE!\pOn t'attend tous à\nCIMETRONELLE!$"

MatchCall_Text_Winona4::
	.string "ALIZEE: {PLAYER}…\nJ'ai perdu, mais cette défaite ne\lva pas m'ébranler.\pTu peux comprendre, car toi aussi\ntu vis pour tes rêves.$"

MatchCall_Text_TateLiza1::
	.string "LEVY: Oh! C'est…\nTATIA: {PLAYER}!\pLEVY: On a repris l'entraînement…\nTATIA: pour rouvrir l'ARENE!\pLEVY: Quand l'ARENE sera prête…\nTATIA: il y aura un symbole…\pLEVY: près de nos noms dans…\nTATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza2::
	.string "LEVY: Félicitations, {PLAYER}!\nTATIA: Félicitations, {PLAYER}!\pLEVY: Nous, on s'entraîne…\nTATIA: encore!\pLEVY: Quand l'ARENE sera prête…\nTATIA: il y aura un symbole…\pLEVY: près de nos noms dans…\nTATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza3::
	.string "LEVY: {PLAYER}!\nTATIA: {PLAYER}!\pLEVY: L'ARENE est prête!\nTATIA: L'ARENE est prête!\pLEVY: Passe nous voir…\nTATIA: à ALGATIA!$"

MatchCall_Text_TateLiza4::
	.string "LEVY: {PLAYER}, notre combat…\nTATIA: a été une expérience unique.\pLEVY: Ce serait bien si on faisait…\nTATIA: un autre combat bientôt!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hum…\n{PLAYER}{KUN}… C'est ça?\pNotre combat m'a rappelé la\npremière fois que j'ai vu MARC.\pPeut-être arriverez-vous à\nsurpasser MARC? Qui sait!?!$"

MatchCall_Text_Juan2::
	.string "JUAN: Dites donc… {PLAYER}{KUN}…\nVous avez atteint votre objectif!\pVous voyez, j'ai l'œil pour\ndécouvrir les nouveaux talents…\pVous avez réussi à atteindre le\nsommet de la gloire. J'espère vous\lrevoir bientôt!$"

MatchCall_Text_Juan3::
	.string "JUAN: Ho, ho… {PLAYER}{KUN}…\pL'ARENE d'ATALANOPOLIS a enfin\nrouvert.\pSi vous voulez me voir, vous pouvez\npasser quand vous voulez.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\pQuand je me bats contre vous, c'est\ncomme si une musique\lmajestueuse jouait dans mon cœur…\pEn fermant les yeux, je vous vois\ndanser gracieusement…$"

MatchCall_Text_Sidney::
	.string "DAMIEN: Salut, {PLAYER}!\pRepasse quand tu veux à la LIGUE\nPOKéMON si tu veux te battre\lencore contre moi.\pJ'y serai!\nJe t'attends!$"

MatchCall_Text_Phoebe::
	.string "SPECTRA: Salut, {PLAYER}!\pTu devrais passer nous voir, un de\nces jours!\pJ'aimerais voir à quel point ton\nattachement à tes POKéMON a\lgrandi.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Salut, {PLAYER}.\pJure-moi que tu n'as pas pris la\ngrosse tête!\pSi tu as besoin d'une petite douche\nfroide, passe à la LIGUE POKéMON…$"

MatchCall_Text_Drake::
	.string "ARAGON: Cette voix…\nC'est toi, {PLAYER}?\pJe sais que maintenant il y a la\nZONE DE COMBAT où les DRESSEURS\lpeuvent tester leurs aptitudes.\pMais si tu veux faire de vrais\ncombats, on n'a encore rien inventé\lde mieux que la LIGUE POKéMON!\pTu ne crois pas, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "MARC: Salut, {PLAYER}{KUN}.\nAs-tu rencontré PIERRE?\pIl est… Comment dire…\nIl est vraiment doué!\pMais il se bat très rarement,\nc'est un solitaire.\pIl préfère chercher des pierres\nrares.\pAu moment où on parle, il est\nsûrement en train de creuser\ldans une caverne ou une montagne.\pC'est quoi une pierre rare, en fait?\nJe ne vois que les METEORITES…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n… … … … … Bip!\pFLORA: Bonjour, {PLAYER}{KUN}!\pJe suis allée à PACIFIVILLE\nil y a quelques jours.\pJ'y ai vu un POKéMON géant\nde couleur verte voler dans le ciel!\pJe n'avais jamais vu une chose\npareille…\pJe me demande bien ce que c'était.\nC'est peut-être une découverte!\p… … … … … …\n… … … … … Clic!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n… … … … … Bip!\pBRICE: Salut, {PLAYER}!\nJe reviens de PACIFIVILLE.\pJ'y ai vu un POKéMON géant de\ncouleur verte voler dans le ciel!\pJe n'avais jamais vu un truc pareil!\pJ'aurais aimé que tu voies ça,\n{PLAYER}.\p… … … … … …\n… … … … … Clic!$"

MatchCall_Text_May1::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pM. MARCO a pris sa retraite de\nMARIN, mais de temps en temps,\lje le vois en mer avec son PIKO.\pLa mer, c'était plus qu'un travail\npour lui. C'est une vraie passion.$"

MatchCall_Text_May2::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pTu sais qu'il y a une ARENE à\nCLEMENTI-VILLE et MYOKARA?\lCe sont pourtant de petites villes.\pPar contre, il n'y en a pas dans la\ngrande ville portuaire de\lPOIVRESSEL.\pLe jour où ils en construiront une,\nje postulerai pour le poste de\lCHAMPION D'ARENE.$"

MatchCall_Text_May3::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pTu te souviens de l'homme de la\nMAISON COUPCOUP à MEROUVILLE?\pJe viens d'apprendre qu'il a un\npetit frère qui habite à LAVANDIA.\pTu veux savoir comment il\ns'appelle?\p… … … … … …\n… … … … … …\pTYPE ECLATE-ROC!$"

MatchCall_Text_May4::
	.string "FLORA: {PLAYER}{KUN}?\pTUNNEL MERAZON…\nIls l'ont appelé comme ça parce \lqu'il relie MEROUVILLE à VERGAZON.$"

MatchCall_Text_May5::
	.string "FLORA: Comment ça va, {PLAYER}{KUN}?\pJe suis sur la ROUTE 111.\pJe vais faire une halte chez une\ndame âgée pour me reposer.\pElle habite au nord du désert.$"

MatchCall_Text_May6::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pTu connais la TOUR MIRAGE\nqui se trouve dans le désert?\pElle disparaît parfois\nmystérieusement, puis réapparaît\ltel un mirage.\pJ'aimerais bien la voir.$"

MatchCall_Text_May7::
	.string "FLORA: Salut, {PLAYER}{KUN}!\nJe suis sur la ROUTE 119.\pIl y a une rivière immense.\nEt il n'arrête pas de pleuvoir.\pJe suis trempée jusqu'aux os!$"

MatchCall_Text_May8::
	.string "FLORA: Bonjour, {PLAYER}{KUN}.\pLe MONT MEMORIA est un mémorial\ndédié aux POKéMON qui nous ont\lmalheureusement quittés.\pForcément, le lieu est rempli de\nPOKéMON de type SPECTRE!$"

MatchCall_Text_May9::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pJe pensais aller aux sources\nchaudes de VERMILAVA.\pMais près du SENTIER SINUROC, j'ai\nrencontré des gens bizarres. Ils\ln'avaient pas l'air de bonne humeur.$"

MatchCall_Text_May10::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\nTu es au courant?\pIl paraît que le CAPT. POUPE a\ndécouvert la CAVERNE FONDMER lors\lde son expédition sous-marine.$"

MatchCall_Text_May11::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\nTu sais quoi?\pSi tu n'as pas de bateau, il y a une\ncapacité de POKéMON qui peut te\lfaire flotter sur l'eau.\pEt ce n'est pas tout!\pIl y a même une autre capacité qui\npermet d'aller au fond de la mer.$"

MatchCall_Text_May12::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\nTout va bien?\pTu as dû voir que parfois on ne\npeut pas traverser la mer.\lC'est tout simplement bloqué.\pIl faut plonger sous l'eau et\nsuivre les sillons.\pUne fois de l'autre côté, il suffit\nde remonter à la surface. Facile!$"

MatchCall_Text_May13::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\pComment ça va?\nTu remplis bien ton POKéDEX?\pJ'ai entendu dire qu'il y a des\nPOKéMON très anciens par ici.\lIl y en aurait trois!\pJ'aimerais bien en voir au\nmoins un…$"

MatchCall_Text_May14::
	.string "FLORA: {PLAYER}{KUN}!\nLes gens parlent de toi!\pTu as battu le CHAMPION D'ARENE\nd'ATALANOPOLIS, c'est super!\pIl ne te reste plus beaucoup de\nchemin à parcourir.$"

MatchCall_Text_May15::
	.string "FLORA: Il n'y a pas un seul\nDRESSEUR à HOENN qui n'ait jamais\lentendu parler de toi, {PLAYER}{KUN}!\pQuand je dis aux gens que je\nte connais, {PLAYER}{KUN}, ils sont\limpressionnés!$"

MatchCall_Text_Brendan1::
	.string "BRICE: Salut, {PLAYER}!\pM. MARCO a pris sa retraite de\nMARIN, mais il part toujours en\lmer avec son PIKO.\pCe n'est pas parce qu'il est à la\nretraite qu'il va oublier la mer!$"

MatchCall_Text_Brendan2::
	.string "BRICE: Salut, {PLAYER}!\pPourquoi CLEMENTI-VILLE\net MYOKARA ont une ARENE?\pAprès tout, POIVRESSEL n'en a pas\net c'est beaucoup plus grand!\pS'il y en avait une, je voudrais en\nêtre le CHAMPION.$"

MatchCall_Text_Brendan3::
	.string "BRICE: Bonjour, {PLAYER}!\pTu te souviens de la MAISON\nCOUPCOUP à MEROUVILLE?\pL'homme qui y vit a un petit frère\nà LAVANDIA.\pDevine comment il s'appelle!\p… … … … … …\n… … … … … …\pTYPE ECLATE-ROC!$"

MatchCall_Text_Brendan4::
	.string "BRICE: {PLAYER}?\pTu sais que le TUNNEL MERAZON\ns'appelle comme ça parce qu'il\lrelie MEROUVILLE à VERGAZON?\pTu le savais?$"

MatchCall_Text_Brendan5::
	.string "BRICE: {PLAYER}, quoi de neuf?\pJe suis sur la ROUTE 111, là.\pJe vais me reposer un peu chez une\nvielle dame au nord du désert.\pSi tu es dans le coin, tu pourrais\naussi lui rendre visite.$"

MatchCall_Text_Brendan6::
	.string "BRICE: Hé, {PLAYER}!\pTu as entendu parler de la TOUR\nMIRAGE dans le désert?\pIl paraît qu'on ne peut pas la voir\ntout le temps, comme un mirage!\pÇa, c'est un truc à voir!$"

MatchCall_Text_Brendan7::
	.string "BRICE: Qui c'est? {PLAYER}!\nJe suis sur la ROUTE 119.\pIl y a une grosse rivière et il pleut\ndes cordes.\pJe suis complètement trempé!$"

MatchCall_Text_Brendan8::
	.string "BRICE: {PLAYER}!\pLe MONT MEMORIA est dédié aux\nPOKéMON qui nous ont quittés.\pDu coup, tous les POKéMON de type\nSPECTRE y vont!$"

MatchCall_Text_Brendan9::
	.string "BRICE: Salut, {PLAYER}.\pJe suis allé aux sources chaudes\nde VERMILAVA aujourd'hui.\pJ'ai croisé des gens à l'air louche\nprès du SENTIER SINUROC.\pDes sales types…\nÇa devait être la TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRICE: Bonjour, {PLAYER}!\nTu es au courant?\pLe CAPT. POUPE a découvert la\nCAVERNE FONDMER pendant une\lexpédition sous-marine.$"

MatchCall_Text_Brendan11::
	.string "BRICE: Hé! Salut, {PLAYER}!\nJe vais t'apprendre un truc!\pIl y a une capacité de POKéMON\nqui permet d'aller en mer même\lsi on n'a pas de bateau!\pEt il y en a aussi une qui permet\nd'aller au fond de la mer.\pJe trouve ça dingue!$"

MatchCall_Text_Brendan12::
	.string "BRICE: Salut, {PLAYER}!\nÇa va comme tu veux?\pTu sais que parfois il est\nimpossible de franchir la mer?\pDans ces cas-là, il faut plonger et\nsuivre les sillons au fond de la mer.\pUne fois de l'autre côté, il suffit\nde revenir à la surface! Enfantin!$"

MatchCall_Text_Brendan13::
	.string "BRICE: Salut, {PLAYER}!\pTu vas bien? Ça avance ton\nPOKéDEX?\pIl paraît qu'il y a des POKéMON très\nanciens dans le coin. Trois!\pJ'aimerais en attraper au moins un…$"

MatchCall_Text_Brendan14::
	.string "BRICE: {PLAYER}!\nHé, je suis au courant!\pTu as battu le CHAMPION D'ARENE\nd'ATALANOPOLIS! Trop cool!\pTu es près du but!$"

MatchCall_Text_Brendan15::
	.string "BRICE: Tous les DRESSEURS te\nconnaissent à HOENN, {PLAYER}!\pLes gens ne me croient même pas\nquand je leur dis que je suis l'ami\lde {PLAYER}! Ils sont tous jaloux.$"

MatchCall_Text_Wally1::
	.string "TIMMY: Oh, {PLAYER}!\pJe suis en bien meilleure\nforme, maintenant.\pJ'espère être bientôt un aussi bon\nDRESSEUR que toi, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "TIMMY: Salut, {PLAYER}!\pDepuis que le TUNNEL MERAZON\nest creusé, SYLVIE est aux anges!$"

MatchCall_Text_Wally3::
	.string "TIMMY: Oh, {PLAYER}!\pJe suis parti de chez mon oncle\nà VERGAZON sans prévenir personne.\pIl doit être furieux contre moi…\pMais {PLAYER}… Toi, tu me comprends,\nnon?$"

MatchCall_Text_Wally4::
	.string "TIMMY: {PLAYER}?\nC'est moi, TIMMY!\pL'univers des DRESSEURS,\nc'est quelque chose!\pDès que tu as des POKéMON, tout\nle monde te parle!\pC'est comme si les POKéMON\nrapprochaient les gens!$"

MatchCall_Text_Wally5::
	.string "TIMMY: {PLAYER}? Tu sais quoi?\nLe TARSAL qu'on a capturé\lensemble a évolué!\pPeut-être que je suis doué,\naprès tout…\pEn tout cas, il ne faut pas que\nje prenne la grosse tête!\pC'est le POKéMON qui fait le\nplus gros du travail!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n… … … … … …\pTIMMY est dans un endroit non\ncouvert par le réseau POKéNAV…$"

MatchCall_Text_Wally7::
	.string "TIMMY: Oh, {PLAYER}!\pAvant de te connaître, je passais\ntout mon temps à la maison…\pEt maintenant, je sillonne les\nroutes avec mes POKéMON!\p{PLAYER}…\nJe te dois tant…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Bien le bonjour, {PLAYER}{KUN}!\pTu sais qu'on trouve des POKéMON\nabsolument partout?\pEn montagne, dans la mer,\ndans les hautes herbes!?!\pDe même, tu peux rencontrer des\nDRESSEURS partout.\pC'est pour ça que je cours toujours\nà droite à gauche!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Je suis sur la ROUTE 119.\nÇa grouille de DRESSEURS ici!\pLe sol est recouvert de hautes\nherbes.\pJe suis en short, l'herbe me\nchatouille les gambettes!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Bonjour, bonjour, {PLAYER}{KUN}!\pAs-tu déjà eu l'occasion de gravir\nle MONT MEMORIA?\pC'est un mémorial dédié aux\nPOKéMON qui nous ont quittés.\pLes DRESSEURS devraient tous\ny monter au moins une fois.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Bonjour, {PLAYER}{KUN}!\pJ'ai entendu parler de ces deux\nbandes qui font du grabuge.\pTEAM MAGMA et TEAM AQUA,\nje crois.\pIl doit y avoir quelques bons\nDRESSEURS parmi eux.\pMais ce sont des brutes…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Tiens! Bonjour, {PLAYER}{KUN}.\pY a-t-il de bons DRESSEURS\nau fond de la mer?\pJe ne peux pas vérifier moi-même.\nJe ne sais pas nager.\lEt je n'élève pas de POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Bonjour, bonjour, {PLAYER}{KUN}!\pTu sais que si tu as tous les\nBADGES D'ARENES, tu as le droit\lde défier la LIGUE POKéMON?\pAvec ton talent, tu as toutes les\nchances de devenir MAITRE.\pMais tu sais…\nIl y a un endroit encore mieux.\pJe ne veux pas t'en dire plus pour\nl'instant.\pMais penses-y.\pQuand la LIGUE POKéMON et le\nPANTHEON DES DRESSEURS\lseront derrière toi!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n… … … … … …\pSCOTT est dans un endroit non\ncouvert par le réseau POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPA: A MEROUVILLE, il y a un\nendroit qui s'appelle la MAISON\lCOUPCOUP. Quel drôle de nom!\pVas-y, si tu es dans le coin.$"

MatchCall_Text_Norman2::
	.string "PAPA: Hum… Tu fais des\nprogrès, {PLAYER}.\pPlus le temps passe et plus tu\nt'éloignes de ta mère et moi…\pC'est un drôle de sentiment.$"

MatchCall_Text_Norman3::
	.string "PAPA: Je vois…\nTu as quatre BADGES…\pJe vais devoir tenir ma promesse.\nNous allons nous battre.\pViens quand tu veux.\nJe t'attendrai.$"

MatchCall_Text_Norman4::
	.string "PAPA: {PLAYER}! Tu devrais rendre\nvisite à ta mère de temps en temps.\pMoi, je reste ici. Je m'entraîne\ndur.\pLa voie qui mène à la perfection\nest un chemin sans fin!$"

MatchCall_Text_Norman5::
	.string "PAPA: Bonjour, {PLAYER}!\pQuoi? Un SCEAU MAGMA?\nJe n'en ai jamais entendu parler.\pMais vu le nom, ça doit avoir un\nrapport avec un volcan!$"

MatchCall_Text_Norman6::
	.string "PAPA: Allez! C'est ça!\pOh? {PLAYER}!\pJe suis en pleine séance\nd'entraînement avec mes POKéMON!$"

MatchCall_Text_Norman7::
	.string "PAPA: {PLAYER}!\pSi j'avais su que tu deviendrais le\nMAITRE de la LIGUE POKéMON…\pBien! Je dois réagir!\nJe ne vais pas me laisser faire!$"

MatchCall_Text_Norman8::
	.string "PAPA: Hum? {PLAYER}?\nTu appelles au bon moment!\pJe t'invite à venir faire un combat\ncontre moi.\pJe suis dans l'ARENE de\nCLEMENTI-VILLE.$"

MatchCall_Text_Norman9::
	.string "PAPA: Tu m'épates, {PLAYER}.\nMais jusqu'où iras-tu?$"

MatchCall_Text_Steven1::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\pAs-tu déjà visité LAVANDIA?\pTu devrais aller te procurer un\nVELO COURSE aux CYCLES\lRODOLPHE.\pEnsuite, je te conseille d'aller\nexplorer la GROTTE GRANITE.\pTu pourrais bien y faire une\ndécouverte.$"

MatchCall_Text_Steven2::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\pJ'ai rencontré beaucoup de\nDRESSEURS dans ma vie.\pMais toi, tu n'es pas comme les\nautres. Ça saute aux yeux.$"

MatchCall_Text_Steven3::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\pQuand tu es sur la route avec tes\nPOKéMON, à quoi penses-tu?\pTu les considères comme des\npartenaires solides?\pOu plutôt comme d'agréables\npetits camarades?\pLes enjeux de ton périple\nsont liés à ton état d'esprit.$"

MatchCall_Text_Steven4::
	.string "PIERRE: Allô?\n{PLAYER}{KUN}?\pJe suis au CENTRE SPATIAL.\nJ'ai des ennuis, là.\pJe suis désolé, je ne peux pas\nparler. Au revoir!$"

MatchCall_Text_Steven5::
	.string "PIERRE: Oh!\n{PLAYER}{KUN}!\pCe n'est plus le moment de\ndiscuter. Il n'y a plus rien à dire.\pTu dois croire en toi et faire ce\nque tu penses être juste.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\pPIERRE ne prend pas l'appel…$"

MatchCall_Text_Steven7::
	.string "PIERRE: {PLAYER}{KUN}… Bravo pour ton\nentrée au PANTHEON DES DRESSEURS.\p… … … … … …\n… … … … … …\pJ'espère que nos chemins se\ncroiseront de nouveau!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. SEKO: Oh, {PLAYER}{KUN}!\nJ'ai entendu parler de toi, tu sais!\pOn dirait que ton POKéNAV a été\néquipé du MATCH PHONE.\pIl faudrait que j'y sois enregistré!\pComme ça, je pourrai garder un œil\nsur ton POKéDEX même quand tu\les en vadrouille.\p… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Vous avez enregistré PROF. SEKO\ndans le POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\nthe POKéDEX and POKéNAV, studying\lPOKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}!\pJe suis content de voir que\nle POKéNAV fonctionne!\pD'autres personnes y seront\nenregistrées, alors tu auras\lplein de gens à appeler!\pÇa a l'air de te faire plaisir!\pHum…\nComment je sais ça?\pMais je te vois de la fenêtre\nde mon bureau, pardi!\pHa, ha, ha!\nA bientôt!$"

MatchCall_Text_MrStone2::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}!\pDis, tu as oublié la course que\nje t'ai demandée de faire?\pJ'ai besoin que tu donnes ma\nlettre à PIERRE à MYOKARA…\pet que tu apportes le paquet au \nCAPT. POUPE à POIVRESSEL.\pTu n'as pas oublié, dis?\pJe te laisse, je suis un DIRECTEUR\ntrès occupé! Au revoir!$"

MatchCall_Text_MrStone3::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}!\pTu as vu PIERRE?\nUne récompense t'attend, alors!\pQuand tu seras de passage à\nMEROUVILLE, viens à mon bureau.\pA bientôt!$"

MatchCall_Text_MrStone4::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}!\pTu savais que DEVON creusait\nle TUNNEL MERAZON?\pMais on a dû arrêter pour préserver\nles POKéMON de cette zone.\pFranchement, si ça ne tenait qu'à\nmoi…\pSi on s'arrête à ce genre de\ndétails, on ne fait plus rien!$"

MatchCall_Text_MrStone5::
	.string "M. ROCHARD: Bonjour, {PLAYER}{KUN}!\pQuelqu'un de CLEMENTI-VILLE m'a\ndit que NORMAN est ton père!\pTu as de qui tenir!$"

MatchCall_Text_MrStone6::
	.string "M. ROCHARD: Comment?\pTu as battu ton propre père?\pMais c'est ahurissant!\pTu n'es pas n'importe qui, toi!\nHa, ha, ha!$"

MatchCall_Text_MrStone7::
	.string "Allô?\nDEVON SARL, j'écou…\l{PLAYER}! Bonjour!\pMalheureusement, le DIRECTEUR\nvient de s'absenter.\pLe DIRECTEUR est très occupé.\nComme toi, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "Hein? Comment?\pGROU… Quoi? DON?\pLa ligne est mauvaise…\nJe ne t'entends plus…\pBZZZZ…$"

MatchCall_Text_MrStone9::
	.string "Hein? Comment?\pLa CAV… Quoi? FONDMER?\pLa ligne est mauvaise…\nJe ne t'entends plus…\pBZZZZ…$"

MatchCall_Text_MrStone10::
	.string "M. ROCHARD: {PLAYER}{KUN}! C'est moi!\pJe sais que tu as réalisé toutes\nsortes de choses, mais je n'ai\lpas le temps de me tenir informé!\pQuoi qu'il en soit, continue comme\nça, je me fie à ton jugement.\pEt si tu as besoin de moi,\nn'hésite pas à appeler.$"

MatchCall_Text_MrStone11::
	.string "M. ROCHARD: … … … … … …\nC'est toi, {PLAYER}{KUN}?\pTa voix a pris tant d'assurance que\nje ne n'ai pas pu te reconnaître!\pPasse me voir à DEVON,\nà l'occasion!$"
