MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Cette capacité ne peut être\napprise qu'une fois, OK?$"

MoveTutor_Text_SwaggerTeach:
	.string "Hé! Mon POKéMON, c'est de la balle!\nC'est le plus cool de tous les POKéMON!\pL'autre jour, j'ai dit ça devant le\nPRESIDENT et je me suis fait\lremonter les bretelles.\pDu coup, j'essaie de me vanter un peu\nmoins.\pMais si tu veux, je peux apprendre\nVANTARDISE à un de tes POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Non? Alors toi, tu ne comprends\ncarrément rien aux POKéMON!$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Cool. A quel POKéMON tu veux que\nj'enseigne VANTARDISE?$"

MoveTutor_Text_SwaggerTaught:
	.string "Dorénavant, je complimenterai mes\nPOKéMON et j'arrêterai de me vanter.$"

MoveTutor_Text_RolloutTeach:
	.string "Tu sais que si tu vas dans cette\ndirection, tu peux avancer longtemps\lsans avoir à tourner?\pJe suis sûr qu'on peut même y aller\nen roulant.\pTiens, tu crois que tes POKéMON\naimeraient rouler, eux aussi?\pJe pourrais enseigner ROULADE à\nl'un d'entre eux, si tu veux.$"

MoveTutor_Text_RolloutDeclined:
	.string "Je vois, tu es timide.\nPas de problème, ça roule!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Super! Ce que j'aimerais que les\nPOKéMON me ressemblent.$"

MoveTutor_Text_RolloutTaught:
	.string "Rouler dans l'herbe me met toujours\nde bonne humeur! Ça roule!!!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Il existe une capacité qui gagne en\npuissance quand on l'utilise plusieurs\lfois de suite.\pC'est une super capacité de type\nINSECTE.\pElle s'appelle TAILLADE.\nJe l'enseigne à un de tes POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "On n'est pas sur la même longueur\nd'ondes.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Super!\nQuel POKéMON est l'heureux élu?$"

MoveTutor_Text_FuryCutterTaught:
	.string "Rien n'est plus beau qu'un POKéMON\nutilisant encore et encore cette\lcapacité!$"

MoveTutor_MimicTeach:
	.string "Je suis jeune, mais j'aime copier le\nstyle des personnes âgées de la ville.\pEt si j'apprenais COPIE à un\nde tes POKéMON?\pQu'en dis-tu, mon p'tit?$"

MoveTutor_MimicDeclined:
	.string "Boudiou! Les jeunes d'aujourd'hui,\nquelle ingratitude!$"

MoveTutor_Text_MimicWhichMon:
	.string "Oh, oh! Je pense bien!\nA quel POKéMON dois-je enseigner\lCOPIE?$"

MoveTutor_Text_MimicTaught:
	.string "COPIE est une capacité très difficile à\nmaîtriser.\pQui sait, peut-être sauras-tu l'utiliser\naussi bien que moi?$"

MoveTutor_Text_MetronomeTeach:
	.string "Moi, j'ai des goûts de luxe!\nMais je ne suis pas riche…\pCe que j'aimerais pouvoir faire\napparaître tout ce que je veux,\pjuste en bougeant un doigt!\pSi tu veux, je peux apprendre\nMETRONOME à tes POKéMON.\pRien n'apparaîtra mais ton POKéMON\nbougera un doigt. Tu veux?$"

MoveTutor_Text_MetronomeDeclined:
	.string "D'accord. Si tu changes d'avis, je serai\nlà.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Super! A quel POKéMON dois-je\nenseigner cette capacité?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quand un POKéMON bouge le doigt\ncomme un METRONOME, plein de\lbonnes choses peuvent se produire.\pCe serait tellement bien, si ça\nmarchait aussi pour les humains!$"

MoveTutor_Text_SleepTalkTeach:
	.string "Tu sais, mon p'tit, ma femme a besoin de\nPUISSANCE CACHEE pour rester éveillée.\pPour moi, c'est BLABLA DODO!\nJe dors, un point c'est tout!\pSi tu veux, je peux enseigner BLABLA\nDODO à un de tes POKéMON. Tu veux?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Toi aussi, tu préfères lutter contre\nle sommeil avec PUISSANCE CACHEE…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, voilà qui est bien répondu!\nA quel POKéMON dois-je l'enseigner?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Je n'ai jamais bien compris le tour\nde magie de ma femme.\pJ'aimerais le maîtriser aussi bien\nque BLABLA DODO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quand j'observe le monde, perchée\nsur ce toit…\pJe me dis qu'il y a tellement de choses\nà faire, de territoires à explorer, que\lj'aimerais vivre plusieurs vies à la fois.\pJe sais bien que c'est impossible,\nmais les journées sont trop courtes…\pÇa me fait penser… Et si j'enseignais\nCLONAGE à un de tes POKéMON?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Non?\pUn POKéMON peut créer un double de\nlui-même avec… Enfin, c'est\lcomme tu veux.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hi, hi!\nA quel POKéMON dois-je enseigner\lCLONAGE?$"

MoveTutor_Text_SubstituteTaught:
	.string "Nous, les humains, devrions profiter\nà fond de l'instant présent!\pEnfin, c'est ce que je pense!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Je n'en peux plus!\pC'est sans espoir!\pJe suis un DRESSEUR de type COMBAT,\nalors je n'arrive à rien dans l'ARENE\ld'ALGATIA!\pTiens! Prends ça! Un coup de poing!\nEt encore ça! Un autre coup de poing!\pNe me fais pas ces yeux-là!\nJe ne frappe que le sol!\pTu veux peut-être que j'enseigne\nDYNAMOPOING à un de tes POKéMON?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Tu te moques de moi? Je frapperais bien\nautre chose que le sol, tu sais!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Tiens, voilà quelqu'un d'intelligent!\nA quel POKéMON dois-je l'enseigner?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Je veux que tu gagnes à l'ARENE\nd'ALGATIA grâce à DYNAMOPOING!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Bouh…\pLe CHAMPION D'ARENE d'ATALANOPOLIS\nest vraiment admirable.\pCe qui veut dire que beaucoup de\ngens veulent le défier.\pJe n'ai même pas réussi à attirer son\nattention avec DAMOCLES!\pEst-ce que je peux enseigner DAMOCLES\nà un de tes POKéMON?$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\nTu vois, toi aussi, tu me rejettes…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "A quel POKéMON dois-je enseigner\nDAMOCLES?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Je vais m'endurcir!\nPlus question de tomber amoureuse!$"

MoveTutor_Text_ExplosionTeach:
	.string "J'ai la ferme intention de faire quelque\nchose de ma vie, je te le dis!\pRegarde-moi bien, parce que je ne vais\npas rester longtemps ici.\pOn va entendre parler de moi!\nCe sera une vraie EXPLOSION!\pA propos d'EXPLOSION… J'enseigne\ncette capacité à un de tes POKéMON?$"

MoveTutor_Text_ExplosionDeclined:
	.string "Tu ne me fais pas confiance parce que\nj'ai décidé de partir, c'est ça?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Super, ça va faire du bruit! A quel\nPOKéMON dois-je enseigner EXPLOSION?$"

MoveTutor_Text_ExplosionTaught:
	.string "Ça fait longtemps que j'enseigne\nEXPLOSION aux POKéMON sans jamais\lpenser à ma propre EXPLOSION…\pPeut-être est-ce parce qu'au fond,\nje préfèrerais rester ici…$"
