gText_ObtainedTheItem::
	.string "Obtenu: {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Le SAC est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} met {STR_VAR_2} dans\nPOCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Dommage!\nLe SAC est plein.$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} met {STR_VAR_2} dans\nle SAC.$"

gText_ObtainedTheDecor::
	.string "Obtenu: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Dommage! Il n'y a plus assez de place\npour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Transfert de {STR_VAR_2} sur le PC.$"
