gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} a été transféré sur le\nPC de ???.\pIl a été placé dans la BOITE\nappelée «{STR_VAR_1}»$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} a été transféré sur le\nPC d'ANNETTE.\pIl a été placé dans la BOITE\nappelée «{STR_VAR_1}»$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La BOITE {STR_VAR_3} sur le PC\nde ??? est pleine.\p{STR_VAR_2} a été placé dans la\nBOITE appelée «{STR_VAR_1}».$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La BOITE «{STR_VAR_3}» sur le PC\nd'ANNETTE est pleine.\p{STR_VAR_2} a été placé dans la\nBOITE appelée «{STR_VAR_1}».$"

gText_NoMoreRoomForPokemon::
	.string "Il n'y a plus de place pour\nles POKéMON.\pLes BOITES sont pleines et\nne peuvent plus rien recevoir.$"

gText_NicknameThisPokemon::
	.string "Voulez-vous donner un surnom\nà {STR_VAR_1}?$"
