gText_WouldYouLikeToRestYourPkmn::
    .string "Bonjour! Bienvenue au CENTRE\nPOKéMON.\pNous pouvons soigner vos POKéMON.\pVoulez-vous les soigner?$"

gText_IllTakeYourPkmn::
    .string "OK, je prends vos POKéMON un instant.$"

gText_RestoredPkmnToFullHealth::
    .string "Merci d'avoir attendu.\pVos POKéMON sont en super\nforme.$"

gText_WeHopeToSeeYouAgain::
    .string "A une prochaine fois peut-être!$"

gText_WelcomeCutShort::
    .string "Bonjour! Bienvenue au CENTRE\nPOKéMON.\pNous pouvons soigner vos POKéMON.\pVoulez-vous les…$"

gText_NoticesGoldCard::
    .string "Ce… Cette carte…\nSerait-ce la CARTE OR?!\pOh, ce jaune or est si brillant!\nLes quatre étoiles étincellent presque!\pJ'ai déjà vu des DRESSEURS avec\ndes CARTES ARGENT, mais…\pVous êtes le premier DRESSEUR que je\nvois avec une CARTE OR!\pAccordez-moi l'honneur de soigner\nvos POKéMON un instant!$"

gText_YouWantTheUsual::
    .string "Contente de vous voir, {PLAYER}!\nOn fait comme d'habitude?$"

gText_IllTakeYourPkmn2::
    .string "OK, je prends vos POKéMON un instant.$"

gText_ThankYouForWaiting::
    .string "Merci d'avoir attendu.$"

gText_WeHopeToSeeYouAgain2::
    .string "Encore merci et à bientôt!$"
