
gPokeNewsTextSlateport_Upcoming::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pL'homme le plus adulé de POIVRESSEL,\nle MAITRE DE LA FORME fait encore\lparler de lui!\pIl a déclaré: «Je réserve une surprise\nsans précédent à tous, dans quelques\ljours: exactement {STR_VAR_1}!»\pIl n'a pas voulu dévoiler son secret,\nmais il a tenu à préciser:\l«Economisez! Ça en vaudra la peine…»\pIl est donc conseillé à tous d'aller\nfaire un tour à POIVRESSEL ce jour-là.\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextSlateport_Ongoing::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pEt voici la nouvelle que vous attendiez\ntous avec impatience!\pLe MAITRE DE LA FORME de POIVRESSEL\nva créer l'évènement au MARCHE!\pIl a promis de vendre le CALCIUM et\nla PROTEINE à des prix imbattables!\pLe voyage à POIVRESSEL vaut le détour.\nPourquoi ne pas aller acheter tout\lce que vous voulez?\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextSlateport_Ending::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pEt voici la nouvelle que vous attendiez\ntous avec impatience!\pLe MAITRE DE LA FORME de POIVRESSEL\nva créer l'évènement au MARCHE!\pIl a promis de faire le CALCIUM et\nla PROTEINE à des prix imbattables!\pD'après le MAITRE DE LA FORME, il en\nresterait encore beaucoup en stock.\pAlors pourquoi ne pas se laisser tenter\npar de petites emplettes à POIVRESSEL?\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextGameCorner_Upcoming::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pÇa approche!\nC'est bientôt là!\pLa journée du CASINO est prévue pour\nles jours à venir: dans {STR_VAR_1} exactement!\pMême les moins chanceux vont\npouvoir gagner ce jour-là!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextGameCorner_Ongoing::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pC'est fait!\nÇa y est enfin!\pLa journée du CASINO est enfin\narrivée!\pAurez-vous de la chance aux MACHINES\nA SOUS et à la ROULETTE?\pÇa se passe à LAVANDIA.\nC'est là qu'il faut aller!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextGameCorner_Ending::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pC'est fait!\nÇa y est enfin!\pLa journée du CASINO est enfin\narrivée!\pAurez-vous de la chance aux MACHINES\nA SOUS et à la ROULETTE?\pLe temps est compté et presque écoulé.\nÇa se passe à LAVANDIA.\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextLilycove_Upcoming::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pNous venons de recevoir de bonnes\nnouvelles du CENTRE COMMERCIAL\lNENUCRIQUE.\pLes soldes du CENTRE COMMERCIAL\ndébutent dans quelques jours:\lexactement {STR_VAR_1}!\pCe truc ou ce machin que vous avez\ntoujours voulu pourrait être à vous!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextLilycove_Ongoing::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pVoici la nouvelle que vous attendiez\ntous avec impatience!\pC'est enfin le début des soldes au\nCENTRE COMMERCIAL NENUCRIQUE!\pTous les trucs et machins dont vous\navez toujours rêvé seront à vous…\pVous n'aurez que l'embarras du choix!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextLilycove_Ending::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pVoici la nouvelle que vous attendiez\ntous avec impatience!\pC'est enfin le début des soldes au\nCENTRE COMMERCIAL NENUCRIQUE!\pTous les trucs et machins dont vous\navez toujours rêvé…\pVous n'aurez que l'embarras du choix!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextBlendMaster_Upcoming::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pNous avons de grandes nouvelles\npour tous les amateurs de {POKEBLOCK}S.\pLe grand MAITRE MIXEUR sera à\nNENUCRIQUE dans quelques\ljours! {STR_VAR_1}, précisément!\pPour ce qui est de mixer des BAIES, il\nn'y a pas mieux que le MAITRE\lMIXEUR dans tout HOENN!\pCeux qui veulent faire des {POKEBLOCK}S\navec le MAITRE ou juste l'admirer\lsont invités à apporter leurs BAIES!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextBlendMaster_Ongoing::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pNous avons de grandes nouvelles\npour tous les amateurs de {POKEBLOCK}S.\pLe grand MAITRE MIXEUR est enfin\narrivé!\pLe MAITRE MIXEUR, virtuose du\nMIXEUR, se produit dans le HALL DE\lCONCOURS de NENUCRIQUE.\pCeux qui veulent faire des {POKEBLOCK}S\navec le MAITRE ou juste l'admirer\lsont invités à apporter leurs BAIES!\pC'était le scoop du BULLETIN POKéMON.$"

gPokeNewsTextBlendMaster_Ending::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pC'est incroyable! Un spectacle à vous\ncouper le souffle!\pLe MAITRE MIXEUR mérite bien sa\nréputation!\pLe MIXEUR tourne à une vitesse folle!\pMais plus pour longtemps, amis\ntéléspectateurs. Le MAITRE MIXEUR\lva bientôt quitter NENUCRIQUE.\pSi vous n'avez pas encore vu le MAITRE\nà l'œuvre, il n'est pas trop tard!\lVenez vite à NENUCRIQUE!\pC'était le scoop du BULLETIN POKéMON.$"
