gBirchDexRatingText_AreYouCurious::
	.string "PROF. SEKO: Ah, {PLAYER}{KUN}!\pTu veux que je te donne mon avis\nsur ton POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hum? Oh, tu n'as pas attrapé assez\nde POKéMON pour que ça en vaille\lla peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hum…\pTu as rencontré {STR_VAR_1} POKéMON\net tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Tu devrais aller plus souvent dans\nles herbes et mieux chercher\lles POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu as bien\ncompris ça. Mais désormais,\lça va devenir plus dur.$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent\nque dans des zones précises.\lSois tenace!$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il pourrait être un peu plus\nrempli, mais il ressemble déjà plus\là un POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Hé, il commence à être plutôt\npas mal. Continue sur ta lancée!$"

gBirchDexRatingText_LessThan60::
	.string "Est-ce que tu utilises des CANNES?\nIl y a beaucoup de POKéMON\ldans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Plutôt que juste attraper des\nPOKéMON, pourquoi ne pas aussi\lles faire évoluer?$"

gBirchDexRatingText_LessThan80::
	.string "Ce POKéDEX va être formidable.\nJ'en ai bien l'impression.$"

gBirchDexRatingText_LessThan90::
	.string "Tu as collecté tout ça…\nTu as un talent remarquable!$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le PARC SAFARI?\pJ'ai entendu dire que certains\nPOKéMON ne s'attrapent que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as atteint la barre des 100.\nC'est un POKéDEX impressionnant!$"

gBirchDexRatingText_LessThan120::
	.string "En utilisant ECLATE-ROC, tu peux\ntrouver des POKéMON.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais faire des échanges pour\nte procurer d'autres POKéMON.$"

gBirchDexRatingText_LessThan140::
	.string "Certains POKéMON évoluent quand\nils aiment vraiment leur DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu'il y avait\nautant d'espèces de POKéMON\là HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Il arrive que certains POKéMON\nsortent en grand nombre, telle une\lhorde sauvage.\pNe rate pas ce genre d'occasion!$"

gBirchDexRatingText_LessThan170::
	.string "On a une bonne représentation des\nPOKéMON de la région de HOENN\len regardant ton POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Je pourrais déjà te donner le titre\nde PROFESSEUR POKéMON!$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi bien rempli,\ntu passes en professionnel!$"

gBirchDexRatingText_LessThan200::
	.string "Tu es à deux doigts de compléter\nce POKéDEX. Je le vois!$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations!\nTon POKéDEX est complet!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hum…\nSur l'ensemble du territoire…\pTu as rencontré {STR_VAR_1} POKéMON\net tu as attrapé {STR_VAR_2} POKéMON…$"
