Questionnaire_Text_FillOut::
	.string "Il y a un questionnaire…\nVoulez-vous y répondre?$"

Questionnaire_Text_ThankYou::
	.string "Merci d'avoir pris le temps de\nrépondre à notre questionnaire.\pVos réponses nous permettront\nde mieux vous servir.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, bonjour!\nVous connaissez ces mots?\pDonc vous devez aussi\nconnaître le CADEAU MYST.\pA partir de maintenant, vous allez\nrecevoir des CADEAUX MYST.!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Après avoir sauvegardé, vous\naurez accès aux CADEAUX MYST.!$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, bonjour!\nVous connaissez ces mots?\pDonc vous devez aussi\nconnaître les EVENEMENTS MYSTERE.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Après avoir sauvegardé, vous\naurez accès aux EVENEMENTS MYSTERE.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Merci d'utiliser le système\nEVENEMENTS MYSTERE.\pVous devez être {PLAYER}.\nIl y a un ticket pour vous.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Il peut être utilisé au port de\nNENUCRIQUE.\pEssayez-le pour voir de quoi \nil s'agit.$"
