	.align 2
gText_ConfirmSave::
	.string "Voulez-vous sauvegarder la partie?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une partie sauvegardée.\nVoulez-vous la remplacer?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE EN COURS…\nN'ETEIGNEZ PAS LA CONSOLE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "Une partie différente est déjà\nsauvegardée.\pVoulez-vous la remplacer?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\pChanger la mémoire de sauvegarde.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE EN COURS…\nNE PAS ETEINDRE.$"
