SecretBase_Text_Trainer0Intro:
    .string "Tu as déjà créé une BASE SECRETE?\pJ'ai parcouru le monde avant de choisir\ncet endroit.\pPuisque tu es ici, qu'est-ce que tu\ndirais d'un petit combat?$"

SecretBase_Text_Trainer0AcceptBattle:
    .string "OK!\nC'est parti!$"

SecretBase_Text_Trainer0DeclineBattle:
    .string "Hein?\nOh, tu n'as pas le temps, maintenant…$"

SecretBase_Text_Trainer0Defeated::
    .string "Ouaaarg! Tu es trop balèze!\nHeu, ne parle de ma défaite à personne!$"

SecretBase_Text_Trainer0PostBattle:
    .string "Qu'est-ce que tu penses de ma BASE\nSECRETE? Reviens me voir demain.$"

SecretBase_Text_Trainer0PreChampion:
    .string "Tu as déjà créé une BASE SECRETE?\pJ'ai parcouru le monde avant de choisir\ncet endroit.\pTu peux y venir quand tu veux!$"

SecretBase_Text_Trainer5Intro:
    .string "Tu peux faire une BASE SECRETE dans de\nnombreux endroits.\pMais cet endroit est mon préféré.\nIl est cool, non?\pOh, ça te dirait, un petit combat?$"

SecretBase_Text_Trainer5AcceptBattle:
    .string "OK, c'est parti!$"

SecretBase_Text_Trainer5DeclineBattle:
    .string "Oh… Tu n'as pas le temps, maintenant?\nTant pis.$"

SecretBase_Text_Trainer5Defeated::
    .string "Humm… Une défaite…\nN'en parle à personne!\pMotus et bouche cousue!$"

SecretBase_Text_Trainer5PostBattle:
    .string "Si tu repasses dans le coin,\nj'espère que tu me rendras visite.$"

SecretBase_Text_Trainer5PreChampion:
    .string "Tu peux faire une BASE SECRETE dans de\nnombreux endroits.\pMais cet endroit est mon préféré.\nIl est cool, non?$"

SecretBase_Text_Trainer1Intro:
    .string "Cet endroit est très apprécié.\nIl est toujours occupé par quelqu'un.\pOh! Tu pensais occuper cet endroit\naussi?\pDans ce cas, si tu parviens à me battre,\nje te le laisserai.$"

SecretBase_Text_Trainer1AcceptBattle:
    .string "OK!\nJe vais défendre ma BASE SECRETE!$"

SecretBase_Text_Trainer1DeclineBattle:
    .string "Quoi? C'est vrai?\nCet endroit ne t'intéresse pas?$"

SecretBase_Text_Trainer1Defeated::
    .string "Je n'en peux plus!\nJe me rends!$"

SecretBase_Text_Trainer1PostBattle:
    .string "OK, quand je partirai d'ici, tu pourras\nprendre possession de l'endroit!$"

SecretBase_Text_Trainer1PreChampion:
    .string "Cet endroit est très apprécié.\nIl est toujours occupé par quelqu'un.\pJ'ai dû attendre longtemps avant d'y\nentrer. Finalement, j'ai réussi!$"

SecretBase_Text_Trainer6Intro:
    .string "Bienvenue dans mon LABO POKéMON.\pJ'étudie secrètement les méthodes de\ncombat.\pTu veux voir comme je suis forte?$"

SecretBase_Text_Trainer6AcceptBattle:
    .string "Je vais me donner à fond!$"

SecretBase_Text_Trainer6DeclineBattle:
    .string "Oh.\nTant pis. Ce sera pour une autre fois!$"

SecretBase_Text_Trainer6Defeated::
    .string "Hum… J'ai encore beaucoup à apprendre.\nJe vais continuer mes recherches.$"

SecretBase_Text_Trainer6PostBattle:
    .string "Merci d'avoir accepté ce combat.\nReviens me voir demain.$"

SecretBase_Text_Trainer6PreChampion:
    .string "Bienvenue dans mon LABO POKéMON.\pJ'étudie secrètement les méthodes de\ncombat.$"

SecretBase_Text_Trainer2Intro:
    .string "C'est sympa d'avoir un grand manoir,\nmais je préfère cet endroit.\pJe l'aime bien, car des gens de tous\nles horizons viennent me rendre visite.\pA part ça, que dirais-tu d'un combat?$"

SecretBase_Text_Trainer2AcceptBattle:
    .string "Excellent!$"

SecretBase_Text_Trainer2DeclineBattle:
    .string "Préviens-moi quand tu voudras!$"

SecretBase_Text_Trainer2Defeated::
    .string "Pfffou! Je suis épuisé!\nMais c'est toujours marrant, un combat!$"

SecretBase_Text_Trainer2PostBattle:
    .string "Quoi qu'il en soit, je dois aller acheter\ndes meubles et des décorations.\pJe veux que les gens se sentent\nbien dans ma BASE SECRETE.$"

SecretBase_Text_Trainer2PreChampion:
    .string "C'est sympa d'avoir un grand manoir,\nmais je préfère cet endroit.\pJe l'aime bien, car des gens de tous\nles horizons viennent me rendre visite.$"

SecretBase_Text_Trainer7Intro:
    .string "J'adore faire du shopping pour trouver\ndes meubles et des décorations.\pMais j'aime bien aussi élever\ndes POKéMON.\pTu as l'air sympa. Tu veux te battre\ncontre mes POKéMON et moi?$"

SecretBase_Text_Trainer7AcceptBattle:
    .string "Cool.\nOn commence?$"

SecretBase_Text_Trainer7DeclineBattle:
    .string "Oh.\nJe suis terriblement déçue…$"

SecretBase_Text_Trainer7Defeated::
    .string "J'abandonne…$"

SecretBase_Text_Trainer7PostBattle:
    .string "C'était super marrant! Je vais aller\nfaire du shopping maintenant.$"

SecretBase_Text_Trainer7PreChampion:
    .string "J'adore faire du shopping pour trouver\ndes meubles et des décorations.\pMais j'aime bien aussi élever\ndes POKéMON.$"

SecretBase_Text_Trainer3Intro:
    .string "Certaines personnes font leur BASE\nSECRETE dans des endroits bien cachés.\lEst-ce qu'ils veulent éviter de se\lfaire remarquer?\pBon, puisque tu m'as trouvé, qu'est-ce\nque tu dirais d'un combat?$"

SecretBase_Text_Trainer3AcceptBattle:
    .string "Je vais te donner du fil à retordre!$"

SecretBase_Text_Trainer3DeclineBattle:
    .string "Oh… Tu as sûrement fait beaucoup\nd'efforts pour trouver cet endroit.$"

SecretBase_Text_Trainer3Defeated::
    .string "Je me suis étalé…$"

SecretBase_Text_Trainer3PostBattle:
    .string "Où est ta BASE SECRETE?\nJe viendrai te rendre visite.$"

SecretBase_Text_Trainer3PreChampion:
    .string "Certaines personnes font leur BASE\nSECRETE dans des endroits bien cachés.\pEst-ce qu'ils veulent éviter de se\nfaire remarquer?$"

SecretBase_Text_Trainer8Intro:
    .string "On m'a dit qu'il y avait plusieurs façons\nd'obtenir des décorations.\pOn devrait faire un concours et voir\nqui aura les plus belles décorations!\pEn attendant, ça te tente un combat?$"

SecretBase_Text_Trainer8AcceptBattle:
    .string "Nous sommes dans ma BASE SECRETE.\nJe ne peux pas perdre!$"

SecretBase_Text_Trainer8DeclineBattle:
    .string "Quand tu voudras, alors!$"

SecretBase_Text_Trainer8Defeated::
    .string "Quoi?\nJ'ai perdu, là?$"

SecretBase_Text_Trainer8PostBattle:
    .string "Je me rattraperai sur les décorations.\nReviens me faire un petit coucou!$"

SecretBase_Text_Trainer8PreChampion:
    .string "On m'a dit qu'il y avait plusieurs façons\nd'obtenir des décorations.\pOn devrait faire un concours et voir\nqui aura les plus belles décorations!$"

SecretBase_Text_Trainer4Intro:
    .string "J'ai trouvé un endroit qui me plaisait et\nje l'ai décoré avec mes objets préférés.\pEn plus, j'élève mon POKéMON préféré.\nGrâce à lui, je suis plus fort.\pC'est mon passe-temps préféré.\nTu veux te battre contre moi?$"

SecretBase_Text_Trainer4AcceptBattle:
    .string "Montre-moi de quoi tu es capable!$"

SecretBase_Text_Trainer4DeclineBattle:
    .string "Je suppose que tu n'as pas toujours\nenvie de te battre.$"

SecretBase_Text_Trainer4Defeated::
    .string "OK, je sais de quoi tu es capable.\nPas la peine d'insister!$"

SecretBase_Text_Trainer4PostBattle:
    .string "On pourrait tous les deux devenir plus\nforts. Continuons à nous entraîner!$"

SecretBase_Text_Trainer4PreChampion:
    .string "J'ai trouvé un endroit qui me plaisait et\nje l'ai décoré avec mes objets préférés.\pEn plus, j'élève mon POKéMON préféré.\nGrâce à lui, je suis plus fort.\pChaque jour est une aventure.$"

SecretBase_Text_Trainer9Intro:
    .string "Tu peux en apprendre beaucoup sur les\ngoûts des autres en regardant leurs\ldécorations et la façon dont elles\lsont disposées.\pQu'est-ce que tu penses de mes goûts?\nTu restes sans voix, hein?\pTu veux connaître mes goûts\nen matière de combat?$"

SecretBase_Text_Trainer9AcceptBattle:
    .string "Il est trop tard pour reculer\nmaintenant!$"

SecretBase_Text_Trainer9DeclineBattle:
    .string "Je peux te faire une démonstration\nde mon style quand tu veux.$"

SecretBase_Text_Trainer9Defeated::
    .string "Quel talent formidable!\nTon pouvoir semble sans limites…$"

SecretBase_Text_Trainer9PostBattle:
    .string "Alors, qu'est-ce que tu as pensé de\nmon style? Je vais encore le peaufiner!$"

SecretBase_Text_Trainer9PreChampion:
    .string "Tu peux en apprendre beaucoup sur les\ngoûts des autres en regardant leurs\ldécorations et la façon dont elles\lsont disposées.\pQu'est-ce que tu penses de mes goûts?\nTu restes sans voix, hein?$"
