ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tu as prévu d'aller loin?\pEt si tu m'apportais des SELS TREFONDS\net des CO. TREFONDS?\pJe peux te préparer quelque chose\nde bon si tu m'apportes ce qu'il faut.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si tu m'apportais quatre SELS TREFONDS\net quatre CO. TREFONDS, je pourrais te\lfaire un GRELOT COQUE.\pTu peux te procurer ces ingrédients\ntous les jours.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hé! Des SELS TREFONDS et des \nCO. TREFONDS! Et suffisamment!\pTu veux que je les utilise\npour faire un GRELOT COQUE?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Bon, d'accord! Je te fais un\nGRELOT COQUE sur-le-champ.\p… … … … … … … …\n… … … … … … … …\pVoilà! C'est prêt!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Gardes-en pour un POKéMON.\nIl va adorer ça, c'est sûr!\pQuoi, le carillon du GRELOT COQUE…\nSublime!\pTu peux avoir ses ingrédients tous les\njours. Alors je peux t'en faire d'autres.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Dans ce cas…\nJe voulais faire un GRELOT COQUE…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Tu n'as pas assez de place dans ton SAC\npour recevoir ça.\pTu devrais faire de la place et\nrevenir pour avoir un GRELOT COQUE.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Il y avait du SEL TREFONDS ici.\nMais il n'y a plus rien.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Il y avait un CO. TREFONDS ici.\nMais il n'y a plus rien.$"
