Route102_Text_CalvinIntro:
	.string "Si tu as un POKéMON avec toi, alors\ntu es officiellement un DRESSEUR\lde POKéMON!\pTu ne peux pas refuser mon défi!$"

Route102_Text_CalvinDefeated:
	.string "Grrrr, j'ai perdu… J'aurais dû davantage\nentraîner mon POKéMON…$"

Route102_Text_CalvinPostBattle:
	.string "Ecoute, toi. T'aurais pu me le dire\navant, que tu avais un tel niveau!$"

Route102_Text_CalvinRegister:
	.string "Je me suis beaucoup entraîné depuis\nnotre dernière rencontre.\pJ'aimerais t'affronter de nouveau,\ntu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "J'aimerais t'affronter de nouveau,\ntu m'enregistres dans ton POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Depuis que j'ai perdu contre toi, je n'ai\npas cessé de m'entraîner.\pTu ne peux pas refuser mon défi!$"

Route102_Text_CalvinRematchDefeated:
	.string "Grrrr, j'ai perdu…\nMon entraînement est-il mauvais?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tu t'améliores, je m'améliorerai aussi.$"

Route102_Text_AllenIntro:
	.string "Tu viens juste de devenir DRESSEUR?\nOn est tous les deux des débutants!$"

Route102_Text_AllenDefeated:
	.string "Je voulais me mesurer à toi parce que\nje pensais pouvoir te battre…$"

Route102_Text_AllenPostBattle:
	.string "Je n'ai même pas gagné une seule fois…\nJ'espère que je vais bientôt y arriver…$"

Route102_Text_RickIntro:
	.string "Ah, ah! Nos regards se sont croisés!\nBats-toi contre mes POKéMON INSECTE!$"

Route102_Text_RickDefeated:
	.string "Hou! Je suis hors d'état de combattre!$"

Route102_Text_RickPostBattle:
	.string "Si tu fixes ton regard sur un DRESSEUR,\ntu dois l'affronter! C'est la règle!$"

Route102_Text_TianaIntro:
	.string "Je vais continuer à gagner pour\ndevenir le meilleur DRESSEUR.\pFais-moi avancer dans ma carrière!$"

Route102_Text_TianaDefeated:
	.string "En fait, c'est moi qui contribue à faire\navancer ta carrière…$"

Route102_Text_TianaPostBattle:
	.string "Pour prendre le chemin de la victoire,\nje vais devoir attraper plus de\lPOKéMON.$"

Route103_Text_DaisyIntro:
	.string "Ne sens-tu pas le parfum de la défaite?$"

Route103_Text_DaisyDefeated:
	.string "Tu n'as pas laissé notre parfum\nte distraire…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromathérapie utilise les parfums\npour soigner des troubles psychiques.$"

Route103_Text_AmyIntro:
	.string "EVE: Je suis EVE.\nEt voici ma petite sœur, AWA.\pOn combat ensemble!$"

Route103_Text_AmyDefeated:
	.string "EVE: Oooh, on a perdu.$"

Route103_Text_AmyPostBattle:
	.string "EVE: Il faut penser à tout un tas\nde choses quand tu te bats contre deux\lDRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "EVE: Oh, tu n'as qu'un seul POKéMON\navec toi.\lTu ne vas pas pouvoir nous affronter.$"

Route103_Text_LivIntro:
	.string "AWA: On se bat ensemble, comme une\néquipe.$"

Route103_Text_LivDefeated:
	.string "AWA: Oh, on a perdu, grande sœur…$"

Route103_Text_LivPostBattle:
	.string "AWA: On fonctionne très bien\nensemble, ma grande sœur et moi…\pMais on a quand même perdu…$"

Route103_Text_AmyLivRegister:
	.string "AWA: Nous sommes bien meilleures…\nC'est vrai, on te montrera une\lprochaine fois!$"

Route103_Text_LivNotEnoughPokemon:
	.string "AWA: Si tu veux te battre contre\nnous, il faut que tu aies deux POKéMON!\lSinon, ce ne serait pas juste!$"

Route103_Text_AmyRematchIntro:
	.string "EVE: Je suis EVE.\nEt voici ma petite sœur, AWA.\pOn combat ensemble!$"

Route103_Text_AmyRematchDefeated:
	.string "EVE: Ah, bouhou!\nOn n'a toujours pas réussi à gagner…$"

Route103_Text_AmyRematchPostBattle:
	.string "EVE: Il faut penser à tout un tas\nde choses quand tu te bats contre deux\lDRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "EVE: Oh, tu n'as qu'un seul POKéMON\navec toi.\lTu ne vas pas pouvoir nous affronter.$"

Route103_Text_LivRematchIntro:
	.string "AWA: On se bat ensemble, comme une\néquipe.$"

Route103_Text_LivRematchDefeated:
	.string "AWA: Arrrg, on a encore perdu…\nGrande sœur…$"

Route103_Text_LivRematchPostBattle:
	.string "AWA: On fonctionne très bien\nensemble, ma grande sœur et moi…\pMais pourquoi a-t-on encore perdu?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "AWA: Si tu veux te battre contre\nnous, il faut que tu aies deux POKéMON!\lSinon, ce ne serait pas juste!$"

Route103_Text_AndrewIntro:
	.string "Arrg! Ma ligne est emmêlée!\nÇa m'énerve et ça me rend agressif!\pAllez! Viens te battre!$"

Route103_Text_AndrewDefeated:
	.string "Ah! Perdu!\nJe suis encore plus énervé maintenant!$"

Route103_Text_AndrewPostBattle:
	.string "Ah, je vais devenir fou…\nGrrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mon POKéMON est tellement adorable!\nNe sois pas timide. J'te l'montre!$"

Route103_Text_MiguelDefeated:
	.string "Oh, ça alors!\nMon POKéMON chéri!$"

Route103_Text_MiguelPostBattle:
	.string "Mon POKéMON chéri est à croquer,\nmême quand il est K.O.!$"

Route103_Text_MiguelRegister:
	.string "Il faudra que tu viennes pour voir mes\nadorables POKéMON!$"

Route103_Text_MiguelRematchIntro:
	.string "Salut, toi! Mon adorable POKéMON est\nvraiment à croquer. De plus en plus!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\nMon POKéMON chéri!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Plus je passe de temps avec mon\nPOKéMON et plus il est adorable.$"

Route103_Text_PeteIntro:
	.string "Pour une si petite distance…\nRien de mieux que la nage…$"

Route103_Text_PeteDefeated:
	.string "Bloub!$"

Route103_Text_PetePostBattle:
	.string "Oh, je comprends d'où tu viens\nmaintenant.\pSi j'avais un POKéMON en qui je puisse\navoir confiance, je l'utiliserais aussi\lavec SURF.$"

Route103_Text_IsabelleIntro:
	.string "Regarde où tu vas! On a failli se rentrer\ndedans!$"

Route103_Text_IsabelleDefeated:
	.string "Méeuh…$"

Route103_Text_IsabellePostBattle:
	.string "Je ne suis pas très bonne, alors je\nm'entraîne à la nage…\pDésolée, j'ai failli te rentrer dedans.$"

Route103_Text_RhettIntro:
	.string "On est un peu à l'étroit ici.$"

Route103_Text_RhettDefeated:
	.string "Tu te débrouilles bien pour ton âge!$"

Route103_Text_RhettPostBattle:
	.string "Tu aimes bien les petits endroits\ncomme ça?$"

Route103_Text_MarcosIntro:
	.string "Je vais t'électriser avec mon\nsolo de guitare!$"

Route103_Text_MarcosDefeated:
	.string "Ma carrière est fichue!$"

Route103_Text_MarcosPostBattle:
	.string "Je jouais de la guitare un peu à l'écart\net soudain, je me suis retrouvé entouré\lde fans.\pHé, peut-être que je devrais faire\ncarrière!$"

Route104_Text_GinaIntro:
	.string "GINA: D'accord, on n'a qu'à se battre\navec nos POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Ça m'embête de perdre!$"

Route104_Text_GinaPostBattle:
	.string "GINA: On n'a pas le niveau!\nIl va falloir qu'on s'entraîne bien plus!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Un seul POKéMON?\nAlors on ne se bat pas contre toi.\pAvec un seul POKéMON, ça va pas \nl'faire. C'est pas cool.$"

Route104_Text_MiaIntro:
	.string "MIA: On est jumelles, alors on\ncombat ensemble.$"

Route104_Text_MiaDefeat:
	.string "MIA: On s'est battues ensemble et\non a perdu toutes les deux…$"

Route104_Text_MiaPostBattle:
	.string "MIA: On va davantage entraîner nos\nPOKéMON pour être aussi fortes que toi.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Tu veux te mesurer à nous?\pOn te dira non et non, si tu n'as pas\ndeux POKéMON avec toi.\pOn est trop fortes pour toi!$"

Route104_Text_IvanIntro:
	.string "Pourquoi en faire un secret?\nJe suis l'expert en POKéMON EAU!\pHum?\nTu ne me connais pas?$"

Route104_Text_IvanDefeat:
	.string "Je pensais ne pas être trop mauvais,\nmais je suppose que si… Fffff…$"

Route104_Text_IvanPostBattle:
	.string "J'étais si occupé à pêcher que j'en ai \noublié de dresser mes POKéMON.$"

Route104_Text_BillyIntro:
	.string "C'est trop cool de laisser des traces\nde pas sur le sable!$"

Route104_Text_BillyDefeat:
	.string "Waah! J'ai du sable dans mes\nchaussures! Elles sont dégoûtantes!$"

Route104_Text_BillyPostBattle:
	.string "Je veux laisser les traces de mes pas\npartout sur le sable, mais elles\ldisparaissent aussitôt…$"

Route104_Text_HaleyIntro:
	.string "Je devrais peut-être…\nOu peut-être pas…\pOui, c'est décidé, je me bats!$"

Route104_Text_HaleyDefeat:
	.string "Je n'aurais pas dû me battre…$"

Route104_Text_HaleyPostBattle:
	.string "Si tu dois prendre une décision et que\ntu laisses quelqu'un d'autre la prendre\là ta place, tu le regretteras de toute\lfaçon, quoi qu'il arrive.$"

Route104_Text_HaleyRegister1:
	.string "Tu sais te battre, mais est-ce que\nje devrais t'inscrire dans mon POKéNAV?\pJe suis pas trop sûre…\pJe plaisante! Bien sûr que je vais\nt'enregistrer!$"

Route104_Text_HaleyRegister2:
	.string "Tu sais te battre, mais est-ce que\nje devrais t'inscrire dans mon POKéNAV?\pJe suis pas trop sûre…\pJe plaisante! Bien sûr que je vais\nt'enregistrer!$"

Route104_Text_HaleyRematchIntro:
	.string "Viens te battre!$"

Route104_Text_HaleyRematchDefeat:
	.string "Oooh…\nJe pensais pouvoir gagner…$"

Route104_Text_HaleyPostRematch:
	.string "J'ai fait le choix de me battre, alors je\ndois accepter la défaite avec élégance.\pJe suis quand même triste d'avoir perdu.$"

Route104_Text_WinstonIntro:
	.string "Oh, oui, je relève le défi.\nJ'ai beaucoup d'argent.$"

Route104_Text_WinstonDefeat:
	.string "Pourquoi n'ai-je pas réussi à gagner?$"

Route104_Text_WinstonPostBattle:
	.string "S'il y a bien une chose que l'argent ne\npeut acheter, ce sont les POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hmm?\nTu as obtenu un POKéNAV.\pTu veux de l'argent pour que je puisse\nt'enregistrer dans mon POKéNAV?$"

Route104_Text_WinstonRegister2:
	.string "Hmm?\nTu as obtenu un POKéNAV.\pTu veux de l'argent pour que je puisse\nt'enregistrer dans mon POKéNAV?$"

Route104_Text_WinstonRematchIntro:
	.string "Après ma défaite contre toi, j'ai appris\nun tas de choses sur les POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "J'ai encore perdu?\nPourquoi je n'ai pas réussi à gagner?$"

Route104_Text_WinstonPostRematch:
	.string "Je suis riche et cependant, je ne semble\npas pouvoir gagner avec les POKéMON…\pLe monde des POKéMON est mystérieux…$"

Route104_Text_CindyIntro:
	.string "Le destin nous a fait nous rencontrer.\nAccepterais-tu un petit combat?$"

Route104_Text_CindyDefeat:
	.string "Oh, ça alors!$"

Route104_Text_CindyPostBattle:
	.string "«Bonjour» est le début\nd'«au revoir».\pJ'espère qu'on se reverra.$"

Route104_Text_CindyRegister1:
	.string "Salut, contente de te revoir.\pC'est le destin qui nous fait nous\nrencontrer de nouveau. On devrait\ls'enregistrer dans nos POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "On devrait fêter ces retrouvailles!\pEnregistrons nos numéros dans\nnos POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Salut! Comme on se retrouve!\nQue dirais-tu d'un petit combat?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, non…\nJ'ai fait du mieux que j'pouvais…$"

Route104_Text_CindyPostRematch:
	.string "«Bonjour» est le début\nd'«au revoir».\pJ'espère qu'on se reverra.$"

Route104_Text_DarianIntro:
	.string "J'ai attrapé ce POKéMON qui a\nl'air super fort!\pIl y a un je ne sais quoi de magique\nchez lui!\pJe suis sûr qu'il est très fort, ouaip!$"

Route104_Text_DarianDefeat:
	.string "Que…$"

Route104_Text_DarianPostBattle:
	.string "Hé, MAGICARPE, on ne peut pas vraiment\ndire que tu mérites ton nom!$"

Route105_Text_FosterIntro:
	.string "On raconte qu'il y a une pierre\nmystérieuse par ici.\lTu sais quelque chose là-dessus?$"

Route105_Text_FosterDefeated:
	.string "J'étais si préoccupé par cette pierre\nque mes POKéMON sont restés faibles…$"

Route105_Text_FosterPostBattle:
	.string "Je peux rester des heures à contempler\nune belle pierre sans m'en lasser.$"

Route105_Text_LuisIntro:
	.string "Ouf! En te voyant, j'ai eu peur que ce\nsoit un enfant en train de se noyer.\pMais ça a l'air d'aller, alors que\ndirais-tu de te battre?$"

Route105_Text_LuisDefeated:
	.string "Glou… Glou…$"

Route105_Text_LuisPostBattle:
	.string "Si tu es en train de te noyer, il faut\nagiter un bras pour le signaler.$"

Route105_Text_DominikIntro:
	.string "Nager dans la mer d'un bleu intense…\nC'est formidable!$"

Route105_Text_DominikDefeated:
	.string "J'ai perdu…\nMaintenant, je broie du noir…$"

Route105_Text_DominikPostBattle:
	.string "Pourquoi la mer est-elle bleue?\pJe l'ai appris au MUSEE de POIVRESSEL,\nmais j'ai oublié.$"

Route105_Text_BeverlyIntro:
	.string "Mon corps semble plus léger dans l'eau.\nC'est comme si j'avais maigri!$"

Route105_Text_BeverlyDefeated:
	.string "Je flotte…$"

Route105_Text_PostBattle:
	.string "Le poids de ton corps n'est réduit que\nd'un dixième dans l'eau.\pJe ferais donc…\nHé! J'vais pas te dire combien je pèse!$"

Route105_Text_ImaniIntro:
	.string "Le bleu du ciel…\nL'étendue de la mer…\lC'est tellement paisible…$"

Route105_Text_ImaniDefeated:
	.string "J'ai perdu car je me suis laissée aller!$"

Route105_Text_ImaniPostBattle:
	.string "Je veux qu'on trouve ça apaisant d'être\navec moi. Hi, hi, hi…$"

Route105_Text_AndresIntro:
	.string "Je suis convaincu que la mer nous\ncache de nombreux secrets.$"

Route105_Text_AndresDefeated:
	.string "Oui…\nJe ne suis pas très bon au combat…$"

Route105_Text_AndresPostBattle:
	.string "Il y a sûrement plein de secrets à\ndécouvrir au fond des océans.\pJe veux tous les trouver!$"

Route105_Text_AndresRegister:
	.string "Heu? Tu veux quand même m'enregistrer\ndans ton POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Je t'ai déjà dit que je n'étais pas\ntrès fort…\pMais si tu insistes…$"

Route105_Text_AndresRematchDefeated:
	.string "Oui…\nJe m'en doutais un peu…$"

Route105_Text_AndresRematchPostBattle:
	.string "Je ne me bats peut-être pas très bien,\nmais personne ne m'arrive à la cheville\lquand il s'agit d'exploration.\pJe vais parcourir les océans à travers\nle monde!$"

Route105_Text_JosueIntro:
	.string "Nager, ça m'a épuisé.\nJ'suis pas vraiment habitué.\pUn petit combat pour changer?$"

Route105_Text_JosueDefeated:
	.string "J'ai perdu parce qu'on était près\nde l'eau.$"

Route105_Text_JosuePostBattle:
	.string "Dans le ciel, je me sens plus à \nl'aise que dans l'eau!$"

Route106_Text_ElliotIntro:
	.string "Que préfères-tu: pêcher en mer ou\nen rivière?$"

Route106_Text_ElliotDefeated:
	.string "Comme à la pêche en mer, j'ai perdu\nde façon spectaculaire!$"

Route106_Text_ElliotPostBattle:
	.string "La pêche, c'est ce qu'il y a de mieux, peu\nimporte que ce soit en mer ou en rivière.\lT'es d'accord avec moi?$"

Route106_Text_ElliotRegister:
	.string "C'est cool la pêche, un peu comme les\ncombats quoi!\pIl faudrait qu'on remette ça un jour.$"

Route106_Text_ElliotRematchIntro:
	.string "En pêchant, j'ai attrapé un paquet de \nPOKéMON. Le combat va être terrible!$"

Route106_Text_ElliotRematchDefeated:
	.string "J'ai encore perdu de façon prodigieuse!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gagner ou perdre… De toute façon, les\nPOKéMON, y a rien de mieux!$"

Route106_Text_NedIntro:
	.string "Que font les gens s'ils ont envie d'aller\naux toilettes?\pJ'fais quoi si j'ai une touche quand je\nsuis aux toilettes? Je suis obligé de\lrester là…$"

Route106_Text_NedDefeated:
	.string "J'ai perdu parce que j'essaie\nde me retenir…$"

Route106_Text_NedPostBattle:
	.string "Oh, non! Je croyais que j'allais avoir\nune grosse prise!$"

Route106_Text_DouglasIntro:
	.string "Ah, ah, ah! Je suis un mauvais coureur\nmais dans l'eau, on ne m'attrape pas!$"

Route106_Text_DouglasDefeated:
	.string "J'abandonne!$"

Route106_Text_DouglasPostBattle:
	.string "Je ne perdrai pas une course à la nage…$"

Route106_Text_KylaIntro:
	.string "La mer est mon repaire. Même si tu\nes jeune, je n'vais pas te\lfaciliter la tâche!$"

Route106_Text_KylaDefeated:
	.string "Est-ce que par hasard, tu as trouvé\nça trop facile?$"

Route106_Text_KylaPostBattle:
	.string "Se laisser aller au gré des vagues…\nJ'adore ça! Pourquoi tu n'essaierais\lpas?$"

Route107_Text_DarrinIntro:
	.string "Ouhaaaa…\pJe me suis endormi en me laissant\nporter par les vagues.$"

Route107_Text_DarrinDefeated:
	.string "Ah, ah, j'ai perdu…\nJ'vais faire une p'tite sieste…$"

Route107_Text_DarrinPostBattle:
	.string "Flotter et se laisser bercer par les\nvagues, c'est comme dormir dans\lun bon lit bien douillet.$"

Route107_Text_TonyIntro:
	.string "La mer est comme ma seconde maison.\nBattons-nous!$"

Route107_Text_TonyDefeated:
	.string "J'ai perdu sur mon territoire…\nQuel choc!$"

Route107_Text_TonyPostBattle:
	.string "Je traverse les mers à la nage, le cœur\nrempli de rêves…\pC'est une chanson!\nDe toute façon, je nage encore un peu.$"

Route107_Text_TonyRegister:
	.string "J'en suis tout retourné!\nComme ça, tu te souviendras de moi!$"

Route107_Text_TonyRematchIntro:
	.string "A nager dans cette large et vaste mer,\nmon POKéMON est devenu plus fort.$"

Route107_Text_TonyRematchDefeated:
	.string "Quel choc!\pMon POKéMON est devenu plus fort,\nmais je suis resté faible…$"

Route107_Text_TonyRematchPostBattle:
	.string "Ce que tu apprends au combat te rend\nplus fort en tant que DRESSEUR.\pLes vagues m'ont appris ça.$"

Route107_Text_DeniseIntro:
	.string "Tu connais une petite ville appelée\nMYOKARA?$"

Route107_Text_DeniseDefeated:
	.string "Je déteste ça!$"

Route107_Text_DenisePostBattle:
	.string "Un curieux proverbe est en train de\ndevenir à la mode au CENTRE\lCULTUREL DE MYOKARA.$"

Route107_Text_BethIntro:
	.string "Tu voulais te battre contre moi?\nOui, c'est OK pour moi!$"

Route107_Text_BethDefeated:
	.string "Je n'étais pas assez forte pour toi.$"

Route107_Text_BethPostBattle:
	.string "Je crois que les choses iront de mieux\nen mieux pour toi. Je me lance aussi!$"

Route107_Text_LisaIntro:
	.string "LISA: Accepte le défi d'un frère\net d'une sœur!$"

Route107_Text_LisaDefeated:
	.string "LISA: Impressionnant!\nTu as un niveau bien plus élevé.$"

Route107_Text_LisaPostBattle:
	.string "LISA: As-tu des amis qui aimeraient\naller à la plage avec toi?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Si tu veux nous affronter,\napporte plus de POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Avec ma sœur, on est toujours\nen train de faire des combats POKéMON.\pJe perds toujours, mais on peut te\nbattre en 2 contre 2!$"

Route107_Text_RayDefeated:
	.string "RAY: Waouh, tu as un meilleur niveau\nque nous!$"

Route107_Text_RayPostBattle:
	.string "RAY: C'est ma sœur qui m'a donné\nmon POKéMON. Je l'ai élevé et\lmaintenant, c'est mon meilleur allié!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Si tu veux nous affronter,\nramène d'autres POKéMON!$"

Route107_Text_CamronIntro:
	.string "Je suis en plein triathlon, mais je\nn'ai rien contre un petit match!$"

Route107_Text_CamronDefeated:
	.string "J'en peux plus…$"

Route107_Text_CamronPostBattle:
	.string "Il me reste encore les épreuves de\nvélo et de course après ça.\pJe ne tiendrai jamais…$"

Route108_Text_JeromeIntro:
	.string "Mon rêve est de parcourir les sept mers\ndu monde à la nage!$"

Route108_Text_JeromeDefeated:
	.string "C'est pas comme ça que j'vais pouvoir\nparcourir les sept mers à la nage…$"

Route108_Text_JeromePostBattle:
	.string "Jouer avec les POKéMON marins, c'est\nl'un des plaisirs de la nage!$"

Route108_Text_MatthewIntro:
	.string "Eho, toi là-bas! Tu vas aussi à l'EPAVE?$"

Route108_Text_MatthewDefeated:
	.string "Je me noie!\nGlou… Glou…$"

Route108_Text_MatthewPostBattle:
	.string "Certaines personnes sont même allées\nà l'intérieur de cette EPAVE.$"

Route108_Text_TaraIntro:
	.string "Mon menteur de petit ami m'a dit que\nj'étais très jolie en bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, bouh!$"

Route108_Text_TaraPostBattle:
	.string "Même si ce n'est pas vrai, j'aime bien\nqu'on me dise que je suis jolie…\pAh, nous les filles…$"

Route108_Text_MissyIntro:
	.string "J'adore la mer!\nJ'oublie tous mes soucis quand je nage.$"

Route108_Text_MissyDefeated:
	.string "Quand je perds un combat,\nça me stresse!$"

Route108_Text_MissyPostBattle:
	.string "Nager pour évacuer son stress!\nC'est tellement sain!$"

Route108_Text_CoryIntro:
	.string "J'adore les POKéMON de type EAU.\nLes autres aussi d'ailleurs!$"

Route108_Text_CoryDefeated:
	.string "Aaaaah! J'ai perdu!\nNoooon!$"

Route108_Text_CoryPostBattle:
	.string "Crie un coup quand ça va pas!\nÇa soulage!$"

Route108_Text_CoryRegister:
	.string "J'adore les DRESSEURS difficiles!\nEnregistre-moi dans ton POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Gagner ou perdre, peu importe tant\nque je me bats sur l'eau!$"

Route108_Text_CoryRematchDefeated:
	.string "Aaaaaaaah! J'ai encore perdu!\nNooooooon!$"

Route108_Text_CoryRematchPostBattle:
	.string "Si tu cherches un challenge,\nessaie de crier en mer!$"

Route108_Text_CarolinaIntro:
	.string "Je suis très fière de mes POKéMON.\nLaisse-moi un peu te montrer!$"

Route108_Text_CarolinaDefeated:
	.string "C'était vraiment pas sympa de ta part!$"

Route108_Text_CarolinaPostBattle:
	.string "Comme je suis à la mer, je n'ai rien\ncontre l'idée de mettre un petit\lmaillot de bain rose…$"

Route109_Text_DavidIntro:
	.string "Hé, hé! Regarde un peu mes abdos!\nOn appelle ça «être bien bâti»!$"

Route109_Text_DavidDefeated:
	.string "Oh, oh!\nA côté d'la plaque!$"

Route109_Text_DavidPostBattle:
	.string "Hé, hé!\pMes abdos bien sculptés n'ont rien à\nvoir avec les combats de POKéMON!$"

Route109_Text_AliceIntro:
	.string "Tu as une bonne protection contre le\nsoleil?$"

Route109_Text_AliceDefeated:
	.string "Ouille, ouille, ouille!$"

Route109_Text_AlicePostBattle:
	.string "Ce sont les joues qui sont les plus\nexposées aux coups de soleil.$"

Route109_Text_HueyIntro:
	.string "J'ai jeté l'ancre dans tous les ports du\nmonde, mais c'est POIVRESSEL\lque je préfère.$"

Route109_Text_HueyDefeated:
	.string "Y a pas meilleur que toi!$"

Route109_Text_HueyPostBattle:
	.string "Dans le plus beau port se trouve donc\nle plus fort des DRESSEURS…$"

Route109_Text_EdmondIntro:
	.string "Aaaaaaaaaah…\nTe battre? Contre moi?$"

Route109_Text_EdmondDefeated:
	.string "Aah… Oooooooohhhhh…\nAaaaaaaaaah…$"

Route109_Text_EdmondPostBattle:
	.string "D'habitude, je suis meilleur que ça!\nJe suis juste malade comme un chien!\pJe suis MARIN, mais j'ai le mal de mer…$"

Route109_Text_RickyIntro:
	.string "J'ai si soif… Je pourrais aller prendre\nun SODA COOL à la MAISON DU BORD DE MER.$"

Route109_Text_RickyDefeated:
	.string "Grrrrrr…$"

Route109_Text_RickyPostBattle:
	.string "Je suis affamé… Ma bouée\nressemble à un beignet géant…$"

Route109_Text_RickyRegister:
	.string "On se battra encore?\nDès que je n'aurai plus soif, OK?$"

Route109_Text_RickyRematchIntro:
	.string "Je suis affamé, mais j'ai encore assez\nde forces en moi pour combattre!$"

Route109_Text_RickyRematchDefeated:
	.string "J'ai perdu…\nC'est parce que je suis affamé…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quand on mange sur la plage,\ntout semble meilleur.$"

Route109_Text_LolaIntro:
	.string "Ne trouves-tu pas qu'un parasol\nressemble à une fleur géante?$"

Route109_Text_LolaDefeated:
	.string "Maman!$"

Route109_Text_LolaPostBattle:
	.string "La plage vue du ciel ressemble à un\ngrand jardin de fleurs!$"

Route109_Text_LolaRegister:
	.string "Moi?\nJe suis là tous les jours!$"

Route109_Text_LolaRematchIntro:
	.string "Je n'vais pas encore perdre contre toi!\nC'est pour ça que j'ai ma bouée!$"

Route109_Text_LolaRematchDefeated:
	.string "Maman!$"

Route109_Text_LolaRematchPostBattle:
	.string "Avec une bouée, la grâce de mes POKéMON\nva augmenter, et la mienne aussi!$"

Route109_Text_AustinaIntro:
	.string "Je ne peux pas nager sans ma bouée,\nmais je ne perdrai pas aux POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "C'est parce que j'avais une bouée que\nj'ai perdu?$"

Route109_Text_AustinaPostBattle:
	.string "Ma bouée est un accessoire de mode.\nJe ne sors jamais sans elle.$"

Route109_Text_GwenIntro:
	.string "Salut, grand DRESSEUR.\nTu veux te battre contre moi?$"

Route109_Text_GwenDefeated:
	.string "Oh, quelle puissance!$"

Route109_Text_GwenPostBattle:
	.string "Comment as-tu atteint un tel niveau?$"

Route109_Text_CarterIntro:
	.string "Waaouh! Qu'est-ce que tu vas t'prendre!$"

Route109_Text_CarterDefeated:
	.string "J'ai perdu…$"

Route109_Text_CarterPostBattle:
	.string "Je pense que tu es remarquable.\nNon, que tu vas devenir remarquable!$"

Route109_Text_PaulIntro:
	.string "PAUL: Eh bien, on peut dire que tu\nsais casser l'ambiance.\pTu ne souhaiterais pas gâcher notre\nprécieux temps ensemble, par hasard?$"

Route109_Text_PaulDefeated:
	.string "PAUL: Bon, j'abandonne.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Ne dis à personne qu'on est là.\nC'est juste notre monde secret à tous\lles deux!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: On s'aime profondément.\nC'est pour ça qu'on fait combattre nos\lPOKéMON ensemble.$"

Route109_Text_MelIntro:
	.string "MEL: On est follement amoureux.\nNotre amour enflamme tout HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: On a perdu et c'est ma faute!\nPAUL va me détester!$"

Route109_Text_MelPostBattle:
	.string "MEL: Euh, PAUL, tu m'en veux?\nNe te fâche pas, je t'en prie.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: On s'aime profondément.\nC'est pour ça qu'on fait combattre nos\lPOKéMON ensemble.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaah! Tu vois?\nMa bouée est toute ronde!$"

Route109_Text_ChandlerDefeated:
	.string "Oh oh!\nC'est trop dommage!$"

Route109_Text_ChandlerPostBattle:
	.string "Et tout ça après que je t'ai montré\nma bouée…$"

Route109_Text_HaileyIntro:
	.string "Je ne sais pas nager, alors je fais\njuste semblant.$"

Route109_Text_HaileyDefeated:
	.string "C'est bien ce que je pensais!\nJe ne pouvais pas gagner!$"

Route109_Text_HaileyPostBattle:
	.string "Quand je me suis mise à la natation,\nje pensais que mes POKéMON\ldeviendraient plus forts.$"

Route109_Text_ElijahIntro:
	.string "Pour un macho comme moi, cette\ncombinaison de POKéMON est\lla paire idéale.$"

Route109_Text_ElijahDefeated:
	.string "Je reste cool même dans la défaite.$"

Route109_Text_ElijahPostBattle:
	.string "Pour un macho comme moi, un port\nest le lieu idéal!\pJe pense donc aller faire un tour\nà POIVRESSEL.$"

Route110_Text_JacobIntro:
	.string "Waouh! Regarde ça! Tu ne dois pas trop\nconnaître les courses de VELO.$"

Route110_Text_JacobDefeated:
	.string "Waouh! \nMes freins ont lâché!$"

Route110_Text_JacobPostBattle:
	.string "Des pneus à plat et des problèmes de\nfreins peuvent faire de sérieux dégâts!\pVérifie ton VELO!$"

Route110_Text_AnthonyIntro:
	.string "Hé, toi!\nTu peux aller aussi vite que moi?$"

Route110_Text_AnthonyDefeated:
	.string "Je suis anéanti!$"

Route110_Text_AnthonyPostBattle:
	.string "La vitesse ne suffira pas à me faire\ngagner aux POKéMON. Je dois revoir ça…$"

Route110_Text_BenjaminIntro:
	.string "Ne panique pas quand ton VELO va vite!$"

Route110_Text_BenjaminDefeated:
	.string "Je ne devrais pas m'affoler pendant les\ncombats de POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "Pas la peine de paniquer ou de stresser.\nT'énerve pas! Rien ne presse!$"

Route110_Text_BenjaminRegister:
	.string "Ce qui compte c'est l'entraînement.\nAppelle-moi si tu veux qu'on\lse retrouve.$"

Route110_Text_BenjaminRematchIntro:
	.string "T'irais pas un peu trop vite?\nT'énerve pas et viens te battre!$"

Route110_Text_BenjaminRematchDefeated:
	.string "Je n'ai pas paniqué, mais j'ai perdu…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Pas la peine de paniquer ou de stresser.\nT'énerve pas! Rien ne presse!$"

Route110_Text_AbigailIntro:
	.string "Le triathlon est extrêmement difficile.\pIl faut réussir trois épreuves:\nnatation, cyclisme et course à pied.$"

Route110_Text_AbigailDefeated:
	.string "C'est difficile aussi, les combats\nde POKéMON!$"

Route110_Text_AbigailPostBattle:
	.string "Je suis exténuée. Une pause s'impose.\nC'est important de bien se reposer.$"

Route110_Text_AbigailRegister:
	.string "Tu sais, je t'aime bien!\nÇa te dit une revanche sur la\lPISTE CYCLABLE?$"

Route110_Text_AbigailRematchIntro:
	.string "C'est pratique de livrer bataille en\nfaisant du VELO, non?$"

Route110_Text_AbigailRematchDefeated:
	.string "Waouh… Comment peut-on avoir autant\nde talent?$"

Route110_Text_AbigailRematchPostBattle:
	.string "T'essayais de battre un record?\pDésolée si je te retarde!$"

Route110_Text_JasmineIntro:
	.string "Je n'ai pas arrêté de faire du vélo.\nJ'ai des cuisses en béton!$"

Route110_Text_JasmineDefeated:
	.string "J'ai peur d'avoir des crampes…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tu as des BADGES D'ARENE?\nPas étonnant que tu aies un tel niveau!$"

Route110_Text_EdwardIntro:
	.string "J'ai deviné tes intentions!\nImpossible que je perde!$"

Route110_Text_EdwardDefeated:
	.string "Je n'ai même pas vu ma propre fin!$"

Route110_Text_EdwardPostBattle:
	.string "Je vois ton avenir…\pHum…\nJe vois une lumière briller…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\nMes prodiges vont t'éblouir!$"

Route110_Text_JaclynDefeated:
	.string "J'ai perdu de façon prodigieuse!$"

Route110_Text_JaclynPostBattle:
	.string "T'as gagné, mais c'était juste un\nmiracle! Oui, un miracle! Ne crois pas\lque tu vas gagner à tous les coups!$"

Route110_Text_EdwinIntro:
	.string "Je pourrais voir tes POKéMON?\nJuste un coup d'œil, s'il te plaît.$"

Route110_Text_EdwinDefeated:
	.string "Je voudrais compléter ma\ncollection…$"

Route110_Text_EdwinPostBattle:
	.string "Quand je vois un POKéMON que je ne\nconnais pas, ma passion s'enflamme!$"

Route110_Text_EdwinRegister:
	.string "J'adore collectionner les numéros\nde MATCH PHONE…$"

Route110_Text_EdwinRematchIntro:
	.string "Salut, t'as attrapé de nouveaux\nPOKéMON?\pJe pourrais voir tes POKéMON?\nJuste un coup d'œil, s'il te plaît.$"

Route110_Text_EdwinRematchDefeated:
	.string "Tes POKéMON…\nJe t'envie.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, je rêve de m'approprier tous les\nPOKéMON rares!$"

Route110_Text_DaleIntro:
	.string "Hé!\nNe te faufile pas derrière moi comme ça!$"

Route110_Text_DaleDefeated:
	.string "J'ai perdu!\nSapristi!$"

Route110_Text_DalePostBattle:
	.string "La pêche repose sur la concentration.\nIl faut se concentrer sur le bouchon.$"

Route110_Text_IsabelIntro:
	.string "Ahahahaha! Je voudrais aller partout\npour montrer mes adorables POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelPostBattle:
	.string "Plutôt que de me battre, je devrais\npeut-être montrer mes POKéMON au\lFAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Ce n'est pas comme ça que je pourrai\nfrimer avec mes POKéMON.\pJe te demanderai ton avis aussi\nsouvent que possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Je serais heureuse de te\nmontrer mes POKéMON quand tu voudras!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, non, j'peux pas accepter ça…$"

Route110_Text_IsabelRematchPostBattle:
	.string "Les CONCOURS, c'est charmant, je ne\npeux pas m'empêcher de montrer mes\lPOKéMON.\pMais j'aime aussi combattre!$"

Route110_Text_TimmyIntro:
	.string "J'ai trouvé des POKéMON sympas dans\nl'herbe aux alentours!$"

Route110_Text_TimmyDefeated:
	.string "Etre sympa ne suffit pas pour gagner…$"

Route110_Text_TimmyPostBattle:
	.string "C'est difficile de combattre avec des\nPOKéMON tout juste attrapés.$"

Route110_Text_AlyssaIntro:
	.string "Je suis tombée de la PISTE CYCLABLE…\pJe vais faire passer ma honte avec un\npetit combat contre toi!$"

Route110_Text_AlyssaDefeated:
	.string "Oups!\nTu as réussi à gagner!$"

Route110_Text_AlyssaPostBattle:
	.string "Tomber… Perdre…\nTout ça est si humiliant pour moi!$"

Route110_Text_JosephIntro:
	.string "OK!\nC'est parti pour un duo électrique!$"

Route110_Text_JosephDefeated:
	.string "T'as le groove toi!$"

Route110_Text_JosephPostBattle:
	.string "C'est pas grave. La défaite a fait de\nmoi un homme meilleur!$"

Route110_Text_KalebIntro:
	.string "Rien de plus beau que deux POKéMON\nqui s'entraident!$"

Route110_Text_KalebDefeated:
	.string "N'as-tu donc aucune compassion?$"

Route110_Text_KalebPostBattle:
	.string "Mes POKéMON ont fait de leur mieux,\nje ne leur en veux pas.$"

Route111_Text_DrewIntro:
	.string "Oh, hé! Ces LUNET. SABLE te vont bien.\nMais je trouve qu'elles me vont mieux.\pRéglons ça au combat! Voyons à qui\nelles vont le mieux!$"

Route111_Text_DrewDefeat:
	.string "Avec les LUNET. SABLE, j'ai pas pu\nvoir ce qui s'est passé.$"

Route111_Text_DrewPostBattle:
	.string "Les LUNET. SABLE permettent de\npasser à travers les tempêtes de sable.\lJ'en suis très content!$"

Route111_Text_HeidiIntro:
	.string "Je pique-nique dans le désert.\pIl y a souvent des DRESSEURS, alors\nje peux aussi prendre plaisir au combat!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! Quelle méchanceté!$"

Route111_Text_HeidiPostBattle:
	.string "Quand tu combats durant une tempête\nde sable, vérifie les PV de ton POKéMON.\pIl peut être mis K.O. si tu ne gardes pas\nun œil dessus!$"

Route111_Text_BeauIntro:
	.string "Avec ces LUNET. SABLE, j'ai l'impression\nd'être un super héros.\pPlus personne ne peut me battre!$"

Route111_Text_BeauDefeat:
	.string "Y croire ne suffit pas pour gagner…$"

Route111_Text_BeauPostBattle:
	.string "Un jour, je serai un vrai héros.\nJe vais travailler davantage pour que\lmes POKéMON et moi soyons plus forts.$"

Route111_Text_BeckyIntro:
	.string "Il paraît qu'il y a des fossiles\ndans le désert. Où peuvent-ils être?$"

Route111_Text_BeckyDefeat:
	.string "Je n'ai fait qu'une apparition…$"

Route111_Text_BeckyPostBattle:
	.string "Si on peut trouver des fossiles dans le\ndésert, il devait y avoir une mer avant.$"

Route111_Text_DustyIntro:
	.string "J'ai cherché des ruines antiques\npendant trente ans!\pPeux-tu me défier?$"

Route111_Text_DustyDefeat:
	.string "Comme je cherchais des ruines, je n'ai\npas cherché de POKéMON forts.$"

Route111_Text_DustyPostBattle:
	.string "J'ai cherché des ruines antiques\npendant trente ans!\pNon, attends, quarante ans?\nÇa fait combien maintenant?$"

Route111_Text_DustyRegister:
	.string "Je n'ai pas trop cherché de POKéMON\nvraiment coriaces.\pMais ça ne m'empêche pas de bien\naimer les POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "J'ai cherché des ruines antiques\npendant trente ans!\pNon, attends, quarante ans?\nDe toute façon, tu peux me défier?$"

Route111_Text_DustyRematchDefeat:
	.string "Je n'ai trouvé ni ruines,\nni POKéMON forts…$"

Route111_Text_DustyPostRematch:
	.string "J'ai cherché des ruines antiques\npendant trente ans!\pNon, attends, ça ferait quarante ans\nen fait?\pÇa pourrait même faire cinquante ans…\nMince, ça fait combien de temps?$"

Route111_Text_TravisIntro:
	.string "J'ai la pêche!\nEt mon POKéMON a de l'entrain aussi!$"

Route111_Text_TravisDefeat:
	.string "Mon POKéMON a perdu son entrain…$"

Route111_Text_TravisPostBattle:
	.string "Quand je vois un DRESSEUR plein\nd'entrain, je veux voir ce qu'il vaut.$"

Route111_Text_IreneIntro:
	.string "Je ne sais pas où tu vas, mais tu\nvoudrais bien te battre?$"

Route111_Text_IreneDefeat:
	.string "Oh, t'as une force pas possible!$"

Route111_Text_IrenePostBattle:
	.string "Je me disais que je devrais aller au\nMONT CHIMNEE, mais la vue est\légalement superbe ici.$"

Route111_Text_DaisukeIntro:
	.string "Pour m'entraîner, je défie tous ceux\nque je rencontre!$"

Route111_Text_DaisukeDefeat:
	.string "Je déclare forfait! J'abandonne!$"

Route111_Text_DaisukePostBattle:
	.string "Tout ce que je peux faire, c'est\ncontinuer à m'entraîner jusqu'à ce que\lje puisse battre des DRESSEURS\laussi forts que toi.$"

Route111_Text_WiltonIntro:
	.string "Fais-moi voir comme tu as endurci\ntes POKéMON!$"

Route111_Text_WiltonDefeat:
	.string "Je vois, tu les as considérablement\nendurcis.$"

Route111_Text_WiltonPostBattle:
	.string "Les POKéMON et les DRESSEURS\napprennent beaucoup au combat.\pLe plus important, c'est de ne jamais\nabandonner, même quand on perd.$"

Route111_Text_WiltonRegister:
	.string "Il y aurait beaucoup à dire sur ton\nstyle de combat.\pSi tu es d'accord, j'aimerais vraiment\nune revanche.$"

Route111_Text_WiltonRematchIntro:
	.string "On s'entraîne ici pour passer au\nniveau supérieur.\lReste et entraîne-toi avec nous!$"

Route111_Text_WiltonRematchDefeat:
	.string "Oh, pas si mal!$"

Route111_Text_WiltonPostRematch:
	.string "Si tu as un tel niveau, tu devrais\nviser la LIGUE POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, tes POKéMON ont l'air de faire\nbonne figure.\lJe vais les enrôler.$"

Route111_Text_BrookeDefeat:
	.string "Ils ne paraissent pas seulement forts,\nils le sont réellement!$"

Route111_Text_BrookePostBattle:
	.string "Je pensais entraîner mes POKéMON\nassidûment, mais il y a encore du pain\lsur la planche.$"

Route111_Text_BrookeRegister:
	.string "J'aimerais tant avoir plus d'amis aussi\nforts que toi.$"

Route111_Text_BrookeRematchIntro:
	.string "Tu peux rendre tes POKéMON plus\nou moins forts en fonction des\lcapacités que tu leur apprends.\pQuelles sortes de capacités tes\nPOKéMON connaissent-ils?$"

Route111_Text_BrookeRematchDefeat:
	.string "Tu leur as appris de bonnes capacités!$"

Route111_Text_BrookePostRematch:
	.string "J'aurais peut-être dû empêcher mes\nPOKéMON d'évoluer jusqu'à ce qu'ils\lapprennent de meilleures capacités…$"

Route111_Text_CeliaIntro:
	.string "Je n'aurais vraiment pas dû venir ici\npour un pique-nique!$"

Route111_Text_CeliaDefeat:
	.string "Aïe!\nJe n'aurais vraiment pas dû venir!$"

Route111_Text_CeliaPostBattle:
	.string "Dans une tempête de sable comme ça,\nil est vraiment impossible de faire\pun pique-nique, même avec\nles LUNET. SABLE!$"

Route111_Text_BryanIntro:
	.string "Es-tu vraiment si redoutable?\nJe vais tenter de percer ce secret!$"

Route111_Text_BryanDefeat:
	.string "Oh, ta force!\nElle est entourée de mystère!$"

Route111_Text_BryanPostBattle:
	.string "Ce désert regorge de mystères enfouis\nsous le sable!$"

Route111_Text_BrandenIntro:
	.string "Si je gagne, je te donnerai un de mes\nsandwichs!$"

Route111_Text_BrandenDefeat:
	.string "Pff, je pensais qu'un sandwich\nsuffirait à te corrompre…$"

Route111_Text_BrandenPostBattle:
	.string "Mon SABELETTE adore manger\nmes sandwichs.$"

Route111_Text_TyronIntro:
	.string "C'est mon genre de POKéMON préféré!$"

Route111_Text_TyronDefeat:
	.string "Attends!\nTu as bien regardé mon POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "Au début d'un combat, j'adore le\nmoment où je présente mes POKéMON.\pMais je suis sûr que tout le monde\nressent la même fierté, non?$"

Route111_Text_CelinaIntro:
	.string "Montre-moi comment mettre un\npeu de piment dans ma vie!$"

Route111_Text_CelinaDefeat:
	.string "Oh… Non…\nC'était trop épicé pour moi!$"

Route111_Text_CelinaPostBattle:
	.string "Mon cœur bat encore à tout rompre.\nTu es un DRESSEUR d'exception.$"

Route111_Text_HaydenIntro:
	.string "Quelqu'un d'aussi connu que moi ne\nconnaît aucune pitié.$"

Route111_Text_HaydenDefeat:
	.string "Grr…$"

Route111_Text_HaydenPostBattle:
	.string "Mon estomac gargouille!\nJe devrais essayer de me faire griller\lquelques BAIES…$"

Route111_Text_BiancaIntro:
	.string "Tu viens de LAVANDIA?\nQuelle énergie tu dois avoir!$"

Route111_Text_BiancaDefeat:
	.string "Ooh là là!\nC'était trop pour moi!$"

Route111_Text_BiancaPostBattle:
	.string "Cette route…\pTu n'es pas encore au bout de\ntes peines.$"

Route112_Text_BriceIntro:
	.string "Ahahahaha!\nEt si on s'affrontait?\pToi et moi!\nAhahahaha!$"

Route112_Text_BriceDefeat:
	.string "J'ai perdu!\nAhahahaha!$"

Route112_Text_BricePostBattle:
	.string "Ahahahahaha! Quelque chose me monte\nau nez! Ahahahaha-tchoum!$"

Route112_Text_TrentIntro:
	.string "Mes jambes se sont endurcies à fouler\nle sol rocheux des montagnes.\pElles ne vont pas flancher facilement,\ncamarade!$"

Route112_Text_TrentDefeat:
	.string "Ouille!\nJ'ai des crampes dans les jambes!$"

Route112_Text_TrentPostBattle:
	.string "Essaie d'escalader ces sentiers de\nmontagne en portant un bon poids\lsur le dos.\pÇa, camarade, ça te fera un bon\nexercice.$"

Route112_Text_TrentRegister:
	.string "Mes jambes sont pleines de crampes.\nTu peux m'attraper la pommade qui\lest dans mon sac à dos?\pNon, ça c'est mon POKéNAV!\nOK, je t'enregistre!$"

Route112_Text_TrentRematchIntro:
	.string "J'ai gardé la forme grâce à la\nrandonnée.\pDe la puissance, j'en ai à la pelle!$"

Route112_Text_TrentRematchDefeat:
	.string "Me suis-je fait battre en puissance?$"

Route112_Text_TrentRematchPostBattle:
	.string "J'ai entendu dire qu'il y avait des\nDRESSEURS en haut du MONT CHIMNEE.\pJe compte y monter pour leur lancer\nun défi!$"

Route112_Text_LarryIntro:
	.string "Je suis fort.\nJ'vais pas pleurer si je perds.$"

Route112_Text_LarryDefeat:
	.string "Ouuuin!$"

Route112_Text_LarryPostBattle:
	.string "J'pleure pas parce que maman me manque!\nSniff…$"

Route112_Text_CarolIntro:
	.string "Quand tu pars faire un pique-nique,\nil faut chanter!\lViens, chante avec moi!$"

Route112_Text_CarolDefeat:
	.string "Oh, quel talent!$"

Route112_Text_CarolPostBattle:
	.string "Peu importe que tu sois bon ou mauvais\nen chant et en POKéMON.\pLe gagnant est celui qui prend le plus\nde plaisir!$"

Route112_Text_BryantIntro:
	.string "J'ai attrapé des POKéMON brûlants sur\nle CHEMIN ARDENT!\pTu veux les voir?$"

Route112_Text_BryantDefeat:
	.string "C'était vraiment chaud!$"

Route112_Text_BryantPostBattle:
	.string "J'aime beaucoup ta façon de combattre.\pOn sent que l'inspiration te vient\nnaturellement.$"

Route112_Text_ShaylaIntro:
	.string "Oh, quel DRESSEUR adorable tu es!\pBattons-nous de façon courtoise,\nje t'en prie!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, quelle force!\nJ'en suis toute retournée.$"

Route112_Text_ShaylaPostBattle:
	.string "Tu as des choses à faire en ce moment?\nJe pensais qu'on pourrait peut-être\lfaire notre match de revanche…\pMais ne t'inquiète pas, ce n'est pas\ngrave si tu n'as pas le temps.$"

Route113_Text_JaylenIntro:
	.string "Tu sais pourquoi il fait si frais dans\nles alentours?$"

Route113_Text_JaylenDefeat:
	.string "Arrrg!\nJ'suis dégoûté!$"

Route113_Text_JaylenPostBattle:
	.string "Comme les cendres volcaniques gênent \nle soleil, il ne fait pas trop chaud.\pTant mieux, je ne supporte pas\nla chaleur!$"

Route113_Text_DillonIntro:
	.string "Les éruptions volcaniques prouvent que\nla terre est en vie.$"

Route113_Text_DillonDefeat:
	.string "T'es quelqu'un de fort!$"

Route113_Text_DillonPostBattle:
	.string "Ah! J'peux plus avancer! Les cendres\nm'empêchent de descendre!\pTu piges? Les cendres et descendre?\pD'accord, c'était pas terrible. Désolé…$"

Route113_Text_MadelineIntro:
	.string "Je prends ce parasol pour que mon cher\nCHAMALLOT ne soit pas recouvert de ces\lfichues cendres dégoûtantes.$"

Route113_Text_MadelineDefeat:
	.string "Fooouuu…\nJe suis exténuée…$"

Route113_Text_MadelinePostBattle:
	.string "Tu as vraiment du talent!\nJe dois dire que je suis impressionnée!$"

Route113_Text_MadelineRegister:
	.string "Viens te mettre à l'abri sous mon\nparasol.\pLaisse-moi t'enregistrer dans mon\nPOKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh salut, ça faisait longtemps, hein?\nPuis-je t'inviter à combattre?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, génial!$"

Route113_Text_MadelinePostRematch:
	.string "Tu as toujours autant de talent.\nJe dois dire que je suis impressionnée!$"

Route113_Text_LaoIntro:
	.string "Je jaillis des cendres! Yaha!\nJe t'mets au défi!$"

Route113_Text_LaoDefeat:
	.string "J'admets la défaite avec dignité!$"

Route113_Text_LaoPostBattle:
	.string "Il me faut parfaire l'art de la\ndissimulation. Je te fais mes adieux.$"

Route113_Text_LaoRegister:
	.string "Yahah! Admire l'ancienne technique\nninja d'enregistrement sur POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Je jaillis des cendres! Yaha!\nJe t'mets au défi!$"

Route113_Text_LaoRematchDefeat:
	.string "J'admets la défaite avec dignité!$"

Route113_Text_LaoPostRematch:
	.string "Mon manque d'expérience au combat\na déprécié ma dissimulation parfaite.\pJe te fais mes adieux.$"

Route113_Text_LungIntro:
	.string "Merci de m'avoir trouvé!\nMais on va quand même devoir se battre!$"

Route113_Text_LungDefeat:
	.string "Je vais utiliser mon pouvoir de ninja\nsur toi…\p«Que les cendres volcaniques\ntournoient!» \p… Comment? C'est déjà fini?$"

Route113_Text_LungPostBattle:
	.string "Tu sais c'que c'est le pire quand tu\nte caches?\pC'est de rester seul si personne\nne vient.$"

Route113_Text_ToriIntro:
	.string "LILA: On ramasse des cendres toutes\nles deux et on fait des combats\lde POKéMON.$"

Route113_Text_ToriDefeat:
	.string "LILA: On a perdu… Ça m'énerve, alors\nj'vais aller ramasser d'autres cendres.$"

Route113_Text_ToriPostBattle:
	.string "LILA: On a quoi en cendres? Assez\npour faire une FLUTEBLANCHE, j'espère.$"

Route113_Text_ToriNotEnoughMons:
	.string "LILA: On veut se battre en 2 contre\n2. Sinon, on risquerait de perdre!$"

Route113_Text_TiaIntro:
	.string "NELLY: Toutes les deux, on ramasse des\ncendres et on combat avec des POKéMON.$"

Route113_Text_TiaDefeat:
	.string "NELLY: On n'a pas gagné… Ça m'agace!\nJe vais aller ramasser d'autres cendres.$"

Route113_Text_TiaPostBattle:
	.string "NELLY: On a tout plein de cendres! \nAssez je pense pour une FLUTEBLANCHE!$"

Route113_Text_TiaNotEnoughMons:
	.string "NELLY: On veut se battre en\n2 contre 2. Sinon, on va perdre!$"

Route113_Text_CobyIntro:
	.string "Pff, avec ces ailes, je pourrais\nfacilement t'envoyer balader!$"

Route113_Text_CobyDefeat:
	.string "Euh… Quoi?$"

Route113_Text_CobyPostBattle:
	.string "Je ne sais pas vraiment quoi dire après\nune si grosse défaite…$"

Route113_Text_SophieIntro:
	.string "La chaleur qu'il fait ici me fait\nsomnoler.\pBattons-nous pour me faire rester\ndebout.$"

Route113_Text_SophieDefeat:
	.string "Je suis en train de rêver,\nj'en suis sûre…$"

Route113_Text_SophiePostBattle:
	.string "Ça m'énerve de perdre!\nJe préfère encore dormir…\lZzzz…$"

Route113_Text_LawrenceIntro:
	.string "Tu étais peut-être en train de récolter\ndes cendres?$"

Route113_Text_LawrenceDefeat:
	.string "Oups.\nTu nous as eus proprement!$"

Route113_Text_LawrencePostBattle:
	.string "Je ferais mieux de me cacher aussi\nsous les cendres!$"

Route113_Text_WyattIntro:
	.string "T… tu veux… te battre\ncontre moi?\pMais je viens à peine d'attraper\nmes POKéMON!$"

Route113_Text_WyattDefeat:
	.string "Que… Gagner a l'air de te\nfaire plaisir…\pMême contre quelqu'un comme moi?$"

Route113_Text_WyattPostBattle:
	.string "Oh, alors tu veux dire un mot au\nperdant?\pL'humilité, tu connais?$"

Route114_Text_LennyIntro:
	.string "Lalalahihou!\p… …\pIl faut que tu cries «Lalalahihou!»\nsi tu veux entendre ton écho!$"

Route114_Text_LennyDefeat:
	.string "Lalalahihou!$"

Route114_Text_LennyPostBattle:
	.string "Quand j'étais môme, je croyais que\nquelqu'un m'imitait et répétait\l«Lalalahihou».$"

Route114_Text_LucasIntro:
	.string "Tu ne devrais pas grimper dans\nles montagnes sans préparation!$"

Route114_Text_LucasDefeat:
	.string "La montagne ne pardonne pas…$"

Route114_Text_LucasPostBattle:
	.string "En hiver, le blizzard et les avalanches\nrendent la montagne mortelle.$"

Route114_Text_ShaneIntro:
	.string "C'est sympa le camping! On pêche, on\nfait griller des marshmallows et on\lraconte des histoires qui font peur!\pMais le top, ce sont les combats de\nPOKéMON!$"

Route114_Text_ShaneDefeat:
	.string "Trop dur pour moi!$"

Route114_Text_ShanePostBattle:
	.string "Je trouve ça bien de pouvoir aller\nfaire du camping avec mes POKéMON.$"

Route114_Text_NancyIntro:
	.string "J'ai besoin d'exercice après un repas.\nAffrontons-nous!$"

Route114_Text_NancyDefeat:
	.string "Oh, non!$"

Route114_Text_NancyPostBattle:
	.string "Je viens de prendre un délicieux repas,\nalors je m'endors un peu…$"

Route114_Text_SteveIntro:
	.string "Ohohohoh…\nTu veux affronter mon POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M… Mon POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un grand corps tout dur, d'énormes\ncornes et de puissants crocs…\pOhohohoh…\nJ'aimerais avoir un POKéMON comme ça…$"

Route114_Text_SteveRegister:
	.string "N'oublie pas ce que tu viens de me faire!\nMoi, je n'oublierai pas!$"

Route114_Text_SteveRematchIntro:
	.string "Ohohohoho…\nViens te battre contre moi…$"

Route114_Text_SteveRematchDefeat:
	.string "J'ai de la chance d'avoir pu voir\ntes POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ohohohoho…\pQuand je vois des POKéMON se battre,\nj'ai des frissons et je tremble…$"

Route114_Text_BernieIntro:
	.string "Avant d'allumer un feu de camp, il faut\ns'assurer d'avoir de l'eau à proximité.$"

Route114_Text_BernieDefeat:
	.string "Merci d'avoir éteint mon feu!$"

Route114_Text_BerniePostBattle:
	.string "En forêt, il faut faire très attention\nau feu sous toutes ses formes.\pNe sous-estime pas la puissance du\nfeu.$"

Route114_Text_BernieRegister:
	.string "Je meurs d'envie d'avoir une revanche!\nEnregistrons-nous dans nos POKéNAVS!$"

Route114_Text_BernieRematchIntro:
	.string "Tu sais que pour faire un feu de camp,\nil faut avoir de l'eau à portée de main?$"

Route114_Text_BernieRematchDefeat:
	.string "Je me suis pris une douche avant même\nde m'enflammer.$"

Route114_Text_BerniePostRematch:
	.string "En forêt, il faut faire très attention\nau feu sous toutes ses formes.\pNe sous-estime pas sa puissance.$"

Route114_Text_ClaudeIntro:
	.string "Si on s'affrontait à la pêche, tu\nn'aurais aucune chance contre moi.\lAlors, amène tes POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Si on avait pêché, j'aurais gagné…$"

Route114_Text_ClaudePostBattle:
	.string "Je crois que je vais essayer de faire\nune bonne prise au SITE METEORE.\pIl doit y avoir quelque chose là-bas.\nJe le sens!$"

Route114_Text_NolanIntro:
	.string "J'aime pêcher. Mais j'aime bien\ncombattre aussi!\pSi quelqu'un me défie, je suis toujours\nprêt, même si je suis en train de pêcher.$"

Route114_Text_NolanDefeat:
	.string "J'aime combattre, mais ça ne veut pas\ndire que je suis bon…$"

Route114_Text_NolanPostBattle:
	.string "Cette fois, je vais y arriver!\pJe me dis toujours ça, alors j'arrête\njamais avec la pêche et les POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Eh bien, oui.\nJe me sens d'humeur.\pJe vais t'en apprendre sur les POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Etonnante façon de se battre!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Je donnais à IVY une\nleçon sur les POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Hi, hi, hi…\nSi tu veux te battre contre nous, un\lseul POKéMON ne suffira pas!$"

Route114_Text_IvyIntro:
	.string "IVY: Qui t'a appris ce que tu sais\nsur les POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Etonnante façon de se battre!$"

Route114_Text_IvyPostBattle:
	.string "IVY: J'ai commencé à entraîner des\nPOKéMON parce que TYRA, mon cher\lprofesseur, me l'a enseigné!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Tu n'as qu'un seul POKéMON?\nIl doit se sentir seul.$"

Route114_Text_KaiIntro:
	.string "J'en ai attrapé un gros!\nUn gros, je te dis!$"

Route114_Text_KaiDefeat:
	.string "Quoi la taille?\nLe mien a perdu à cause de sa taille?$"

Route114_Text_KaiPostBattle:
	.string "OK…\nJe vais en attraper un plus gros!$"

Route114_Text_CharlotteIntro:
	.string "Moi, je n'ai pas qu'un joli minois!$"

Route114_Text_CharlotteDefeat:
	.string "C'était pas mignon de ta part!$"

Route114_Text_CharlottePostBattle:
	.string "Je ne veux pas de POKéMON qui soient\nseulement mignons.\pIls doivent avoir un petit je ne sais\nquoi en plus!$"

Route114_Text_AngelinaIntro:
	.string "As-tu bien fait évoluer tes POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, je vois…\nC'est bon à savoir!$"

Route114_Text_AngelinaPostBattle:
	.string "Certains POKéMON changent\nradicalement en évoluant,\lc'est vraiment impressionnant!$"

Route115_Text_TimothyIntro:
	.string "Hum…\nTu as l'air tout à fait capable…\lLaisse-moi te tenir compagnie!$"

Route115_Text_TimothyDefeat:
	.string "Tu as plus de puissance que je ne\nl'avais imaginé!$"

Route115_Text_TimothyPostBattle:
	.string "Rien n'est inné!\nTout s'acquiert par le travail!\lC'est ce que je crois…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Cette défaite est un vieux\nsouvenir pour moi.\pSi tu le permets, j'aimerais bien avoir\nma revanche!$"

Route115_Text_TimothyRematchIntro:
	.string "Hum… Comme toujours, ton agilité\nparle d'elle-même.\lViens me tenir compagnie!$"

Route115_Text_TimothyRematchDefeat:
	.string "Plus de force que jamais!$"

Route115_Text_TimothyPostRematch:
	.string "Tout est une question d'efforts!\pJ'ai perdu parce que je n'ai pas fait\nassez d'efforts!$"

Route115_Text_KoichiIntro:
	.string "Toi!\nMes MACHOC!\pJ'exige un combat!$"

Route115_Text_KoichiDefeat:
	.string "Oh là là!$"

Route115_Text_KoichiPostBattle:
	.string "Mon équipe de MACHOC!\pTant qu'ils chercheront la puissance, je\nm'endurcirai avec eux!$"

Route115_Text_NobIntro:
	.string "Mon plus grand talent, c'est de pouvoir\ncasser des briques avec mon front!$"

Route115_Text_NobDefeat:
	.string "Aaaaaaaah!\nJ'ai la tête en vrac!$"

Route115_Text_NobPostBattle:
	.string "J'ai appris le karaté à mon POKéMON.\pOn dirait que ça lui profite plus qu'à\nmoi. Je m'en réjouis.$"

Route115_Text_NobRegister:
	.string "Tu m'impressionnes! Je prendrai ma\nrevanche après mon entraînement!$"

Route115_Text_NobRematchIntro:
	.string "Après que tu m'as battu, on s'est\nentraînés dur pour s'améliorer…\pViens, on veut prendre notre revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Arrrrg!\nOn a encore perdu!$"

Route115_Text_NobPostRematch:
	.string "Mon POKéMON va devenir plus fort!\nJe renforce mon entraînement!$"

Route115_Text_CyndyIntro:
	.string "Cette plage est le camp secret où je\nm'entraîne! Ne viens pas me déranger!$"

Route115_Text_CyndyDefeat:
	.string "Je ne me suis pas assez entraînée!$"

Route115_Text_CyndyPostBattle:
	.string "Le sable est comme un coussin qui\namortit les chocs et qui empêche de\lse faire mal.\pC'est l'endroit idéal pour s'entraîner.$"

Route115_Text_CyndyRegister:
	.string "Bien… Tu es libre de venir.\nEn retour, j'aimerais t'affronter de\lnouveau.$"

Route115_Text_CyndyRematchIntro:
	.string "OK, que le combat commence!$"

Route115_Text_CyndyRematchDefeat:
	.string "Je peux me battre, mais mes POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Lorsque je perds, j'en tire quand même\nun certain plaisir.\pÇa doit être que j'aime mes POKéMON.$"

Route115_Text_HectorIntro:
	.string "J'ai un POKéMON rare!\nTu voudrais le voir?$"

Route115_Text_HectorDefeat:
	.string "Tu…\nTu veux mon POKéMON, c'est ça?$"

Route115_Text_HectorPostBattle:
	.string "J'ai ce POKéMON rare.\nJe ne le céderai pas.$"

Route115_Text_KyraIntro:
	.string "Je vais me battre en courant!\nEssaie de me rattraper!$"

Route115_Text_KyraDefeat:
	.string "J'ai un point de côté…$"

Route115_Text_KyraPostBattle:
	.string "J'ai fait l'erreur de vouloir me battre\nen courant!\pJe devrais faire une course pour me\ncalmer!$"

Route115_Text_JaidenIntro:
	.string "Prends ça!\nAttaque ninja ultra POKéMON!$"

Route115_Text_JaidenDefeat:
	.string "Ouaaah!\nMa stratégie n'était pas la bonne!$"

Route115_Text_JaidenPostBattle:
	.string "Mais mes POKéMON étaient\nsuper géniaux, non?$"

Route115_Text_HeleneIntro:
	.string "Mes POKéMON mériteraient d'avoir\nune ceinture noire!$"

Route115_Text_HeleneDefeat:
	.string "Quelle humiliation!$"

Route115_Text_HelenePostBattle:
	.string "J'ai rarement vu quelqu'un d'aussi\nfort que moi…\pJ'ai compris!\nTu dois être un CHAMPION D'ARENE,\ln'est-ce pas?$"

Route115_Text_AlixIntro:
	.string "Tu oses croiser mon regard?\nPas d'échappatoire pour toi!$"

Route115_Text_AlixDefeat:
	.string "Gaaah!\nPas mal!$"

Route115_Text_AlixPostBattle:
	.string "Très bien!\pJe vais me TELEPORTER à la\nmaison!$"

Route115_Text_MarleneIntro:
	.string "Tu déranges ma méditation…\nJe vais te le faire payer!$"

Route115_Text_MarleneDefeat:
	.string "Tu as brisé ma concentration!$"

Route115_Text_MarlenePostBattle:
	.string "Je méditais avec mes POKéMON.\nMais ce n'est pas l'endroit idéal…$"

Route116_Text_ClarkIntro:
	.string "S'il n'y a pas de tunnel de construit,\nalors je passerai par en haut.$"

Route116_Text_ClarkDefeat:
	.string "Pfou… Pfou…\nÇa fatigue de perdre…$"

Route116_Text_ClarkPostBattle:
	.string "C'est pas grave s'il n'y a pas de tunnel.\nUn MONTAGNARD passe par les montagnes!$"

Route116_Text_JoeyIntro:
	.string "Mon POKéMON est le roi!\nRegarde un peu!$"

Route116_Text_JoeyDefeat:
	.string "Aïe! Une coupure!\nIl faut que je mette un pansement!$"

Route116_Text_JoeyPostBattle:
	.string "Les pansements prouvent la résistance\nau combat! J'en ai un autre!$"

Route116_Text_JoseIntro:
	.string "Mes POKéMON INSECTE sont résistants!\nBattons-nous!$"

Route116_Text_JoseDefeat:
	.string "J'ai perdu!\nJe croyais pouvoir te vaincre!$"

Route116_Text_JosePostBattle:
	.string "Les POKéMON INSECTE évoluent vite.\nAlors ils deviennent vite forts aussi.$"

Route116_Text_JaniceIntro:
	.string "Laisse-moi te montrer comme mon\nadorable POKéMON est fort!$"

Route116_Text_JaniceDefeat:
	.string "Tu joues dans la catégorie supérieure…$"

Route116_Text_JanicePostBattle:
	.string "Je trouve que l'idéal pour un POKéMON,\nc'est de mêler charme et puissance.$"

Route116_Text_JerryIntro:
	.string "On apprend toutes sortes de choses à\nl'ECOLE DE DRESSEURS.\pJe veux mettre tout ça en pratique!$"

Route116_Text_JerryDefeat:
	.string "Je me suis un peu relâché à l'école…\nC'est pour ça que j'ai perdu.$"

Route116_Text_JerryPostBattle:
	.string "Je vais devoir reprendre des cours à\nl'ECOLE DE DRESSEURS.\pSinon, ROXANNE va pester.$"

Route116_Text_JerryRegister1:
	.string "J'ai appris à l'ECOLE DE DRESSEURS\nque les POKéNAVS peuvent enregistrer\lles DRESSEURS.\pJe sais pas vraiment comment ça marche,\ntu me laisses essayer?$"

Route116_Text_JerryRegister2:
	.string "J'ai appris à l'ECOLE DE DRESSEURS\nque les POKéNAVS peuvent enregistrer\lles DRESSEURS.\pJe sais pas vraiment comment ça marche,\ntu me laisses essayer?$"

Route116_Text_JerryRematchIntro:
	.string "J'ai étudié sérieusement à l'ECOLE\nDE DRESSEURS.\pCette fois, je ne vais pas perdre.$"

Route116_Text_JerryRematchDefeat:
	.string "Hum?\nJ'ai étudié avec assiduité.$"

Route116_Text_JerryPostRematch:
	.string "Je vais devoir reprendre des cours à\nl'ECOLE DE DRESSEURS.\pSinon, ROXANNE va pester.$"

Route116_Text_KarenIntro:
	.string "J'étudie à l'école et j'étudie aussi\nen rentrant chez moi!$"

Route116_Text_KarenDefeat:
	.string "Quel choc! J'ai perdu?$"

Route116_Text_KarenPostBattle:
	.string "C'est pas comme ça que je vais devenir\nun DRESSEUR avec autant de charme\lque ROXANNE!$"

Route116_Text_KarenRegister1:
	.string "Oh, waouh! C'est un POKéNAV?\nJ'en ai un aussi!\pLaisse-moi t'enregistrer!$"

Route116_Text_KarenRegister2:
	.string "Oh, waouh! C'est un POKéNAV?\nJ'en ai un aussi!\pLaisse-moi t'enregistrer!$"

Route116_Text_KarenRematchIntro:
	.string "J'ai beaucoup appris depuis la dernière\nfois. Il faut que tu voies mes progrès!$"

Route116_Text_KarenRematchDefeat:
	.string "Quel choc! J'ai encore perdu?$"

Route116_Text_KarenPostRematch:
	.string "Tu as battu ROXANNE? Je ne vais pas\npouvoir te battre alors. Pas encore.$"

Route116_Text_SarahIntro:
	.string "Pour ta gouverne, personne n'a jamais\npu me vaincre, personne!$"

Route116_Text_SarahDefeat:
	.string "Eh bien, quelle expérience troublante…$"

Route116_Text_SarahPostBattle:
	.string "J'ai les moyens de m'offrir tout ce\nque je souhaite!\pMais pour les POKéMON, ma fortune\nne me sert à rien.$"

Route116_Text_DawsonIntro:
	.string "Si tu poses les yeux sur mes POKéMON,\nleur beauté te laissera le souffle\lcoupé, j'en suis certain!$"

Route116_Text_DawsonDefeat:
	.string "Oh, dis-moi que ça n'est pas vrai!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, non, non, non!\nTu as abîmé la fourrure de mes POKéMON!\pEt aussi mon brushing! Je n'ai plus\nqu'à appeler mon styliste!$"

Route116_Text_DevanIntro:
	.string "T'as pris tes chaussures de marche?$"

Route116_Text_DevanDefeat:
	.string "Aïe aïe aïe!$"

Route116_Text_DevanPostBattle:
	.string "Je devrais essayer d'autres types de\nPOKéMON…\lC'est ce que je devrais faire…$"

Route116_Text_JohnsonIntro:
	.string "C'est une voie sans issue.\nJe m'ennuie… On se bat?$"

Route116_Text_JohnsonDefeat:
	.string "C'était vraiment marrant…\nMême si j'ai perdu…$"

Route116_Text_JohnsonPostBattle:
	.string "Tu voudrais pas rester ici pour me\ntenir compagnie?$"

Route117_Text_IsaacIntro:
	.string "Ecoute, tu pourrais te battre contre\nles POKéMON que j'élève?$"

Route117_Text_IsaacDefeat:
	.string "Tu as très bien élevé les tiens…$"

Route117_Text_IsaacPostBattle:
	.string "Les POKéMON, ce n'est pas qu'une\nquestion de force.\pParfaire la particularité d'une\npersonnalité, c'est une autre façon\ld'apprécier les POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Je vais m'entraîner deux fois plus.\nTu viendras me voir?$"

Route117_Text_IsaacRematchIntro:
	.string "Les POKéMON que j'élève ont l'air en\nforme, exactement comme avant.$"

Route117_Text_IsaacRematchDefeat:
	.string "Tu sais les élever comme il faut.\nTu pourrais tenir une PENSION…$"

Route117_Text_IsaacPostRematch:
	.string "Tes POKéMON grandissent bien!\nTu devrais les inscrire à des CONCOURS.$"

Route117_Text_LydiaIntro:
	.string "Tu permets que je vérifie si tes\nPOKéMON se développent bien?$"

Route117_Text_LydiaDefeat:
	.string "Oui, ils grandissent bien.$"

Route117_Text_LydiaPostBattle:
	.string "Essaie d'élever tes POKéMON en faisant\nattention à leurs traits de caractère.$"

Route117_Text_LydiaRegister:
	.string "Je suis contente d'avoir rencontré un\nDRESSEUR comme toi.\pJ'espère qu'on se reverra!$"

Route117_Text_LydiaRematchIntro:
	.string "Tu permets que je revérifie si tu as\nbien élevé tes POKéMON?$"

Route117_Text_LydiaRematchDefeat:
	.string "Ils se développent admirablement bien.$"

Route117_Text_LydiaPostRematch:
	.string "Les POKéMON aiment différentes sortes\nde {POKEBLOCK}S selon leur nature.$"

Route117_Text_DylanIntro:
	.string "Je suis en plein milieu d'un triathlon,\nmais tant pis, battons-nous!$"

Route117_Text_DylanDefeat:
	.string "Je n'ai plus du tout de force!$"

Route117_Text_DylanPostBattle:
	.string "J'aurais pu te balayer…\pJ'aurais peut-être dû ralentir le\nrythme pour tenir sur la durée…$"

Route117_Text_DylanRegister:
	.string "Les POKéMON aussi doivent être forts?\nTu veux bien devenir mon entraîneur?$"

Route117_Text_DylanRematchIntro:
	.string "On n'est qu'à la moitié du triathlon et\nje suis claqué, mais je suis en tête.\pAffrontons-nous!$"

Route117_Text_DylanRematchDefeat:
	.string "Je suis encore à bout de forces!$"

Route117_Text_DylanPostRematch:
	.string "Je suis au top à la natation et en\ncyclisme, mais je ne suis pas aussi\lconfiant pour les POKéMON.$"

Route117_Text_MariaIntro:
	.string "Je fais du triathlon avec mon POKéMON,\nalors je suis confiante pour la vitesse.$"

Route117_Text_MariaDefeat:
	.string "Je crois qu'il me faut plus de\npratique.$"

Route117_Text_MariaPostBattle:
	.string "L'entraînement n'a de sens que s'il est\npratiqué régulièrement.\pOK! Je me remets à l'entraînement!\nDès demain!$"

Route117_Text_MariaRegister:
	.string "Ton entraînement a l'air d'être\nvraiment efficace…\pOn s'affrontera plus tard si tu\nveux bien!$"

Route117_Text_MariaRematchIntro:
	.string "Tu continues à t'entraîner?\nMoi, oui!\lLaisse-moi te le prouver!$"

Route117_Text_MariaRematchDefeat:
	.string "Je crois qu'il me faut plus de\npratique.$"

Route117_Text_MariaPostRematch:
	.string "Demain, je me remets à l'entraînement.\nOn se rebattra bien un jour ou l'autre!$"

Route117_Text_DerekIntro:
	.string "Hier un SCOUT…\net maintenant un ENTOMOMANIAC!\pMais mon amour pour les POKéMON\nreste intact!$"

Route117_Text_DerekDefeat:
	.string "Mon incompétence, elle aussi,\nest toujours intacte…$"

Route117_Text_DerekPostBattle:
	.string "Je n'ai fait que suivre mon cœur, et me\nvoilà considéré comme un ENTOMOMANIAC.\pEnfin, étant un expert en POKéMON\nINSECTE, c'est normal qu'on me\lconsidère comme un ENTOMOMANIAC.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Je suis avec ma charmante\npartenaire. Je dois être à la hauteur!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Je suis avec ma charmante\npartenaire! Tu aurais pû me laisser\lgagner!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Tes POKéMON se complètent\nbien.\pJe dirais que tu es juste derrière nous!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: On ne peut pas en rester là!\nTu reviendras, hein?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Si tu veux nous affronter,\nprends deux POKéMON avec toi.$"

Route117_Text_MegIntro:
	.string "EVA: On va s'accrocher avec ma\npartenaire de choc et on va t'écraser!$"

Route117_Text_MegDefeat:
	.string "EVA: Oh, non!\nANNA, je suis désolée de te\ldécevoir…$"

Route117_Text_MegPostBattle:
	.string "EVA: J'ai déçu ANNA…\nSans moi, elle aurait gagné!$"

Route117_Text_MegNotEnoughMons:
	.string "EVA: Tu n'as qu'un seul POKéMON?\nAlors on ne va pas pouvoir s'affronter.\pOn veut combattre en 2 contre 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Je ne peux pas continuer à\nperdre devant ma partenaire, pas vrai?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Je n'ai pas trouvé mon rythme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Tes POKéMON se complètent\nbien.\pJe dirais que tu es juste derrière nous!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Si tu veux nous affronter,\nprends deux POKéMON avec toi.$"

Route117_Text_MegRematchIntro:
	.string "EVA: On va s'accrocher avec ma\npartenaire et cette fois, on va gagner!$"

Route117_Text_MegRematchDefeat:
	.string "EVA: Trop balèze pour nous!$"

Route117_Text_MegPostRematch:
	.string "EVA: On s'est battues avec ma\npartenaire, mais on a perdu…\pC'est décourageant…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "EVA: Tu n'as qu'un seul POKéMON?\nAlors on ne va pas pouvoir s'affronter.\pOn veut combattre en 2 contre 2.$"

Route117_Text_MelinaIntro:
	.string "C'est sympa, hein? Se battre tout en\nregardant les jolies fleurs!$"

Route117_Text_MelinaDefeat:
	.string "Oh, c'était très impressionnant!$"

Route117_Text_MelinaPostBattle:
	.string "Rien de mieux qu'un petit jogging en\npleine nature.$"

Route117_Text_BrandiIntro:
	.string "Laisse-moi te montrer la force cachée\ndes POKéMON PSY!$"

Route117_Text_BrandiDefeat:
	.string "Etonnant!$"

Route117_Text_BrandiPostBattle:
	.string "Les POKéMON PSY sont complexes.\nTu devrais essayer d'en attraper.$"

Route117_Text_AishaIntro:
	.string "Se concentrer sur la victoire!\nC'est le secret d'un combat réussi!$"

Route117_Text_AishaDefeat:
	.string "Je ne me morfonds jamais en cas de\ndéfaite… Je retourne m'entraîner!$"

Route117_Text_AishaPostBattle:
	.string "Si tu penses trop à la défaite, tu as\nplus de chances de perdre.$"

Route118_Text_RoseIntro:
	.string "Le parfum des fleurs a un pouvoir\nmagique. Il purifie le corps et l'esprit.$"

Route118_Text_RoseDefeat:
	.string "Oh là là!\nOn dirait bien que j'ai perdu.$"

Route118_Text_RosePostBattle:
	.string "Les fleurs, les POKéMON…\nJ'aime tout ce qui sent bon.\pTout ce qui pue…\nC'est pas pour moi!$"

Route118_Text_RoseRegister:
	.string "Sniff… Cette odeur…\nC'est un POKéNAV!\pTu veux bien qu'on échange nos\nnuméros?$"

Route118_Text_RoseRematchIntro:
	.string "Est-ce ce doux parfum qui t'a fait\nvenir ici?$"

Route118_Text_RoseRematchDefeat:
	.string "Le pouvoir du parfum…\nÇa n'a pas changé grand-chose.$"

Route118_Text_RosePostRematch:
	.string "Si tu sais bien utiliser un doux parfum,\ntu peux attirer les POKéMON avec.$"

Route118_Text_PerryIntro:
	.string "Les POKéMON OISEAU qui volent\navec grâce dans le ciel,\lce sont les meilleurs!$"

Route118_Text_PerryDefeat:
	.string "Arrg… Je me suis fait écraser…$"

Route118_Text_PerryPostBattle:
	.string "Tu es vraiment balèze! Je vais devoir\nperfectionner mon entraînement.$"

Route118_Text_ChesterIntro:
	.string "Prenez votre envol!\nMes POKéMON OISEAU!$"

Route118_Text_ChesterDefeat:
	.string "Ils ont effectivement pris leur envol…$"

Route118_Text_ChesterPostBattle:
	.string "S'ils étaient plus forts, ils pourraient\nvoler plus librement…$"

Route118_Text_BarnyIntro:
	.string "Je suis PECHEUR, mais aussi DRESSEUR.\nJ'élève les POKéMON que j'attrape.$"

Route118_Text_BarnyDefeat:
	.string "Je croyais pourtant que je m'entraînais\ncorrectement…$"

Route118_Text_BarnyPostBattle:
	.string "Je ne pourrai pas gagner si j'entraîne\nmes POKéMON tout en pêchant…\pÇa voudrait dire que je ne fais les\nchoses qu'à moitié?$"

Route118_Text_WadeIntro:
	.string "Pour les PECHEURS, le matériel est\nla clé de tout.\pMais l'essentiel pour les DRESSEURS,\nce sont les POKéMON et le cœur!$"

Route118_Text_WadeDefeat:
	.string "Ai-je été touché en plein cœur?$"

Route118_Text_WadePostBattle:
	.string "Si tu y penses, la pêche c'est comme un\ncombat entre un PECHEUR et un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Laisse ma mélodie bercer ton âme!$"

Route118_Text_DaltonDefeat:
	.string "La, lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Une guitare électrique, ça ne fait pas\ntoujours un bruit terrible…\pOn peut pincer les cordes de façon à en\ntirer cette émouvante mélodie…$"

Route118_Text_DaltonRegister:
	.string "Tu viendras écouter mes prochaines\ncompositions?$"

Route118_Text_DaltonRematchIntro:
	.string "La mélodie de mes POKéMON et moi…\nLaisse-nous la faire toucher ton âme.$"

Route118_Text_DaltonRematchDefeat:
	.string "La, lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quand je joue, mes émotions peuvent te\ntoucher grâce à ma guitare électrique…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\nPOKéMON 1, 2, et 3!$"

Route118_Text_DeandreDefeat:
	.string "POKéMON 1, 2, et 3?\nEst-ce que ça va?$"

Route118_Text_DeandrePostBattle:
	.string "C'est cool d'avoir toute une équipe\nde POKéMON pour se battre!\pTu peux faire comme moi, j't'en\nvoudrai pas!$"

Route119_Text_BrentIntro:
	.string "On est le CLUB COPIE!\nOn COPIE ce que tu fais!$"

Route119_Text_BrentDefeat:
	.string "Oups!\nOn a perdu!$"

Route119_Text_BrentPostBattle:
	.string "Qu'y a-t-il de drôle à copier les\nautres?\pPffffff…\nTu ne comprendras jamais…$"

Route119_Text_DonaldIntro:
	.string "Ah, on se rencontre enfin! Mes POKéMON\nINSECTE vont te tenir compagnie!$"

Route119_Text_DonaldDefeat:
	.string "J'aurais préféré ne pas te rencontrer…$"

Route119_Text_DonaldPostBattle:
	.string "Je voudrais te copier encore un peu.\nTu peux te dépêcher de bouger?$"

Route119_Text_TaylorIntro:
	.string "Si tu avances, on avance.\nSi tu tournes à droite, on tourne aussi.$"

Route119_Text_TaylorDefeat:
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_TaylorPostBattle:
	.string "Je ne peux pas copier ta victoire.\nC'est tout bonnement impossible…\lÇa me met en pétard…$"

Route119_Text_DougIntro:
	.string "Hé, t'as finalement réussi à m'attraper!\nMais tu voulais peut-être m'éviter?$"

Route119_Text_DougDefeat:
	.string "Ouuuuh, c'était un beau combat!$"

Route119_Text_DougPostBattle:
	.string "On est le CLUB COPIE!\nJ'espère que tu aimes ce qu'on fait.$"

Route119_Text_GregIntro:
	.string "Tu ne sais pas qui je suis, hein?\pMais je ne te connais pas non plus.\nAlors on va se battre!$"

Route119_Text_GregDefeat:
	.string "T'es plutôt balèze!$"

Route119_Text_GregPostBattle:
	.string "On copiera chacun de tes mouvements\njusqu'à ce que tu partes ailleurs.$"

Route119_Text_KentIntro:
	.string "Le CLUB COPIE a été fondé par des\npersonnes aimant COPIER les autres.\pA la seconde même où on se rencontre,\nun combat débute!$"

Route119_Text_KentDefeat:
	.string "J'abandonne!$"

Route119_Text_KentPostBattle:
	.string "Veux-tu rejoindre notre CLUB COPIE?$"

Route119_Text_JacksonIntro:
	.string "Qui sait toujours comment faire pour\nsurvivre?\pNous, les POKéMON RANGERS!$"

Route119_Text_JacksonDefeat:
	.string "Je ne connais pas suffisamment de\nchoses sur les POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Fuir la civilisation et éveiller\nl'instinct sauvage qui est en nous!\pC'est notre devise!$"

Route119_Text_JacksonRegister:
	.string "J'espère qu'on s'affrontera de nouveau\net que tu ne te moqueras pas de mon\lmanque de connaissances!$"

Route119_Text_JacksonRematchIntro:
	.string "Je vais faire renaître mon instinct\nsauvage en restant avec les POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Toujours autant de force!$"

Route119_Text_JacksonPostRematch:
	.string "Crois en tes POKéMON.\nCrois en toi.\pLe reste se fera tout seul.$"

Route119_Text_CatherineIntro:
	.string "Hé, regarde-toi.\pPour quelqu'un qui part à l'aventure, tu\nvoyages drôlement léger.$"

Route119_Text_CatherineDefeat:
	.string "Les accidents se produisent quand on\nne s'y attend pas!$"

Route119_Text_CatherinePostBattle:
	.string "Tu voyages léger, mais tu as tout ce\nqu'il te faut.\pTu es mentalement et physiquement\nau top.$"

Route119_Text_CatherineRegister:
	.string "Est-ce que tu as un POKéNAV?\nC'est un outil indispensable pour\lun DRESSEUR.\pOh, tu en as un!\nEnregistrons-nous alors!$"

Route119_Text_CatherineRematchIntro:
	.string "Comment se passe ton voyage avec\ntes POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Il me manque quelque chose…$"

Route119_Text_CatherinePostRematch:
	.string "En tant que DRESSEUR, tu as\nconfiance en tes POKéMON et eux,\lréciproquement, ont confiance en toi.$"

Route119_Text_HughIntro:
	.string "Le ciel, si vaste, tient une grande\npromesse!\pRien n'est aussi intense que de voler!$"

Route119_Text_HughDefeat:
	.string "A terre et hors combat!$"

Route119_Text_HughPostBattle:
	.string "Mon POKéMON OISEAU m'a permis de\nréaliser mon rêve. Je peux voler!$"

Route119_Text_PhilIntro:
	.string "Je vais te montrer mon vrai potentiel,\nainsi que celui de mes POKéMON OISEAU.$"

Route119_Text_PhilDefeat:
	.string "Nous avons manqué de potentiel…$"

Route119_Text_PhilPostBattle:
	.string "Tout petit déjà, j'admirais les\nPOKéMON OISEAU…$"

Route119_Text_YasuIntro:
	.string "Me cacher dans l'ombre et vivre dans\nl'obscurité… Tel est mon destin.\pJ'émerge pour te défier!$"

Route119_Text_YasuDefeat:
	.string "J'admets la défaite!$"

Route119_Text_YasuPostBattle:
	.string "Les perdants se retirent discrètement\npour retourner dans l'ombre.\lÇa aussi, c'est le destin…$"

Route119_Text_TakashiIntro:
	.string "Quand on ne se méfie pas, on prend\nle risque de souffrir!$"

Route119_Text_TakashiDefeat:
	.string "Ta force est surprenante!$"

Route119_Text_TakashiPostBattle:
	.string "Mon attaque surprise a échoué…$"

Route119_Text_HideoIntro:
	.string "L'arbre cache la forêt!$"

Route119_Text_HideoDefeat:
	.string "Je m'incline devant ta supériorité.$"

Route119_Text_HideoPostBattle:
	.string "L'arbre cache la forêt!\nUn POKéMON cache un autre POKéMON!\pIl n'y a pas de sens caché derrière ça.$"

Route119_Text_ChrisIntro:
	.string "Tu m'as parlé…\nAlors tu veux m'affronter!\pPas de problème! Je vais tester le\nPOKéMON que j'ai attrapé en SURFANT!$"

Route119_Text_ChrisDefeat:
	.string "Je n'ai pas la moindre idée de ce qu'il\nfaut pour gagner.$"

Route119_Text_ChrisPostBattle:
	.string "Monter sur mon POKéMON pour faire\ndu SURF…\pEt ensuite, pêcher sur son dos…\pC'est un plaisir indescriptible!$"

Route119_Text_FabianIntro:
	.string "Je vais exploser mon ampli!\nLa victoire est à moi!\lÇa va vibrer, tu vas voir!$"

Route119_Text_FabianDefeat:
	.string "Tu m'as montré qui est le boss,\nje repars avec mes bosses!$"

Route119_Text_FabianPostBattle:
	.string "J'ai débranché mon ampli.\nLaisse-moi seul avec ma défaite.$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\nJ'adore me battre contre de\ljeunes DRESSEURS!$"

Route119_Text_DaytonDefeat:
	.string "T'es plutôt incroyable!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\nJe vais continuer de m'entraîner!$"

Route119_Text_RachelIntro:
	.string "Où que je sois et quoi que je fasse,\nje garde toujours mon parasol.$"

Route119_Text_RachelDefeat:
	.string "Mais…\nC'est pas juste!$"

Route119_Text_RachelPostBattle:
	.string "Tu me demandes si mon parasol\nn'est pas trop lourd?\pTon SAC est rempli de choses bien\nplus lourdes que ce que je porte.$"

Route120_Text_ColinIntro:
	.string "Connais-tu une capacité pouvant\ntoucher un POKéMON en vol?$"

Route120_Text_ColinDefeat:
	.string "Tu es au-dessus de moi!$"

Route120_Text_ColinPostBattle:
	.string "La capacité VOL est très pratique, tu\nne trouves pas?\pPresque aucune capacité ne peut\natteindre un POKéMON en vol.$"

Route120_Text_RobertIntro:
	.string "Mon POKéMON est fort!\nEt les tiens?$"

Route120_Text_RobertDefeat:
	.string "Tes POKéMON étaient plus forts…$"

Route120_Text_RobertPostBattle:
	.string "Si un POKéMON progresse avec\nrégularité, on peut compter dessus.$"

Route120_Text_RobertRegister:
	.string "Je suis sûr que tu vas progresser.\nJe voudrais t'enregistrer dans mon\lPOKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Si un POKéMON progresse avec\nrégularité, on peut compter dessus.$"

Route120_Text_RobertRematchDefeat:
	.string "Tes POKéMON sont vraiment très forts.$"

Route120_Text_RobertPostRematch:
	.string "Mes POKéMON deviennent plus forts.\nMoi aussi je dois devenir plus fort!$"

Route120_Text_LorenzoIntro:
	.string "Je vais vérifier si tes POKéMON sont\nprêts à prendre le grand air.$"

Route120_Text_LorenzoDefeat:
	.string "Avec des POKéMON aussi forts que ça,\ntu ne risques pas d'avoir besoin d'aide!$"

Route120_Text_LorenzoPostBattle:
	.string "Voyager au gré de ses envies avec ses\nPOKéMON…\pC'est le privilège d'être DRESSEUR.$"

Route120_Text_JennaIntro:
	.string "Comment te sens-tu? Si tu n'es pas\nen pleine forme, ça peut être difficile\ldans les moments critiques.$"

Route120_Text_JennaDefeat:
	.string "Je suis en pleine forme, et pourtant…$"

Route120_Text_JennaPostBattle:
	.string "J'ai l'habitude de faire de l'exercice.\nJe cours toujours avec mes POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n… … … … … …\lTu veux te battre?$"

Route120_Text_JeffreyDefeat:
	.string "Vaincu…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n… … … … … …\lJe vais essayer de faire mieux…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n… … … … … …\lTu as un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n… … … … … …\lTu veux encore te battre?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\nJ'ai encore perdu…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n… … … … … …\lJe vais essayer de faire mieux…\lPour mes précieux POKéMON INSECTE…$"

Route120_Text_JenniferIntro:
	.string "Les POKéMON ont de nombreuses\ncapacités spéciales. Pour devenir un\ldes meilleurs DRESSEURS, renseigne-toi.$"

Route120_Text_JenniferDefeat:
	.string "T'es manifestement en pleine réflexion.$"

Route120_Text_JenniferPostBattle:
	.string "Les capacités spéciales des POKéMON\nchangeront leur façon de se battre.$"

Route120_Text_ChipIntro:
	.string "Qui pourrais-tu bien être?\pPeut-être es-tu à la recherche des\nruines antiques qui, selon la légende,\lpourraient exister?$"

Route120_Text_ChipDefeat:
	.string "Quelle infâme mésaventure…$"

Route120_Text_ChipPostBattle:
	.string "Ce rocher géant… J'aimerais croire qu'il\nrenferme des ruines antiques. Mais il\ln'y a pas d'entrée.$"

Route120_Text_ClarissaIntro:
	.string "Pourquoi j'ai ce parasol?\pJe te le dirai si tu réussis à me battre.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasol ne permet pas d'éviter les\nattaques de POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Je ne pense pas que la lumière intense\nsoit bénéfique à mes POKéMON.\lAlors je les protège avec mon parasol.$"

Route120_Text_AngelicaIntro:
	.string "Mon POKéMON, mon parasol et moi…\pSi l'un d'entre nous manque, la\nreprésentation de la beauté est ternie.$"

Route120_Text_AngelicaDefeat:
	.string "Tu as complètement terni ma beauté…$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasol, ça ne t'irait pas du tout.\nÇa ne ferait que t'encombrer…$"

Route120_Text_KeigoIntro:
	.string "Je vais adopter les mouvements des\nPOKéMON et créer des techniques ninja.$"

Route120_Text_KeigoDefeat:
	.string "La création de nouvelles techniques\nninja n'est qu'un rêve…$"

Route120_Text_KeigoPostBattle:
	.string "J'aurais peut-être dû suivre les\nenseignements d'un maître ninja.$"

Route120_Text_RileyIntro:
	.string "Nous, les ninjas, on se dissimule\nderrière nos capes de camouflage.\pJe parie que tu ne savais pas où\nj'étais!$"

Route120_Text_RileyDefeat:
	.string "J'ai perdu!\nJe vais devoir dissimuler ma honte!$"

Route120_Text_RileyPostBattle:
	.string "Nos capes de camouflage sont toutes\nfaites à la main.$"

Route120_Text_CallieIntro:
	.string "Si tu ne fais pas attention, tu pourrais\nte faire mal!$"

Route120_Text_CallieDefeat:
	.string "Ouch!\nC'est moi qui me suis fait mal!$"

Route120_Text_CalliePostBattle:
	.string "Je me demande… Dois-je faire évoluer\nmes POKéMON?\pJe les trouve mignons comme ils sont.$"

Route120_Text_LeonelIntro:
	.string "Ton équipe de POKéMON…\nEst-ce que tu as d'autres types?$"

Route120_Text_LeonelDefeat:
	.string "J'ai bien compris ta façon de te battre!$"

Route120_Text_LeonelPostBattle:
	.string "Rien de mieux que de se battre avec\nses POKéMON préférés!$"

Route121_Text_VanessaIntro:
	.string "Tu veux jouer avec mon adorable\nPOKéMON?$"

Route121_Text_VanessaDefeat:
	.string "Ce n'est pas ce que je voulais dire!$"

Route121_Text_VanessaPostBattle:
	.string "Je vais à un CONCOURS à NENUCRIQUE.\pMon POKéMON ne devrait avoir aucun\nproblème à se distinguer en MASTER.$"

Route121_Text_WalterIntro:
	.string "Avec les POKéMON, j'ai voyagé aux\nquatre coins du monde.\pTu dois te dire que je suis confiant\nen ce qui concerne mes compétences.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien joué!$"

Route121_Text_WalterPostBattle:
	.string "J'aimerais bien refaire le tour du globe!$"

Route121_Text_WalterRegister:
	.string "Les prouesses de tes POKéMON sont\nremarquables. Permets-moi de\lt'enregistrer dans mon POKéNAV.$"

Route121_Text_WalterRematchIntro:
	.string "Avec les POKéMON, j'ai voyagé aux\nquatre coins du monde.\pTu dois te dire que je suis confiant\nen ce qui concerne mes compétences.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien joué!$"

Route121_Text_WalterPostRematch:
	.string "Tes POKéMON et toi…\pLa prouesse que vous avez accomplie\nva être reconnue par-delà les mers.$"

Route121_Text_TammyIntro:
	.string "Dans ce monde, il existe des pouvoirs\nqui dépassent notre entendement…$"

Route121_Text_TammyDefeat:
	.string "J'ai perdu…$"

Route121_Text_TammyPostBattle:
	.string "MONT MEMORIA…\nLà, un mystérieux pouvoir est\len action…$"

Route121_Text_KateIntro:
	.string "VIVI: Ensemble, on ne connaît pas la\npeur! Tu vas voir comme on est fortes!$"

Route121_Text_KateDefeat:
	.string "VIVI: Je vais tout balayer devant\nma petite protégée…$"

Route121_Text_KatePostBattle:
	.string "VIVI: Quand quelqu'un a confiance\nen moi, je me dois de faire preuve d'un\lsang-froid irréprochable…$"

Route121_Text_KateNotEnoughMons:
	.string "VIVI: Si tu n'as qu'un seul POKéMON,\non ne peut pas s'affronter.\pCe serait de la folie!$"

Route121_Text_JoyIntro:
	.string "BEA: Ensemble, on ne connaît pas la\npeur. Tu vas voir comme on est fortes!$"

Route121_Text_JoyDefeat:
	.string "BEA: Pardonne-moi, VIVI!$"

Route121_Text_JoyPostBattle:
	.string "BEA: Il va falloir qu'on s'entraîne\nencore avec VIVI, mon mentor.$"

Route121_Text_JoyNotEnoughMons:
	.string "BEA: Il te faut au moins deux\nPOKéMON pour pouvoir nous affronter!$"

Route121_Text_JessicaIntro:
	.string "Stop! Regarde mes POKéMON!\nDe vrais trésors!$"

Route121_Text_JessicaDefeat:
	.string "Oh, comment oses-tu!\nNe prends pas ça au sérieux!$"

Route121_Text_JessicaPostBattle:
	.string "Je vais peut-être aller attraper\nd'autres POKéMON au PARC SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Je ne me suis pas donnée à fond cette\nfois! Mais ça ne sera pas la même\lchose la prochaine fois!$"

Route121_Text_JessicaRematchIntro:
	.string "Mes précieux POKéMON ont grandi!\nRegarde!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, comment oses-tu!\nTu ne vas quand même pas t'énerver!$"

Route121_Text_JessicaPostRematch:
	.string "Je vais peut-être aller attraper\nd'autres POKéMON au PARC SAFARI.$"

Route121_Text_CristinIntro:
	.string "J'ai pour habitude de battre cinq\nDRESSEURS par jour…\pEt devine quoi! Tu es le numéro cinq!$"

Route121_Text_CristinDefeat:
	.string "Non!\nTu es ignoble!$"

Route121_Text_CristinPostBattle:
	.string "Je ne pensais pas perdre aussi\nfacilement…\pMais je gagnerai la prochaine fois!$"

Route121_Text_CristinRegister:
	.string "Tu m'as humiliée!\nJe ne t'oublierai pas…\lFais-moi voir ton POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "J'ai pour nouvelle habitude de battre\ndix DRESSEURS par jour…\pEt devine quoi! Tu es le numéro dix!$"

Route121_Text_CristinRematchDefeat:
	.string "Attends! Ça va pas!\nJe demande une revanche!$"

Route121_Text_CristinPostRematch:
	.string "Tu es le premier adversaire que je\nne peux pas battre… Sniff…\pJe ne peux pas croire que ça m'arrive…$"

Route121_Text_CaleIntro:
	.string "Tu vois pas que j'ai les mains pleines?\pEt malgré ça, tu insistes pour qu'on\nse batte!$"

Route121_Text_CaleDefeat:
	.string "Evidemment que j'ai perdu!\nJ'ai les deux mains prises!$"

Route121_Text_CalePostBattle:
	.string "J'ai acheté trop d'articles au CENTRE\nCOMMERCIAL de NENUCRIQUE.\pIl est juste un peu plus loin.\nSi seulement j'avais un SAC comme\lle tien!$"

Route121_Text_MylesIntro:
	.string "Pour moi, rien de mieux que de découvrir\nles POKéMON des autres!$"

Route121_Text_MylesDefeat:
	.string "Super génial!$"

Route121_Text_MylesPostBattle:
	.string "Ils sont super tes POKéMON!\nComment est-ce que tu les dresses?$"

Route121_Text_PatIntro:
	.string "Je veux que tout le monde voie les\nPOKéMON que j'ai dressés!$"

Route121_Text_PatDefeat:
	.string "Waouh!\nSpectaculaire!$"

Route121_Text_PatPostBattle:
	.string "Je dresse chaque POKéMON avec le\nmême soin et la même attention.\lJe ne favorise pas ceux que je préfère!$"

Route121_Text_MarcelIntro:
	.string "Mes POKéMON n'ont jamais connu la\ndéfaite! Encore une victoire et je les\linscris à un CONCOURS!$"

Route121_Text_MarcelDefeat:
	.string "Hein? Qu'est-ce qui s'est passé?$"

Route121_Text_MarcelPostBattle:
	.string "Je devrais peut-être les entraîner un\npeu plus avant de les inscrire à\lun CONCOURS…$"

Route123_Text_WendyIntro:
	.string "Tu veux connaître ta force?\nJe vais te faire passer le test!$"

Route123_Text_WendyDefeat:
	.string "Tu as réussi haut la main!$"

Route123_Text_WendyPostBattle:
	.string "Pour l'emporter même sur moi…\nIl faut que ta force soit grandiose!$"

Route123_Text_BraxtonIntro:
	.string "Tu sembles avoir une belle collection\nde BADGES D'ARENES.\pLaisse-moi voir si tu es réellement\ndigne de tous ces BADGES.$"

Route123_Text_BraxtonDefeat:
	.string "Bon, très bien, tu en es digne!$"

Route123_Text_BraxtonPostBattle:
	.string "Tu as prouvé la véritable valeur\nde tes BADGES dans ce combat!$"

Route123_Text_VioletIntro:
	.string "On dit que les bons moments sont\nriches en agréables parfums.$"

Route123_Text_VioletDefeat:
	.string "Oh…\nJe sens l'âpre odeur de la souffrance…$"

Route123_Text_VioletPostBattle:
	.string "Le jardin du MAITRE DES BAIES dégage\nde multiples parfums édifiants.$"

Route123_Text_CameronIntro:
	.string "Etre médium est une question de\nvolonté.\pJe me suis promis de ne jamais perdre.\nC'est ce qui fait ma force!$"

Route123_Text_CameronDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostBattle:
	.string "Etre médium requiert de la volonté.\nJe ne pensais pas perdre contre toi…$"

Route123_Text_CameronRegister:
	.string "Je vois… Je vois…\nJe vois que nous allons nous battre\lde nouveau!\pMais je ne peux pas voir si je vaincrai…\nMontre-moi ton POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Je me suis convaincu que je n'allais\nplus perdre. Ça me donne de la force!$"

Route123_Text_CameronRematchDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostRematch:
	.string "Je devrais m'entraîner au MONT MEMORIA.\nSinon, je ne vais jamais te battre…$"

Route123_Text_JackiIntro:
	.string "Ne te réjouis pas trop si tes POKéMON\ndéveloppent des pouvoirs psychiques.\pIl faut que tu les perfectionnes si tu\nveux vraiment pouvoir t'en servir.$"

Route123_Text_JackiDefeat:
	.string "Ecrasée!$"

Route123_Text_JackiPostBattle:
	.string "On a tous des pouvoirs psychiques.\nOn a juste oublié comment les utiliser.$"

Route123_Text_JackiRegister:
	.string "J'aimerais te rencontrer de nouveau.\nTu es d'accord?$"

Route123_Text_JackiRematchIntro:
	.string "As-tu éveillé les pouvoirs psychiques\nqui sommeillent en toi?$"

Route123_Text_JackiRematchDefeat:
	.string "Renversant!$"

Route123_Text_JackiPostRematch:
	.string "Le pouvoir que tu as sur tes POKéMON…\nÇa pourrait être un pouvoir psychique…$"

Route123_Text_MiuIntro:
	.string "MIU: Salut, DRESSEUR! J'espère que\ntes POKéMON ne pleurent pas quand\lils perdent.$"

Route123_Text_MiuDefeat:
	.string "MIU: Ouin, on a perdu.$"

Route123_Text_MiuPostBattle:
	.string "MIU: DRESSEUR, si tes POKéMON\nsont forts, c'est grâce à votre amitié.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: C'est pas marrant de se\nbattre si t'as pas deux POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: OK! On va battre les POKéMON\nde ce DRESSEUR!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Ouin, on a perdu.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Pourquoi es-tu si robuste?\nOn n'avait jamais perdu avant.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: C'est pas marrant de se\nbattre si t'as pas deux POKéMON.$"

Route123_Text_KindraIntro:
	.string "MONT MEMORIA…\nIci reposent les âmes des POKéMON…\pTon POKéMON veut-il se reposer?$"

Route123_Text_KindraDefeat:
	.string "Débordant de vitalité…$"

Route123_Text_KindraPostBattle:
	.string "MONT MEMORIA…\nIci reposent les âmes des POKéMON…\pUn pouvoir apaisant les esprits doit\nse dégager de cet endroit…$"

Route123_Text_FernandoIntro:
	.string "Je vais m'occuper de toi tout en\njouant mon solo de guitare!$"

Route123_Text_FernandoDefeat:
	.string "Hé, pas si vite!\nJ'ai même pas fini l'intro!$"

Route123_Text_FernandoPostBattle:
	.string "T'as le rock dans la peau. J'aimerais\nécrire un morceau sur toi.$"

Route123_Text_FernandoRegister:
	.string "La prochaine fois, écoute au moins\njusqu'au bout, OK?$"

Route123_Text_FernandoRematchIntro:
	.string "Je sens que cette fois sera la bonne!\nJe vais gagner avant même la fin de\lma chanson!$"

Route123_Text_FernandoRematchDefeat:
	.string "Attends un peu!\nTu veux vraiment pas entendre\lle refrain?$"

Route123_Text_FernandoPostRematch:
	.string "Ma musique était censée te captiver\nau point de te faire perdre.$"

Route123_Text_DavisIntro:
	.string "C'est mon formidable POKéMON INSECTE!\nC'est mon frangin qui me l'a donné!$"

Route123_Text_DavisDefeat:
	.string "Waah!\nQuelle méchanceté!$"

Route123_Text_DavisPostBattle:
	.string "Ne dis pas à mon frère que j'ai perdu.\nCe sera notre secret!$"

Route123_Text_JazmynIntro:
	.string "Ça me donnera confiance en moi de\nbattre quelqu'un comme toi!$"

Route123_Text_JazmynDefeat:
	.string "Où est passée ma confiance?$"

Route123_Text_JazmynPostBattle:
	.string "On dit qu'il ne faut pas juger les gens\nsur leur apparence.\pMais la plupart du temps, ça marche!$"

Route123_Text_FrederickIntro:
	.string "Salut jeune DRESSEUR!\nT'as un peu de temps à perdre?$"

Route123_Text_FrederickDefeat:
	.string "Un DRESSEUR plein de promesses!\nVoilà pour toi!$"

Route123_Text_FrederickPostBattle:
	.string "Comment? L'argent de la victoire ne\nte suffit pas?$"

Route123_Text_AlbertoIntro:
	.string "Je dois t'avouer que les POKéMON OISEAU\nsont mon obsession!\pLes oiseaux sont vraiment cool!\nCe sont simplement les meilleurs!$"

Route123_Text_AlbertoDefeat:
	.string "Même dans la défaite, les POKéMON\nOISEAU arrivent à rester cool!$"

Route123_Text_AlbertoPostBattle:
	.string "Je collectionne les plumes que les\nPOKéMON OISEAU perdent\lpendant leurs combats.\pJ'ai l'intention d'en faire un chapeau\nune fois que j'en aurai suffisamment.$"

Route123_Text_EdIntro:
	.string "Quand il n'y a pas de DRESSEUR à\naffronter, je laisse mes POKéMON se\pbattre entre eux et je profite du\nspectacle.$"

Route123_Text_EdDefeat:
	.string "Plutôt pas mal tes POKéMON…$"

Route123_Text_EdPostBattle:
	.string "Héhé, je vais copier tes techniques de\ncombat, je suis sûr que ça me rendra\lencore plus fort.$"

Route123_Text_JonasIntro:
	.string "J'ai tendu un piège, et un DRESSEUR est\ntombé dedans!$"

Route123_Text_JonasDefeat:
	.string "Si je ne gagne pas, c'est tout de suite\nmoins drôle de jouer au ninja!$"

Route123_Text_JonasPostBattle:
	.string "La prochaine fois, je tendrai un piège\nà quelqu'un de moins fort!$"

Route123_Text_KayleyIntro:
	.string "Je viens d'acheter ce parasol.\nAvec ça, je suis deux fois plus belle!$"

Route123_Text_KayleyDefeat:
	.string "Tu es au moins cinq fois plus\nredoutable que moi!$"

Route123_Text_KayleyPostBattle:
	.string "Bien utiliser les accessoires est\nle secret pour bien s'habiller!$"

Route124_Text_SpencerIntro:
	.string "Hé, tu ne retrouves pas ta route?\pSi tu réussis à battre mes POKéMON, je\nte servirai de guide.$"

Route124_Text_SpencerDefeat:
	.string "Ce combat m'a fait perdre le nord!$"

Route124_Text_SpencerPostBattle:
	.string "De nombreuses personnes perdent\nleurs repères en mer.\pSi c'est ton cas, tu n'as qu'à te repérer\nsur la CARTE du POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hum! Plutôt que de nager, tu avances\nsur le dos d'un POKéMON…\pJe t'envie!$"

Route124_Text_RolandDefeat:
	.string "Oh!\nJe ne peux pas…$"

Route124_Text_RolandPostBattle:
	.string "Je suis en train d'attraper froid… Je\nsuis resté trop longtemps dans l'eau…\pJ'aimerais être sur un POKéMON aussi…$"

Route124_Text_JennyIntro:
	.string "Si tu restes là à flotter en mer, les\nPOKéMON vont venir jouer avec toi.$"

Route124_Text_JennyDefeat:
	.string "Oh, non!\nJ'ai lancé le défi et j'ai perdu…$"

Route124_Text_JennyPostBattle:
	.string "En mer, j'ai remarqué que des POKéMON\nattaquent et d'autres regardent.\pJe suppose que chaque POKéMON\na sa propre personnalité.$"

Route124_Text_JennyRegister:
	.string "C'est peut-être un caprice, mais\nj'aimerais beaucoup que tu\lm'enregistres sur ton POKéNAV!$"

Route124_Text_JennyRematchIntro:
	.string "Si tu ne fais que flotter en mer, les\nDRESSEURS vont te défier!$"

Route124_Text_JennyRematchDefeat:
	.string "C'est curieux…\nJ'ai encore perdu…$"

Route124_Text_JennyPostRematch:
	.string "Ça n'a rien à voir, mais je vais aller\nvisiter la MAISON DES PIEGES.$"

Route124_Text_GraceIntro:
	.string "Je commence à en avoir marre de nager…\nQu'est-ce que tu dirais d'un combat?$"

Route124_Text_GraceDefeat:
	.string "Je ne t'imaginais pas aussi robuste!$"

Route124_Text_GracePostBattle:
	.string "Ce sont tous tes efforts qui ont\ndû te donner autant de force.$"

Route124_Text_ChadIntro:
	.string "Pfffff… J'ai plongé dans les abîmes de\nla mer pour me mettre bien à l'abri.\pJ'excelle dans le sondage des\nprofondeurs!$"

Route124_Text_ChadDefeat:
	.string "Glou, glou, glou…\nJe coule…$"

Route124_Text_ChadPostBattle:
	.string "Je tiens de source sûre qu'il y a par\nici un endroit où l'on peut faire de la\lPLONGEE.\pJe ne résiste pas à l'envie de retourner\ndans les profondeurs…$"

Route124_Text_LilaIntro:
	.string "RITA: Soupir…\pMe voilà en mer, mais avec qui je suis?\nMon petit frère!\pBattons-nous, que je ne continue pas\nà m'appesantir là-dessus!$"

Route124_Text_LilaDefeat:
	.string "RITA: SAM! C'est de ta faute si on\na perdu! Ça se paiera!$"

Route124_Text_LilaPostBattle:
	.string "RITA: Soupir…\pSi seulement j'étais avec un charmant\npetit ami et pas avec mon petit frère…$"

Route124_Text_LilaNotEnoughMons:
	.string "RITA: Tu comptes nous affronter?\nSeulement si tu as deux POKéMON.$"

Route124_Text_RoyIntro:
	.string "SAM: Ma sœur est forte aux POKéMON.\pViens pas te plaindre si tu perds!$"

Route124_Text_RoyDefeat:
	.string "SAM: Ouin…\nMa grande sœur va m'incendier…$"

Route124_Text_RoyPostBattle:
	.string "SAM: Ma grande sœur est vraiment\nflippante quand elle s'énerve.\pC'est pour ça qu'elle n'a pas de petit\nami.$"

Route124_Text_LilaRoyRegister:
	.string "SAM: Tu te battras encore avec nous?\nMais vas-y mollo la prochaine fois, OK?$"

Route124_Text_RoyNotEnoughMons:
	.string "SAM: Tu veux nous affronter?\nAlors ramène d'autres POKéMON.$"

Route124_Text_LilaRematchIntro:
	.string "RITA: J'ai vraiment pas de chance…\pMe voilà en mer, mais avec qui je suis?\nMon petit frère!\pSalut, ça faisait longtemps. Qu'on se\nbatte! Ça me changera les idées!$"

Route124_Text_LilaRematchDefeat:
	.string "RITA: SAM!\nC'est de ta faute si on a perdu!\pOn va faire une séance d'entraînement!$"

Route124_Text_LilaPostRematch:
	.string "RITA: J'ai vraiment pas de chance…\pAvec un petit ami, on battrait tout le\nmonde avec nos tendres combinaisons…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "RITA: Tu comptes nous affronter? \nSeulement si tu as deux POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "SAM: Il faut qu'on gagne!\nJe vais tout donner!$"

Route124_Text_RoyRematchDefeat:
	.string "SAM: Ouin…\nMa grande sœur va encore m'incendier.$"

Route124_Text_RoyPostRematch:
	.string "SAM: Ma grande sœur est vraiment\nflippante quand elle s'énerve.\pElle va me faire travailler très dur\navec les POKéMON…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "SAM: Tu veux nous affronter?\nAlors ramène d'autres POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Je me demande bien ce que je suis\nvenu faire ici.\pC'est pathétique, y'a pas d'autre mot.$"

Route124_Text_DeclanDefeat:
	.string "Je me suis retrouvé noyé sous\nles coups.$"

Route124_Text_DeclanPostBattle:
	.string "Je devrais aller parler un peu avec les\nNAGEUSES du coin.$"

Route124_Text_IsabellaIntro:
	.string "Je ne peux pas perdre contre un\nDRESSEUR qui utilise SURF pour\lse déplacer!$"

Route124_Text_IsabellaDefeat:
	.string "C'est de la sueur que j'ai dans les\nyeux, pas des larmes, je t'assure!$"

Route124_Text_IsabellaPostBattle:
	.string "On trouve de très jolies choses au\nfond de l'eau par ici!$"

Route125_Text_NolenIntro:
	.string "Je savais que tu arrivais, alors je me\nsuis attardé pour te rencontrer!$"

Route125_Text_NolenDefeat:
	.string "Je me rends!$"

Route125_Text_NolenPostBattle:
	.string "Le son se propage plus vite dans l'eau\nque dans l'air.$"

Route125_Text_StanIntro:
	.string "Hé, toi là-bas!\nViens voir mon adorable POKéMON!$"

Route125_Text_StanDefeat:
	.string "J'ai carrément pataugé…$"

Route125_Text_StanPostBattle:
	.string "Le charme d'HYPOTREMPE m'a attiré\net j'ai commencé à nager aussi.$"

Route125_Text_TanyaIntro:
	.string "J'en ai marre de nager.\nÇa te dirait un combat contre moi?$"

Route125_Text_TanyaDefeat:
	.string "T'es vraiment trop!$"

Route125_Text_TanyaPostBattle:
	.string "Fffou…\nC'est par où ALGATIA?$"

Route125_Text_SharonIntro:
	.string "Comment! Tu voudrais te battre contre\nle POKéMON EAU que j'ai élevé?$"

Route125_Text_SharonDefeat:
	.string "Que…$"

Route125_Text_SharonPostBattle:
	.string "Cette force… Tu ne me déçois pas!\nAu contraire, j'en ai le souffle coupé!$"

Route125_Text_ErnestIntro:
	.string "Je suis un MARIN robuste et passionné.\nJ'ai bravé les mers du monde entier!$"

Route125_Text_ErnestDefeat:
	.string "Arrrrg!\nJe n'ai pas réussi à gagner!$"

Route125_Text_ErnestPostBattle:
	.string "Dans la GROTTE TREFONDS, la mer\nmonte et descend.\pIl y a environ six heures entre la marée\nhaute et la marée basse. Tu l'savais?$"

Route125_Text_ErnestRegister:
	.string "Enregistre-moi dans ton POKéNAV\net je te dirai un truc dingue!$"

Route125_Text_ErnestRematchIntro:
	.string "Il est grand temps que je prenne ma\nrevanche sur toi! Place au combat!$"

Route125_Text_ErnestRematchDefeat:
	.string "Je n'ai pas réussi à gagner!\nAbsolument pas!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTE TREFONDS…\pIl existe des endroits accessibles\nou non en fonction de la marée.\lTout dépend si elle est haute ou basse.\pN'oublie pas qu'il y a environ six heures\nentre la marée haute et la marée basse!$"

Route125_Text_KimIntro:
	.string "KIM: Un drôle de vieux monsieur vit dans\nla GROTTE TREFONDS. On me l'a dit.\pToi aussi tu veux aller le voir?$"

Route125_Text_KimDefeat:
	.string "KIM: Je croyais qu'on allait gagner.$"

Route125_Text_KimPostBattle:
	.string "KIM: Un drôle de vieux monsieur vit dans\nla GROTTE TREFONDS, n'est-ce pas?\pAllons le voir, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Non, non et non! Il te faut\ndeux POKéMON sinon, c'est pas la peine!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, tu peux me dire ce\nqu'on cherche là?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, on ne peut plus trop avancer.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, on va vraiment aller dans\nla GROTTE TREFONDS?\pOn va être toutes mouillées.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, on ne pourrait jamais\ncombattre à 2 contre 1.$"

Route125_Text_PresleyIntro:
	.string "Tu te demandes ce qu'un ORNITHOLOGUE\ncomme moi fait au milieu de l'océan?$"

Route125_Text_PresleyDefeat:
	.string "OK, je vais te dire ce que je fais ici.$"

Route125_Text_PresleyPostBattle:
	.string "J'ai mis un message dans une bouteille\net je suis venu le déposer.\pJ'espère qu'une jolie NAGEUSE\ntombera dessus.$"

Route125_Text_AuronIntro:
	.string "Hé! C'est toi qui jettes des ordures\nà la mer?$"

Route125_Text_AuronDefeat:
	.string "Oh, apparemment ça n'était pas toi?$"

Route125_Text_AuronPostBattle:
	.string "J'ai trouvé une affreuse bouteille en\ntrain de flotter dans l'eau.\pÇa me met hors de moi de voir\nles gens polluer la mer.$"

Route126_Text_BarryIntro:
	.string "La natation fait travailler tout le\ncorps. Ça va te donner la pêche!$"

Route126_Text_BarryDefeat:
	.string "Je l'admets! Tu as gagné!$"

Route126_Text_BarryPostBattle:
	.string "Mate un peu ce physique! C'est grâce\nà la natation que je fais chaque jour.$"

Route126_Text_DeanIntro:
	.string "Cette très haute montagne de roche\nblanche, c'est ATALANOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "Tu m'as réglé mon compte?$"

Route126_Text_DeanPostBattle:
	.string "Je n'arrive pas à trouver l'entrée\nd'ATALANOPOLIS. Où peut-elle être?$"

Route126_Text_NikkiIntro:
	.string "Lalalalalala!\nJe suis une sirène!$"

Route126_Text_NikkiDefeat:
	.string "Je m'efface devant toi, comme une bulle\nqui éclate! Bul, bul, bul…$"

Route126_Text_NikkiPostBattle:
	.string "Tu m'as battue… Je veux disparaître\ndans une vague de désespoir…$"

Route126_Text_BrendaIntro:
	.string "Salut, p'tit môme!\nTu te bats contre moi?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooon!$"

Route126_Text_BrendaPostBattle:
	.string "J'adore m'ébattre comme ça dans la mer\navec les POKéMON!$"

Route126_Text_PabloIntro:
	.string "Admire un peu ce corps d'athlète!\nJe suis encore plus costaud qu'un\lKARATEKA!$"

Route126_Text_PabloDefeat:
	.string "Oups!\nPas mal, pas mal du tout!$"

Route126_Text_PabloPostBattle:
	.string "Perdre contre toi ne fait que me\nmotiver davantage.\pJe vais m'entraîner avec mes POKéMON\nencore plus durement!$"

Route126_Text_PabloRegister:
	.string "Ouaip, vraiment pas mal!\nJ'aimerais vraiment te connaître un\lpeu mieux!$"

Route126_Text_PabloRematchIntro:
	.string "Mate un peu ce physique! Je suis\nencore plus musclé qu'un NAGEUR!$"

Route126_Text_PabloRematchDefeat:
	.string "Oups! Vraiment trop fort!$"

Route126_Text_PabloPostRematch:
	.string "Tu arrives vraiment à me motiver.\nJe vais m'entraîner encore plus!\pReviens me voir dès que possible!$"

Route126_Text_LeonardoIntro:
	.string "L'année dernière, je n'étais même pas\ncapable de nager la brasse.\pMais maintenant je suis un bon NAGEUR,\nje vais te montrer!$"

Route126_Text_LeonardoDefeat:
	.string "Je ferais mieux d'apprendre le crawl.$"

Route126_Text_LeonardoPostBattle:
	.string "Rien de mieux que l'entraînement pour\nse perfectionner.\pTu es jeune, n'hésite pas à essayer\nplein de choses!$"

Route126_Text_IsobelIntro:
	.string "Tu ne trouves pas ça affreux d'avaler\nde l'eau salée par le nez?$"

Route126_Text_IsobelDefeat:
	.string "Gloub gloub.\nJ'ai bu la tasse!$"

Route126_Text_IsobelPostBattle:
	.string "J'ai avalé de l'eau!\nC'est salé et amer!$"

Route126_Text_SiennaIntro:
	.string "Je vais y mettre tout mon cœur!$"

Route126_Text_SiennaDefeat:
	.string "Tu as montré plus de volonté.$"

Route126_Text_SiennaPostBattle:
	.string "Je suis épuisée…\nJe vais faire la planche pour changer.$"

Route127_Text_CamdenIntro:
	.string "Je le lis sur ton visage. Tu veux\nme défier.$"

Route127_Text_CamdenDefeat:
	.string "Ooooooooooooh…$"

Route127_Text_CamdenPostBattle:
	.string "Un combat bien disputé me ravigote\net m'apaise.$"

Route127_Text_DonnyIntro:
	.string "As-tu un rival contre qui tu détestes\nperdre?$"

Route127_Text_DonnyDefeat:
	.string "Arrrrg!\nJ'ai horreur de perdre!$"

Route127_Text_DonnyPostBattle:
	.string "Si tu as un rival, ne ressens-tu pas le\ndevoir de toujours faire mieux?$"

Route127_Text_JonahIntro:
	.string "Grâce à la pêche, j'ai atteint un état de\ncomplète sérénité…\pPermets-moi de t'en donner la preuve…$"

Route127_Text_JonahDefeat:
	.string "Même si j'ai perdu, je reste serein…$"

Route127_Text_JonahPostBattle:
	.string "Ce n'est pas grave si je n'attrape rien.\nLa ligne reste dans l'eau…$"

Route127_Text_HenryIntro:
	.string "Ne me dis pas qu'un POKéMON en train\nde SURFER s'est accroché à ma ligne!$"

Route127_Text_HenryDefeat:
	.string "Je n'arrive pas à tenir le rythme!$"

Route127_Text_HenryPostBattle:
	.string "Tes POKéMON ont l'air plutôt forts.\nSi je voulais les attraper, j'aurais\ldu fil à retordre!$"

Route127_Text_RogerIntro:
	.string "Hé! C'est parti pour un match entre toi,\nfan de POKéMON et moi, mordu de pêche!$"

Route127_Text_RogerDefeat:
	.string "Non! Ma ligne est emmêlée!\nLa partie est terminée!$"

Route127_Text_RogerPostBattle:
	.string "Ma ligne exécute une danse!\nLe méli-mélo! Hahaha, elle est emmêlée…$"

Route127_Text_AidanIntro:
	.string "Les POKéMON OISEAU ont une bonne\nvue. Ils repèrent leurs proies de haut.$"

Route127_Text_AidanDefeat:
	.string "Pfooou… J'abandonne!$"

Route127_Text_AidanPostBattle:
	.string "Par ici, il y a beaucoup d'endroits où\ntu peux plonger.\pIls sont facilement repérables du ciel\nen raison de leur couleur plus foncée.$"

Route127_Text_KojiIntro:
	.string "Marcher pieds nus, c'est ce que je\nconseille pour s'endurcir l'esprit!$"

Route127_Text_KojiDefeat:
	.string "Woutch! Je me suis pris une\nécharde dans le pied!$"

Route127_Text_KojiPostBattle:
	.string "C'est sympa de marcher pieds nus.\nMais tes CHAUSSURES ont l'air\lvraiment pas mal!$"

Route127_Text_KojiRegister:
	.string "Voilà ce que je fais à ceux qui me\nbattent! J'espère qu'on se reverra!$"

Route127_Text_KojiRematchIntro:
	.string "Je marche pieds nus tous les jours.\nMes pieds sont durs comme la pierre!$"

Route127_Text_KojiRematchDefeat:
	.string "Ouch! Encore une écharde!$"

Route127_Text_KojiPostRematch:
	.string "Tu n'veux pas essayer de marcher\npieds nus?\pComme ça je pourrai t'emprunter tes\nCHAUSSURES…$"

Route127_Text_AthenaIntro:
	.string "Affrontons-nous dans un combat\ncalme et méthodique.$"

Route127_Text_AthenaDefeat:
	.string "Tu ne m'as pas donné le temps de me\nbattre stratégiquement.$"

Route127_Text_AthenaPostBattle:
	.string "Quand je suis entourée par le ciel et\nla mer, c'est comme si le temps\ls'arrêtait.$"

Route128_Text_IsaiahIntro:
	.string "Il y a encore un bon bout de chemin\navant ETERNARA…$"

Route128_Text_IsaiahDefeat:
	.string "J'ai aussi du chemin à parcourir\navant ma première victoire…$"

Route128_Text_IsaiahPostBattle:
	.string "Toute ma vie j'ai connu la défaite,\nmais je n'abandonnerai jamais!$"

Route128_Text_IsaiahRegister:
	.string "Je sais que je n'ai pas le niveau pour\nl'instant. Mais ça changera.\pEnregistre-moi dans ton POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "Je ne suis pas trop fatigué. Je vais\ncontinuer à nager jusqu'à ETERNARA.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Je n'ai pas encore goûté à la victoire…$"

Route128_Text_IsaiahPostRematch:
	.string "Je vais arriver à ETERNARA,\noù je vais finalement gagner…$"

Route128_Text_KatelynIntro:
	.string "Un triathlon est une course épuisante\ncomposée de trois épreuves.\pIl faut nager, faire du vélo et puis\ncourir un semi-marathon.$"

Route128_Text_KatelynDefeat:
	.string "Un combat de POKéMON, c'est épuisant\naussi…$"

Route128_Text_KatelynPostBattle:
	.string "Après, je dois rouler en VELO, mais…\nJe suis sur le point de jeter l'éponge…$"

Route128_Text_KatelynRegister:
	.string "Je suis sûre que je pourrais mieux\nfaire. On se fait une revanche un de\lces jours?$"

Route128_Text_KatelynRematchIntro:
	.string "C'est long un triathlon. Mais je suppose\nque devenir le MAITRE POKéMON\lest également long et épuisant.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combat de POKéMON, c'est vraiment\ndur et ça ne pardonne pas…$"

Route128_Text_KatelynPostRematch:
	.string "Tu devrais bien réfléchir aux défis qui\nt'attendent sur la ROUTE VICTOIRE.$"

Route128_Text_AlexaIntro:
	.string "Nous avons travaillé si dur pour relever\nle défi de la LIGUE POKéMON…\pNous ne pouvons pas perdre maintenant!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\nComment cela a-t-il pu se produire?!$"

Route128_Text_AlexaPostBattle:
	.string "Après ce que j'ai fait pour en arriver là,\nje n'vais pas m'arrêter sur une défaite.$"

Route128_Text_RubenIntro:
	.string "Il n'y a pas plus fort DRESSEUR que moi!$"

Route128_Text_RubenDefeat:
	.string "C'est impossible!$"

Route128_Text_RubenPostBattle:
	.string "Il n'y a probablement pas plus fort\nDRESSEUR que toi!$"

Route128_Text_WayneIntro:
	.string "Je veux aller à ETERNARA, alors j'ai\nattrapé un POKéMON connaissant\lCASCADE pour monter les chutes d'eau.$"

Route128_Text_WayneDefeat:
	.string "J'ai chuté!$"

Route128_Text_WaynePostBattle:
	.string "Ah, ah, très drôle!\pMon POKéMON connaît CASCADE, mais je\nn'ai pas le BADGE d'ATALANOPOLIS!$"

Route128_Text_HarrisonIntro:
	.string "Tu as l'air plutôt coriace. Je me\ndemande si je peux gagner…$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\nÇa ne devait pas être possible.$"

Route128_Text_HarrisonPostBattle:
	.string "De nombreux DRESSEURS plutôt doués\nse réunissent souvent près d'ETERNARA.\pTu crois que je suis assez fort\npour eux?$"

Route128_Text_CarleeIntro:
	.string "Le soleil semble briller plus fort par\nlà-bas.$"

Route128_Text_CarleeDefeat:
	.string "J'ai perdu parce que j'avais le soleil\ndans les yeux.$"

Route128_Text_CarleePostBattle:
	.string "Il va falloir que je rentre. Je dois me\nremettre de la protection solaire.$"

Route129_Text_ChaseIntro:
	.string "C'est mon premier triathlon.\nJe suis tout tendu et nerveux!$"

Route129_Text_ChaseDefeat:
	.string "Arrrrg!\nJ'ai raté la victoire!$"

Route129_Text_ChasePostBattle:
	.string "Si je suis tendu, je ne vais pas pouvoir\ndonner le maximum.$"

Route129_Text_AllisonIntro:
	.string "Je suis en plein milieu d'un triathlon,\nmais oui, battons-nous!$"

Route129_Text_AllisonDefeat:
	.string "J'étais pourtant sûre de gagner!$"

Route129_Text_AllisonPostBattle:
	.string "Tu sais ce qu'il y a de plus formidable\ndans le triathlon?\pC'est de pouvoir tester les limites de\nta propre force et de ton endurance\lface à Mère Nature!$"

Route129_Text_ReedIntro:
	.string "Hé!\nQu'on s'y mette!$"

Route129_Text_ReedDefeat:
	.string "Battu… On m'a battu!\nÇa y est, c'est fait!$"

Route129_Text_ReedPostBattle:
	.string "Un perdant n'a rien à attendre. Il est\ntemps pour moi de battre en retraite.$"

Route129_Text_TishaIntro:
	.string "Y a pas urgence?\nOn n'a qu'à s'y mettre tranquillement.$"

Route129_Text_TishaDefeat:
	.string "Oh, ça alors!\nJe voulais me détendre un peu plus…$"

Route129_Text_TishaPostBattle:
	.string "N'as-tu pas horreur de faire des\nerreurs quand tu te dépêches?\pC'est pour cela que j'essaie de prendre\nles choses calmement.$"

Route129_Text_ClarenceIntro:
	.string "Surfer n'est pas aussi facile qu'on\npourrait le penser, n'est-ce pas?$"

Route129_Text_ClarenceDefeat:
	.string "Gagner, c'est pas facile non plus!$"

Route129_Text_ClarencePostBattle:
	.string "Tu dois sûrement t'intéresser à\nla LIGUE POKéMON!\lContinue comme ça!$"

Route130_Text_RodneyIntro:
	.string "Quelle surprise! Je ne pensais pas\ntomber sur un DRESSEUR en mer.\pJe crois qu'on devrait s'affronter!$"

Route130_Text_RodneyDefeat:
	.string "Quelle force pour un si jeune âge…$"

Route130_Text_RodneyPostBattle:
	.string "Tu as le regard de quelqu'un qui a connu\nde rudes épreuves et qui a su relever\lles défis. Ça te correspond bien!$"

Route130_Text_KatieIntro:
	.string "Dans les eaux bleues et profondes de\nla mer, mon cœur désemparé trouve\lréconfort auprès des vagues.$"

Route130_Text_KatieDefeat:
	.string "Comme la mer, vaste et bleue, le\nmonde des POKéMON couvre des\lprofondeurs incroyables.$"

Route130_Text_KatiePostBattle:
	.string "Le rêve de tous les enfants du\nmonde, c'est de devenir un jour\lMAITRE POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotter au milieu de l'eau comme ça…\nÇa détend vraiment…$"

Route130_Text_SantiagoDefeat:
	.string "Je devais être un peu trop détendu!$"

Route130_Text_SantiagoPostBattle:
	.string "Se battre et nager comme ça…\nJe suis vraiment un homme heureux…$"

Route131_Text_RichardIntro:
	.string "La mer regorge de POKéMON.\nTu sais, c'est pas facile de nager.$"

Route131_Text_RichardDefeat:
	.string "Les POKéMON élevés par des DRESSEURS\nsont sacrément forts…$"

Route131_Text_RichardPostBattle:
	.string "Pfou… Pfou… Je suis lessivé…\pL'aller est facile. C'est le retour qui\nest plus difficile.\pVa-t-il me rester assez d'énergie pour\nfaire le trajet retour?$"

Route131_Text_HermanIntro:
	.string "La mer… La mer… La mer…\nLa mer à perte de vue!\pÇa me rend dingue!$"

Route131_Text_HermanDefeat:
	.string "Booouh!$"

Route131_Text_HermanPostBattle:
	.string "Je suis las de la mer et pourtant,\nje ne peux m'empêcher de nager.\pJe suis un nageur-né!\nVoilà ce que je suis.$"

Route131_Text_SusieIntro:
	.string "Salut, mon chou. Attends!\nOn devrait s'affronter, toi et moi!$"

Route131_Text_SusieDefeat:
	.string "Même si tu n'en as pas l'air, tu as\nune grande force!$"

Route131_Text_SusiePostBattle:
	.string "As-tu vu un type par ici qui se\nplaignait d'être lassé de la mer?\pTu parles!\nIl est éperdument amoureux de la mer!$"

Route131_Text_KaraIntro:
	.string "Pourquoi les hommes aiment-ils\ntant les maillots de bain?\pIls me matent tous!$"

Route131_Text_KaraDefeat:
	.string "J'ai perdu pied!$"

Route131_Text_KaraPostBattle:
	.string "C'est peut-être pas mon maillot de bain\nque matent les hommes, mais ma beauté!$"

Route131_Text_ReliIntro:
	.string "LANA: Avec mon frère, on va faire équipe\npour t'avoir!$"

Route131_Text_ReliDefeat:
	.string "LANA: On n'a pas réussi à gagner,\nmême en faisant équipe…$"

Route131_Text_ReliPostBattle:
	.string "LANA: A PACIFIVILLE, les habitants\nsont liés à la mer et aux POKéMON comme\lau premier jour.$"

Route131_Text_ReliNotEnoughMons:
	.string "LANA: Si tu n'as pas deux POKéMON,\non n'aura pas le plaisir de s'affronter.$"

Route131_Text_IanIntro:
	.string "IAN: Avec ma sœurette, on fait de\nnotre mieux!$"

Route131_Text_IanDefeat:
	.string "IAN: Avec ma sœurette, on a fait\ntout ce qu'on pouvait, mais on a perdu…$"

Route131_Text_IanPostBattle:
	.string "IAN: Tu sais que PACIFIVILLE\nest une ville flottante?\pAlors là où il y a la mer, se trouve une\npartie de PACIFIVILLE!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Si tu as deux POKéMON, on\nte prend à 2 contre 2!$"

Route131_Text_TaliaIntro:
	.string "Si tu arrives à me battre, je te donnerai\ndes infos intéressantes!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\nJ'ai vraiment perdu?$"

Route131_Text_TaliaPostBattle:
	.string "Il y a un endroit étrange pas très loin\nd'ici. On peut y voir une tour immense.\pMais pourquoi n'irais-tu pas y jeter\nun coup d'œil?$"

Route131_Text_KevinIntro:
	.string "Il n'y a pas plus calme que les gens\nde PACIFIVILLE.\pIls ne se mettent jamais en colère, un\npeu comme moi, quoi!$"

Route131_Text_KevinDefeat:
	.string "Oups!$"

Route131_Text_KevinPostBattle:
	.string "Gr… Eh, non!\nJe ne suis pas en colère, je t'assure!$"

Route132_Text_GilbertIntro:
	.string "Quand j'étais petit, je prenais toujours\nfroid mais depuis que je nage, je suis\len bonne santé.$"

Route132_Text_GilbertDefeat:
	.string "J'aimerais tant être plus puissant…$"

Route132_Text_GilbertPostBattle:
	.string "Les DRESSEURS arpentent champs et\nmontagnes. Ça les garde en forme aussi.$"

Route132_Text_DanaIntro:
	.string "Je ne nage pas là où le courant est\ntrop fort.$"

Route132_Text_DanaDefeat:
	.string "Oh, non, je t'en supplie!$"

Route132_Text_DanaPostBattle:
	.string "Si je me fais balayer, je vais perdre\ntout repère…$"

Route132_Text_RonaldIntro:
	.string "Défaite, victoire… Si tu n'essaies pas,\ntu ne sauras jamais…$"

Route132_Text_RonaldDefeat:
	.string "Waah!\nJe sombre dans la défaite!$"

Route132_Text_RonaldPostBattle:
	.string "Je ne me bats jamais si je sais que c'est\ngagné d'avance. J'aime me battre en\lprenant le risque de perdre!$"

Route132_Text_KiyoIntro:
	.string "Je médite sur les POKéMON 24 heures\nsur 24. Comment pourrais-tu me battre?$"

Route132_Text_KiyoDefeat:
	.string "J'ai perdu.\nJ'admets la défaite.$"

Route132_Text_KiyoPostBattle:
	.string "Arrrg…\nTu es fana de POKéMON, n'est-ce pas?\pTu dois observer les POKéMON 24 heures\nsur 24, pas vrai?$"

Route132_Text_MakaylaIntro:
	.string "Je suis toujours avec mon mari, mais\nje peux gagner même sans lui!$"

Route132_Text_MakaylaDefeat:
	.string "Oh, je ne devais pas être assez forte!$"

Route132_Text_MakaylaPostBattle:
	.string "Le jeune homme plus loin est le portrait\ncraché de mon mari quand il était\lplus jeune.\pIl me fait rougir!$"

Route132_Text_JonathanIntro:
	.string "Quelqu'un n'arrête pas de me regarder!\nCe ne serait pas toi par hasard?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\nOK, j'ai compris!$"

Route132_Text_JonathanPostBattle:
	.string "J'ai la désagréable impression que\nquelqu'un n'arrête pas de me regarder!\pJe n'arrive pas à me concentrer!$"

Route132_Text_PaxtonIntro:
	.string "Où est-ce que ma femme est encore\npassée?\pJe passe mon temps à la chercher\npartout!$"

Route132_Text_PaxtonDefeat:
	.string "Ah, j'aurais dû attendre l'aide de ma\nfemme pour t'affronter.$"

Route132_Text_PaxtonPostBattle:
	.string "Ma femme doit être en train de me\nchercher. Je vais aller à sa rencontre.$"

Route132_Text_DarcyIntro:
	.string "J'adore m'entraîner toute seule ici.\nJe ne supporte pas que tous ces gens\lsoient là!$"

Route132_Text_DarcyDefeat:
	.string "OK, j'arrête de me plaindre de voir trop\nde monde ici!$"

Route132_Text_DarcyPostBattle:
	.string "Je suppose que je dois pouvoir faire\néquipe avec ce vieil homme pour\laffronter l'autre équipe.$"

Route133_Text_FranklinIntro:
	.string "Le courant m'a mené ici. Toi aussi?\nC'est un coup du destin. Battons-nous!$"

Route133_Text_FranklinDefeat:
	.string "Quelle force!\nTrop pour moi!$"

Route133_Text_FranklinPostBattle:
	.string "C'est bien ma chance… Un DRESSEUR\naussi fort que toi qui atterrit ici…\lJe dois être maudit…$"

Route133_Text_DebraIntro:
	.string "J'ai mené une existence de chagrin et\nde misère… J'ai fait naufrage et voilà\loù je me suis retrouvée…$"

Route133_Text_DebraDefeat:
	.string "Encore une autre défaite…$"

Route133_Text_DebraPostBattle:
	.string "Une vie à la dérive…\nJe n'en veux plus!$"

Route133_Text_LindaIntro:
	.string "Bienvenue!\nJe t'attendais!$"

Route133_Text_LindaDefeat:
	.string "Non! Je t'en prie!$"

Route133_Text_LindaPostBattle:
	.string "Un DRESSEUR aussi fort et pourtant\nsi jeune… C'est agaçant!$"

Route133_Text_WarrenIntro:
	.string "Comme les autres, je veux gagner. Mais\nje ne veux pas que mes POKéMON soient\lcomme ceux des autres.$"

Route133_Text_WarrenDefeat:
	.string "Zut!\nJe ne suis pas encore assez énergique!$"

Route133_Text_WarrenPostBattle:
	.string "C'est plus sympa de faire les choses à\nma guise que de faire comme les autres.\lC'est évident!$"

Route133_Text_BeckIntro:
	.string "J'ai fait tout le chemin jusqu'ici avec\nmon POKéMON OISEAU.$"

Route133_Text_BeckDefeat:
	.string "Tu…\nTu gardes un tel sang-froid!$"

Route133_Text_BeckPostBattle:
	.string "J'aimerais retourner à CIMETRONELLE,\nmais j'ai aussi appris à aimer ce lieu.$"

Route133_Text_MollieIntro:
	.string "J'ai dû me battre des centaines de fois,\nmais j'ai arrêté de compter!$"

Route133_Text_MollieDefeat:
	.string "J'ai aussi perdu des centaines de fois,\nmais ça fait toujours aussi mal!$"

Route133_Text_MolliePostBattle:
	.string "Continue comme ça, et un jour tu seras\ncomme mon mari et moi!$"

Route133_Text_ConorIntro:
	.string "Les jeunes n'en font qu'à leur tête. Ils\nn'ont vraiment rien dans le crâne.$"

Route133_Text_ConorDefeat:
	.string "Les jeunes n'ont vraiment aucun\nrespect pour leurs aînés!$"

Route133_Text_ConorPostBattle:
	.string "Ne laisse pas les autres diriger ta vie.\nEt essaie de toujours suivre ton but!$"

Route134_Text_JackIntro:
	.string "Même les POKéMON qui savent nager sont\nemportés par le courant.$"

Route134_Text_JackDefeat:
	.string "Ouuuuuille!$"

Route134_Text_JackPostBattle:
	.string "Je crois que les POKéMON aiment bien\nles forts courants des environs.$"

Route134_Text_LaurelIntro:
	.string "Mes LOVDISC veulent un match sympa.\nTu te joins à nous?$"

Route134_Text_LaurelDefeat:
	.string "Oups!$"

Route134_Text_LaurelPostBattle:
	.string "Il y a un collectionneur qui recherche\nles ECAILLES de LOVDISC.$"

Route134_Text_AlexIntro:
	.string "Dacodac! Assez flemmardé!\nIl est temps de combattre!$"

Route134_Text_AlexDefeat:
	.string "Encore carrément naze…$"

Route134_Text_AlexPostBattle:
	.string "Mes POKéMON OISEAU sont vite fatigués\naprès un long vol…$"

Route134_Text_HitoshiIntro:
	.string "Tu es DRESSEUR de POKéMON.\nLes mots sont inutiles. Agissons!$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "C'est moi qui te défie et c'est moi\nqui perds. J'ai vraiment honte…$"

Route134_Text_AaronIntro:
	.string "Le mauvais temps sur cette zone nous\npermet d'être plus forts que jamais.$"

Route134_Text_AaronDefeat:
	.string "J'admets la défaite!$"

Route134_Text_AaronPostBattle:
	.string "On va retourner au SITE METEORE\npour s'entraîner davantage.\pSi ça te dit, tu n'as qu'à venir aussi.\nJe vais t'endurcir!$"

Route134_Text_KelvinIntro:
	.string "Notre… notre bateau!\nLa marée l'a emmené!$"

Route134_Text_KelvinDefeat:
	.string "Arrête, arrête, j'abandonne!$"

Route134_Text_KelvinPostBattle:
	.string "Si on ne peut pas SURFER, comment\nfaire pour rentrer chez nous?\pEn fait, je sais qu'un POKéMON K.O.\npeut utiliser SURF, mais ça me\ldonne mauvaise conscience…$"

Route134_Text_MarleyIntro:
	.string "Est-ce que tes POKéMON peuvent éviter\nnos attaques rapides comme l'éclair?$"

Route134_Text_MarleyDefeat:
	.string "Je ne savais pas qu'une telle technique\nexistait! Tu m'as complètement battue!$"

Route134_Text_MarleyPostBattle:
	.string "Je n'ai pas perdu mon goût pour la\nvitesse. J'essaierai encore et encore!$"

Route134_Text_ReynaIntro:
	.string "Mes POKéMON ne pourront pas être\nbattus si facilement!$"

Route134_Text_ReynaDefeat:
	.string "Tu plaisantes?\nComment t'as fait pour gagner?$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\nTu as gagné, très bien!\pJe vais affronter tous les DRESSEURS\nque je croiserai sur le chemin du retour\lpour retrouver mon vrai niveau!$"

Route134_Text_HudsonIntro:
	.string "Dis, t'aurais pas vu un autre MARIN\ndans l'coin?$"

Route134_Text_HudsonDefeat:
	.string "Wow! C'était vraiment quelque chose!$"

Route134_Text_HudsonPostBattle:
	.string "Notre bateau a pris la mer.\pMon compagnon est quelqu'un de timide,\nalors je suis un peu inquiet pour lui.$"
