LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Bonjour! Vous étiez dans un CONCOURS\nPOKéMON, n'est-ce pas?\pJe reconnais votre POKéMON.\pJe suis journaliste. Je réalise un\nreportage sur les CONCOURS POKéMON.\pJe peux me permettre de vous poser\nquelques questions?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Vous voulez bien? Super!\nMerci.\pRapidement, comment décririez-vous le\nCONCOURS auquel vous avez participé?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Oh, je vois.\nQuelle déclaration incroyable.\pCela donne un bon aperçu de la\nfaçon dont s'est déroulé le CONCOURS.\pJ'ai une dernière question.\pLorsque vous entendez\n«{STR_VAR_2}»,\lça vous évoque quoi?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Je vois!\pC'est comme ça que vous percevez le\nconcept de «{STR_VAR_2}».\pMerci!\nVous m'avez donné de bonnes idées.\pJe vais pouvoir réaliser un chouette\nreportage sur les CONCOURS POKéMON.\pAvec un peu de chance, ce reportage\npassera même à la télé.\lJ'espère que vous ne le raterez pas!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, quel dommage…\pEh bien, si vous entendez parler d'une\nhistoire intéressante, revenez me voir.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Je suivrai votre prochain CONCOURS\nPOKéMON avec intérêt.$"

gTVBravoTrainerText00::
	.string "Youhou!\nC'est l'heure de DRESSEUR SPECIAL!\pNous allons vous présenter un\nPOKéMON appartenant à {STR_VAR_1}.\pSur le thème {STR_VAR_2}, ce POKéMON\na gagné un CONCOURS\lcatégorie {STR_VAR_3}.$"

gTVBravoTrainerText01::
	.string "Et voici {STR_VAR_2} le {STR_VAR_1}!\pIl est surnommé {STR_VAR_2}…\p«{STR_VAR_3}»!\nSon surnom l'évoque déjà!$"

gTVBravoTrainerText02::
	.string "Quoi qu'il en soit, quand le DRESSEUR\n{STR_VAR_1} a inscrit ce POKéMON dans un \lCONCOURS, nous avons réussi à lui poser\lquelques questions sur son partenaire.$"

gTVBravoTrainerText03::
	.string "A propos du CONCOURS,\n{STR_VAR_1} a déclaré avec un sourire:\l«{STR_VAR_2}»!\pLe POKéMON de {STR_VAR_1} a pris la place\nnuméro {STR_VAR_3} du CONCOURS.\pCette phrase résume bien l'état\nd'esprit de {STR_VAR_1} en ce moment!$"

gTVBravoTrainerText04::
	.string "A propos du CONCOURS,\n{STR_VAR_1} a déclaré avec une pointe\ld'amertume: «{STR_VAR_2}».\pLe POKéMON de {STR_VAR_1} a pris la place\nnuméro {STR_VAR_3} du CONCOURS.\pIl me semble que la déception de\n{STR_VAR_1} est tout à fait évidente!$"

gTVBravoTrainerText05::
	.string "Vous aimeriez peut-être savoir comment\n{STR_VAR_1} conçoit la qualité {STR_VAR_2}?\pEvidemment!\nDonc, nous lui avons demandé!\pLa réponse est claire et concise:\n«{STR_VAR_3}».\pVoilà comment {STR_VAR_1} définit la\nqualité {STR_VAR_2}!$"

gTVBravoTrainerText06::
	.string "La dernière démo, {STR_VAR_2},\nutilisée par {STR_VAR_1} était\ltout à fait «{STR_VAR_3}»!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\nBravo, {STR_VAR_2}!\pJ'espère que nous pourrons encore\nvoir {STR_VAR_1} gravir les échelons de\lla gloire!\pBien, le temps qui nous est accordé est\ndésormais écoulé! A vous les studios!$"

gTVBravoTrainerText08::
	.string "Et voici le {STR_VAR_1} du DRESSEUR!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Bonjour! C'est vous qui venez de vous\nbattre, n'est-ce pas?\pJ'interviewe tous les DRESSEURS\ndu coin.\pVous pouvez me donner vos impressions\nsur le combat?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vraiment? Vous acceptez?\nMerci!\lDonc, heu…\pComment ça s'est passé dans la TOUR DE\nCOMBAT?\pEn gardez-vous une bonne impression?\nOu une mauvaise impression?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\nJe m'excuse du dérangement.\pJ'espère que vous accepterez\nde nous répondre lors de votre\lprochaine visite.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Mais bien sûr!\pCette incroyable lueur de satisfaction\ndans vos yeux…\pDe toute évidence, vous avez fait un\ntrès beau combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, je vois…\pOui, les combats ne se déroulent pas\ntoujours comme prévu.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Une dernière petite question?\pSi vous deviez résumer vos impressions\nsur ce combat, que diriez-vous?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Incroyable!\pQuelle déclaration! Bonne chance pour\nvos prochains combats.\pA bientôt, j'espère!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, je vois…\pMais être du genre silencieux, c'est\nbien aussi, non?\pJ'espère avoir de nouveau l'occasion\nde parler avec vous!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "J'ai hâte que vous fassiez votre\nprochain combat!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ouais!\nC'est l'heure du DRESSEUR SPECIAL!\pNous allons vous présenter {STR_VAR_1}, qui\na relevé le défi de la TOUR DE COMBAT!\pPour ce défi, {STR_VAR_1} avait inscrit\nson malicieux {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Ils ont tous les deux établi le nouveau\nrecord de {STR_VAR_2} victoires consécutives\pau {STR_VAR_1} de la compétition.\nBravo!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Ils se sont finalement inclinés devant\n{STR_VAR_1} lors du match numéro {STR_VAR_2}.\lTrès bel essai, DRESSEUR!\pAffronter {STR_VAR_1} aussi tôt dans la\ncompétition, quelle malchance!\pNous avons demandé au DRESSEUR ses\nimpressions sur {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Ils ont triomphé en combattant avec\nbrio {STR_VAR_2} de {STR_VAR_1}.\lBravo, DRESSEUR!\pIls ont même battu {STR_VAR_1}…\nEtonnant! Epoustouflant!\pNous avons demandé au DRESSEUR ses\nimpressions au moment de la victoire.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Après une série de victoires, ils ont\nperdu devant {STR_VAR_2} de\l{STR_VAR_1}, l'obstacle final.\pTrès bel essai, DRESSEUR!\pMais il faut bien avouer qu'il y a peu\nde combinaisons aussi réussies que\l{STR_VAR_1} et {STR_VAR_2}.\pNous avons demandé au DRESSEUR ses\nimpressions sur ce couple infernal.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Voici la déclaration du DRESSEUR:\n«Entière satisfaction!»\pN'est-ce pas rafraîchissant?\nBravo, DRESSEUR!\pN'est-ce pas grandiose de pouvoir se\nbattre jusqu'à la satisfaction totale?\pJ'ai vraiment compris l'état d'esprit\ndu DRESSEUR quand il a déclaré:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Voici la déclaration du DRESSEUR: «On ne\npeut pas parler de satisfaction…»\pVisiblement, notre DRESSEUR était \nquelque peu abattu.\pMais il faut dire qu'il est dur de sortir\ndu combat pleinement satisfait, non?\pJ'ai mieux compris l'état d'esprit\ndu DRESSEUR quand il a déclaré:$"

BravoTrainerBattleTower_Text_None1::
	.string "Rien$"

BravoTrainerBattleTower_Text_None2::
	.string "Rien$"

BravoTrainerBattleTower_Text_None3::
	.string "Rien$"

BravoTrainerBattleTower_Text_None4::
	.string "Rien$"

BravoTrainerBattleTower_Text_Response::
	.string "«{STR_VAR_1}».$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "«{STR_VAR_1}».\nN'est-ce pas formidable?\pCela exprime parfaitement la joie\nde {STR_VAR_2}, je pense.\pCe combat contre {STR_VAR_3}, vers\nla fin… «{STR_VAR_1}»,\lc'est vraiment ce que vous en diriez!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "«{STR_VAR_1}».\nVoilà qui est judicieux, n'est-ce pas?\pEt ce dernier combat contre\n{STR_VAR_3}… Je crois que la\ldéclaration «{STR_VAR_1}» résume\lparfaitement la situation!\pIl me semble que la déception de\n{STR_VAR_2} ne fait pas de doute!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\nBravo, {STR_VAR_2}!\pJ'espère que nous pourrons encore\nvoir {STR_VAR_1} gravir les échelons\lde la gloire!\pBien, le temps qui nous est accordé est\ndésormais écoulé! A vous les studios!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Waouh!\pApparemment, vous donnez beaucoup\nd'amour à votre {STR_VAR_1}.\pAh, d'accord, il s'appelle {STR_VAR_2}.\pJe peux vous demander un service?\pJe suis journaliste pour la télé et je\nréalise un sondage sur les POKéMON.\pPourriez-vous répondre à quelques\nquestions simples, pour moi?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Super! Merci beaucoup!\pTrès bien, allons-y. Il me faut des\nréponses concises, d'accord?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "La première fois que vous avez vu\n{STR_VAR_1}, qu'avez-vous ressenti?\pComment décririez-vous les sentiments\nque vous avez éprouvés, à l'époque?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Ce {STR_VAR_1} est traité avec amour.\pSi vous le compariez à quelque chose\nque vous aimez, de quoi s'agirait-il?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Cette question est aussi valable pour\nvotre {STR_VAR_1} adoré.\pQu'est-ce que vous aimez\nchez {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Bien sûr, c'est logique.\pLa prochaine question est un peu\nplus compliquée.\pLa voici:\pPour vous, que signifie POKéMON?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Je vois!\pHumm…\pTrès bien!\nMerci de votre coopération.\pCette discussion avec vous a été\namusante et enrichissante.\pVotre interview passera peut-être à\nla télé. Regardez-la régulièrement!\pVoilà, c'est tout.\nAu revoir!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, très bien…\pSi vous changez d'avis et que vous\nvoulez parler de POKéMON, je serai là!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "J'adore ce métier. On peut apprendre\ntellement de choses sur les POKéMON en\lfaisant des interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Salut! Vous semblez très proche de\nvotre {STR_VAR_1}.\pVous savez quoi?\nJe suis journaliste pour la télé.\pJe voyage pour interviewer les gens\nà propos des POKéMON.\pMais j'y pense, vous voulez peut-être\nme parler de votre {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Super, merci!\pBon, eh bien, dites-moi ce que vous\naimez chez votre {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Oh…\nVoilà des remarques intéressantes.\pVous êtes vraiment très intime avec\n{STR_VAR_1}, n'est-ce pas?\pJ'ai l'impression que vos déclarations\nferont un chouette sujet pour la télé.\pJe vous promets d'en faire une\nsuper émission.\lRegardez-nous régulièrement.\pVoilà, c'est tout.\nAu revoir!$"

gTVFanClubOpinionsText00::
	.string "C'EST NOUS, LE FAN CLUB POKéMON!\pEt nous sommes en direct!\pDans cette émission, nous compilons\nvos opinions et nous les diffusons!\lSuper concept d'émission, n'est-ce pas?\pAujourd'hui, nous vous présentons un\nreportage de notre journaliste,\lenvoyé spécial au FAN CLUB POKéMON.\pBien, qui est notre fan de POKéMON,\naujourd'hui?\p… … … … … … … …\p{STR_VAR_1}!\pEcoutons ce que {STR_VAR_1} souhaite nous\nraconter sur {STR_VAR_3} le {STR_VAR_2}.\pPuis, je répandrai ces belles paroles\nsur les ondes!\pYou-hou!\pC'est parti!$"

gTVFanClubOpinionsText01::
	.string "Nous avons demandé à {STR_VAR_1}: «La\npremière fois que vous avez vu votre\l{STR_VAR_2}, qu'avez-vous ressenti?»\p«{STR_VAR_3}»!\pHé! Génial! Quelles paroles magnifiques!\pPas de doute, ça nous remet en mémoire\nde magnifiques souvenirs d'autrefois.$"

gTVFanClubOpinionsText02::
	.string "Nous avons demandé à {STR_VAR_1}: «Si vous\ndeviez comparer votre {STR_VAR_2} à\lquelque chose, ce serait…»\p… … … … … … … …\p«{STR_VAR_3}»!\pHé, voilà une idée originale!\pOn peut sentir l'intensité des\nsentiments de ce DRESSEUR pour\lson {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Continuons…\nQu'est-ce qui était si attirant\lchez {STR_VAR_2} pour {STR_VAR_1}?\p… … … … … … … …\p«{STR_VAR_3}»!\pWaouh! Quelle déclaration fracassante!\pL'amour de ce DRESSEUR pour son\n{STR_VAR_2} ne fait aucun doute!$"

gTVFanClubOpinionsText04::
	.string "Hein? Oh, nous avons encore du temps.\nTrès bien!\pVoyons donc…\pNous avons demandé à {STR_VAR_1}: «Pour\nvous, que signifie POKéMON?»\p… … … … … …\p«{STR_VAR_3}»!\pBravo!\pCe sont de bien belles paroles!\p«{STR_VAR_3}»!\pÇa donne envie de le répéter encore et\nencore!\pBien, après ces belles paroles, il est\ntemps de se dire au revoir.\pEt répétons encore une fois ces belles\nparoles! Tous ensemble…\p«{STR_VAR_3}»!$"

gTVFanClubText00::
	.string "C'EST NOUS, LE FAN CLUB POKéMON!\pEt nous sommes en direct!\pAujourd'hui, nous allons commencer par\nle QUART D'HEURE DES SONDAGES.\pParmi les histoires de POKéMON et de\nDRESSEURS, quel récit va attirer\lnotre attention aujourd'hui?\pVoyons voir…\pCelui-ci!\pNous allons commencer par cette lettre!\pIl s'agit d'une lettre de {STR_VAR_1} à\npropos de son {STR_VAR_2}.\pVoyons comment notre écrivain\nexprime son amour pour {STR_VAR_2}!\lHumm…$"

gTVFanClubText01::
	.string "Wouah!\nQuelle lettre incroyable!$"

gTVFanClubText02::
	.string "Elle m'a beaucoup plu. Je vais la relire!$"

gTVFanClubText03::
	.string "Quand une lettre est belle, on peut la\nrelire à volonté!$"

gTVFanClubText04::
	.string "La partie «{STR_VAR_3}» met vraiment\nl'accent sur l'impact émotionnel!\pC'est une lettre magnifique d'une\ngrande profondeur!$"

gTVFanClubText05::
	.string "Surtout la partie «{STR_VAR_3}»!\pSuper utilisation de «{STR_VAR_3}»!$"

gTVFanClubText06::
	.string "D'ailleurs, ça n'est pas important, mais\n«{STR_VAR_3}» est super chouette.\pCes derniers temps, j'utilise beaucoup\n«{STR_VAR_3}» dans les discussions.$"

gTVFanClubText07::
	.string "Si je devais noter cette lettre, je lui\ndonnerais {STR_VAR_3} points.\pLa prochaine fois, j'espère que {STR_VAR_1}\nnous fera une lettre encore meilleure!\pOh, le temps passe à une vitesse folle!\nIl est l'heure de se dire au revoir! Bye!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\nVous aimez peut-être les POKéMON?\pJ'effectue un reportage pour la chaîne\nde TV.\pJe recueille des histoires récentes de\nPOKéMON et de DRESSEURS.\pSi ça ne vous gêne pas, vous pourriez\npeut-être me parler de vous?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Je recueille des histoires récentes de\nPOKéMON et de DRESSEURS.\pSi ça ne vous gêne pas, vous pourriez\npeut-être me parler de vous?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, vous voulez bien?\nMerci beaucoup!\pDans ce cas, pouvez-vous me raconter\nune histoire intéressante en rapport\lavec des POKéMON?$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Bon, tant pis…\pSi vous avez une histoire intéressante\nà raconter, revenez me voir.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quelle histoire passionnante!\pJe vais m'arranger pour faire passer\nvotre histoire à la télévision.\pElle sera bientôt sur les écrans.\nVérifiez régulièrement.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Humm…\nJ'ai une excellente histoire pour une\lémission de télé.\pJe ferais mieux d'aller l'écrire de suite!$"

gTVRecentHappeningsText00::
	.string "Bonjour, bienvenue à HISTOIRES VECUES.\pLa vie quotidienne des DRESSEURS DE\nPOKéMON est digne des meilleurs contes.\pNous allons vous présenter certains de\nces contes de POKéMON.\pAujourd'hui, nous allons vous raconter\nl'histoire du DRESSEUR {STR_VAR_1}.\pQu'est-il arrivé à {STR_VAR_1} récemment?\nDécouvrons-le ensemble.\pC'est parti…$"

gTVRecentHappeningsText01::
	.string "Une histoire enrichissante,\nn'est-ce pas?\pCette histoire vous donne une idée\ndes récentes aventures de {STR_VAR_1}.\pC'est comme si nous étions sur place!$"

gTVRecentHappeningsText02::
	.string "«{STR_VAR_3}». Cela\ndonne de la profondeur à l'histoire.$"

gTVRecentHappeningsText03::
	.string "«{STR_VAR_3}».\nCela met l'histoire en perspective.\lOn en sait plus sur le contexte.$"

gTVRecentHappeningsText04::
	.string "«{STR_VAR_3}». Cette\npartie de l'histoire est explicite.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} nous a raconté une\nmerveilleuse histoire de POKéMON.\pL'histoire de {STR_VAR_1} est désormais\ngravée dans nos esprits pour toujours.\pC'est fini pour aujourd'hui.\nA la prochaine fois.$"

gTVMassOutbreakText00::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pNous venons d'apprendre l'apparition\nd'un phénomène très rare.\pDes témoignages affirment l'arrivée\nmassive de {STR_VAR_2} du côté de la\l{STR_VAR_1}.\pLes {STR_VAR_2}, comme vous le savez\ndéjà, sont des POKéMON très rares et\ldifficiles à trouver.\pVoici donc une chance unique de voir\nce débarquement en masse de\l{STR_VAR_2} sauvages dans la nature.\pC'était le scoop du BULLETIN POKéMON.$"

gTV3CheersForPokeblocksText00::
	.string "ANIMATRICE: C'est l'heure de retrouver\n«VIVE LES {POKEBLOCK}S»!\pAujourd'hui, nous allons tester le\n{POKEBLOCK} créé avec l'aide de {STR_VAR_1}.\pSans attendre, je vais le faire goûter\nà mon GLOUPTI.\p… …\n… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GLOUPTI: Gloup… Tiiii!\pANIMATRICE: Le {POKEBLOCK} est très\n{STR_VAR_1}!\pGLOUPTI dit que c'est {STR_VAR_2}!\pMerci beaucoup {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Le résultat de {STR_VAR_1} laisse\nà désirer.\pSi ce DRESSEUR pouvait mieux mixer,\nle {POKEBLOCK} aurait plus de goût.$"

gTV3CheersForPokeblocksText03::
	.string "GLOUPTI: Gloup… Tiiii!\pANIMATRICE: Le {POKEBLOCK} est trop\n{STR_VAR_1}!\pGLOUPTI dit que c'est {STR_VAR_2}!\pOn dirait que les erreurs de {STR_VAR_3}\nse ressentent sur la qualité du mixage.$"

gTV3CheersForPokeblocksText04::
	.string "Les efforts de {STR_VAR_1} n'ont servi\nà rien.\pEspérons que {STR_VAR_2} fera mieux\nla prochaine fois!$"

gTV3CheersForPokeblocksText05::
	.string "A la prochaine!\nEt n'oubliez pas:\l«VIVE LES {POKEBLOCK}S»!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Salut!\pJe suis fan de {STR_VAR_1}.\nJe l'adore!\pEt toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Je vois, je vois. C'est donc ce que tu\npenses de ce DRESSEUR.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Est-ce que tu as tout oublié sur\n{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Je suis fan de {STR_VAR_1}.\nJe l'adore!\pEt toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Sur 100, tu mettrais combien à\n{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Est-ce que tu as tout oublié sur\n{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, je vois!\pMais tu devrais vraiment rencontrer\n{STR_VAR_1}.\pTu deviendras vite fan, je n'ai aucun\ndoute là-dessus.$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Je vois, je vois.\pMerci!\nC'est bon à savoir.\pJe partagerai l'info avec d'autres\nfans de {STR_VAR_1} et en discuterai\lavec eux!$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Il va bientôt y avoir un reportage sur\n{STR_VAR_1} à la télé.\pJ'espère que tu pourras le voir!$"

gTVTrainerFanClubSpecialText00::
	.string "FAN CLUB DES DRESSEURS\nREPORTAGE SPECIAL SUR {STR_VAR_1}!\pCeci est une émission spéciale pour\ntous les fans de {STR_VAR_1}\là travers HOENN!\pAujourd'hui, nous vous avons demandé\nce que vous pensiez de {STR_VAR_1}.\pNous avons posé la question à\n{STR_VAR_2} comme représentant des\lDRESSEURS.\pNous avons demandé: «En un mot,\ncomment décririez-vous {STR_VAR_1}?»\pSa réponse: «{STR_VAR_3}».\pBravo à {STR_VAR_2}!\nQuelle perspicacité!\p{STR_VAR_2} a également noté la force\nde {STR_VAR_1} de 0 à 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Le score est de {STR_VAR_3} points!\nC'est un score vraiment très important!\p{STR_VAR_2} doit certainement avoir\nune très haute opinion de {STR_VAR_1}!$"

gTVTrainerFanClubSpecialText02::
	.string "Le score est de {STR_VAR_3} points!\nC'est un bon score!\p{STR_VAR_2} doit considérer\n{STR_VAR_1} comme un véritable\ladversaire!$"

gTVTrainerFanClubSpecialText03::
	.string "Le score est de {STR_VAR_3} points!\nC'est un score plutôt faible!\p{STR_VAR_2} doit juste considérer\n{STR_VAR_1} comme une simple relation.$"

gTVTrainerFanClubSpecialText04::
	.string "Le score est de {STR_VAR_3} point(s)!\nC'est un score ridicule!\p{STR_VAR_2} doit avoir une bien\nmauvaise impression de {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText05::
	.string "Voilà les amis!\pJe crois que nous venons d'apprendre\nquelque chose sur {STR_VAR_1}.\pPour finir, je vous laisse avec la\nparole du jour de {STR_VAR_2}.\p{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Et maintenant, c'est l'heure de…\nVOYANCE POKéMON.\pJe peux prédire l'avenir de votre\nPOKéMON en fonction de son surnom.\pJe ne donne que des conseils, mais\ncroyez-moi, ces conseils sont utiles.\pAujourd'hui, je vais lire l'avenir dans\nle surnom {STR_VAR_3} du {STR_VAR_2}\lde {STR_VAR_1}.\pHumm…\pHum…\nCe surnom est…$"

gTVNameRaterText01::
	.string "Un surnom qui laisse deviner de\nnombreux talents, divers et variés.\pJe recommande à ce DRESSEUR de relever\ncourageusement un max de défis.$"

gTVNameRaterText02::
	.string "Un surnom qui complète parfaitement\n{STR_VAR_1}, le nom du DRESSEUR.\pCela suggère qu'ils forment une bonne\néquipe en parfaite harmonie.$"

gTVNameRaterText03::
	.string "Un surnom qui met en avant la\npersonnalité unique du POKéMON!\pS'il est élevé correctement, ce POKéMON\naffinera son caractère exceptionnel!$"

gTVNameRaterText04::
	.string "Un surnom qui montre bien l'attention\net la compassion de ce POKéMON.\pS'il est élevé correctement, ce POKéMON\nfera preuve d'une grande affection.$"

gTVNameRaterText05::
	.string "Un très joli surnom qui suggère un\navenir prometteur.\pJe me demande ce que l'avenir réserve\nà ce POKéMON.$"

gTVNameRaterText06::
	.string "Un chouette surnom qui devrait\ngarantir une bonne santé à ce POKéMON!\pCe POKéMON aura une constitution\nrobuste pendant très longtemps.$"

gTVNameRaterText07::
	.string "Un chouette surnom qui donnera\nbeaucoup d'énergie à ce POKéMON!\pTout porte à croire que ce POKéMON\nsera excellent pendant les combats.$"

gTVNameRaterText08::
	.string "Un surnom plaisant qui rend ce\nPOKéMON très charmant!\pAucun doute possible, ce POKéMON aura\ndu succès pendant les CONCOURS.$"

gTVNameRaterText09::
	.string "La racine du surnom {STR_VAR_1}\ns'appuie sur la lettre «{STR_VAR_3}».\pCette lettre est soutenue par la\npremière lettre, «{STR_VAR_2}», qui confère\lune forte présence au surnom.$"

gTVNameRaterText10::
	.string "Le surnom {STR_VAR_1} est très\nharmonieux et très agréable.\pLa présence des lettres «{STR_VAR_2}» et\n«{STR_VAR_3}» est particulièrement bienvenue!$"

gTVNameRaterText11::
	.string "Le surnom {STR_VAR_1} révèle une\nmagnificence et une fluidité certaines.\pLe passage de la lettre «{STR_VAR_2}» à la lettre\n«{STR_VAR_3}» est formidable.$"

gTVNameRaterText12::
	.string "Etudions d'autres exemples de surnoms,\nsi vous le voulez bien!$"

gTVNameRaterText13::
	.string "Par exemple, prenons une partie du nom\ndu DRESSEUR {STR_VAR_1}, ce qui\lpourrait donner un super surnom: {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "{STR_VAR_2}{STR_VAR_3} pourrait aussi être une\nbonne idée de surnom.$"

gTVNameRaterText15::
	.string "Le nom de l'espèce du POKéMON,\n{STR_VAR_2}, pourrait servir de point de\ldépart au surnom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} serait également un\nsurnom efficace.$"

gTVNameRaterText17::
	.string "En revanche, il faut éviter d'utiliser le\nnom d'espèce d'un autre POKéMON.\pPar exemple, il ne faut pas prendre le\nnom {STR_VAR_2} pour créer le surnom\l{STR_VAR_1}{STR_VAR_3}. C'est inacceptable.$"

gTVNameRaterText18::
	.string "Mais il faut bien admettre que\n{STR_VAR_1} est un bon surnom.\pEspérons que ce DRESSEUR continuera\nà traiter {STR_VAR_1} avec amour.\pVoilà! C'est fini pour aujourd'hui.\nNe ratez pas notre prochaine émission.$"

gTVPokemonAnglerText00::
	.string "PECHE AU {STR_VAR_2}\pPRESENTATEUR: Salut! Aujourd'hui, nous\napprenons à pêcher le {STR_VAR_2}.\pVous, le PRO DE LA PECHE, quel\nconseil donneriez-vous pour la pêche\lau {STR_VAR_2}?\pPRO DE LA PECHE: Hein? La pêche au\n{STR_VAR_2}? Eh bien, tout d'abord,\lsoyez patients. C'est la base de tout.\pVous voyez {STR_VAR_1}, là-bas?\nCe DRESSEUR est un bon exemple.\pIl a déjà laissé filer {STR_VAR_3}\nPOKéMON.\pEt pourtant, {STR_VAR_1} attend, sans\nabandonner. C'est ainsi qu'on attrape\ldes {STR_VAR_2}.\pPRESENTATEUR: Je vois…\pOh! {STR_VAR_1} a finalement attrapé\nun {STR_VAR_2} récalcitrant!\pLe DRESSEUR est sur le point\nde pleurer de joie!\pQuand je vois ce genre de regard, ça\nme donne envie de pêcher!\pTéléspectateurs, pourquoi ne pas\nvous mettre à la pêche au {STR_VAR_2}?\pEn attendant notre prochaine émission,\nbonne pêche à tous!$"

gTVPokemonAnglerText01::
	.string "PECHE AU {STR_VAR_2}\pPRESENTATEUR: Salut! Aujourd'hui, nous\napprenons à pêcher le {STR_VAR_2}.\pVous, le PRO DE LA PECHE, quel\nconseil donneriez-vous pour la pêche\lau {STR_VAR_2}?\pPRO DE LA PECHE: Hein? La pêche au\n{STR_VAR_2}? Eh bien, tout d'abord,\ltenez votre CANNE énergiquement!\pVous voyez {STR_VAR_1}, là-bas?\nVous voyez comment il tient sa CANNE?\pCe DRESSEUR vient d'en attraper\n{STR_VAR_3} de suite.\pPRESENTATEUR: C'est incroyable!\nC'est une véritable razzia…\pQuand je vois une telle technique, ça\nme donne envie de pêcher!\pTéléspectateurs, pourquoi ne pas\nvous mettre à la pêche au {STR_VAR_2}?\pEn attendant notre prochaine émission,\nbonne pêche à tous!$"

gTVPokemonTodayFailedText00::
	.string "Bonjour!\pC'est l'heure de POKéMON D'UN JOUR!\pFRANGINE: Salut à tous! Est-ce que\ntout le monde a la pêche aujourd'hui?\pDans cette émission, nous allons voir\n{STR_VAR_2}, le POKéMON de {STR_VAR_1}!\pFRANGIN: Absolument! C'est notre\nprogramme de la journée!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\nPuisqu'on parle de {STR_VAR_1}…\pFRANGINE, j'ai vu ce DRESSEUR de\nmes propres yeux!\pFRANGINE: Oh, vraiment?\pFRANGIN: Oui, j'étais en voyage à\n{STR_VAR_2}.\pEt je suis tombé sur {STR_VAR_1}, qui\nessayait d'attraper le POKéMON\l{STR_VAR_3}, mais malheureusement…$"

gTVPokemonTodayFailedText02::
	.string "Le POKéMON a réussi à s'échapper!\pFinalement, le DRESSEUR a gaspillé\n{STR_VAR_2} POKé BALLS!\pIl fallait voir la déception dans les\nyeux de {STR_VAR_1} au moment où\lle POKéMON s'est enfui!$"

gTVPokemonTodayFailedText03::
	.string "{STR_VAR_1} a fait une gaffe et le POKéMON\ns'est retrouvé K.O.!\pFinalement, le DRESSEUR a gaspillé\n{STR_VAR_2} POKé BALLS!\pIl fallait voir le désarroi dans les\nyeux de {STR_VAR_1} au moment où\lle POKéMON a été mis K.O.!$"

gTVPokemonTodayFailedText04::
	.string "FRANGINE: Hé!\nCe n'est pas très sympa!\pIl ne faut pas se moquer du malheur\ndes autres!\pPauvre {STR_VAR_1}.\nQuel dommage!\pFRANGIN: C'est vrai!\nDésolé de m'être moqué.$"

gTVPokemonTodayFailedText05::
	.string "FRANGINE: Hi hi hi…\pFRANGIN: Hé!\nTu viens de rire!\pFRANGINE: Hein?!\pJe n'ai pas rigolé!\nHonnêtement!\pPauvre {STR_VAR_1}.\nQuel dommage!\pFRANGIN: …$"

gTVPokemonTodayFailedText06::
	.string "FRANGINE: Finies les bêtises!\nVoyons donc le POKéMON du jour…\pQuoi?\nNotre temps est déjà écoulé?\pOh non!\nNous n'avons eu le temps de\lprésenter aucun POKéMON!\pFRANGIN: A la prochaine!\pFRANGINE: Hé, ne terminez pas\nl'émission sans moi!$"

gTVPokemonTodaySuccessfulText00::
	.string "Bonjour!\pC'est l'heure de POKéMON D'UN JOUR!\pFRANGINE: Salut à tous! Est-ce que\ntout le monde a la pêche aujourd'hui?\pDans cette émission, nous allons voir\n{STR_VAR_2}, le POKéMON de {STR_VAR_1}!\pFRANGIN: Absolument! C'est notre\nprogramme de la journée!$"

gTVPokemonTodaySuccessfulText01::
	.string "FRANGINE: {STR_VAR_1} a surnommé son\n{STR_VAR_2} {STR_VAR_3}!\pApparemment, {STR_VAR_3} est\nparticulièrement choyé!$"

gTVPokemonTodaySuccessfulText02::
	.string "FRANGIN: Ce DRESSEUR a dû lancer\n{STR_VAR_3} BALL(S) pour l'attraper!\pHé, tu te rends compte? Une seule\n{STR_VAR_2} a suffi à l'attraper!$"

gTVPokemonTodaySuccessfulText03::
	.string "FRANGINE: S'il était si facile à\nattraper, c'est que le destin a voulu\lréunir {STR_VAR_1} et {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "FRANGINE: Ouah! C'est génial!\pMais comme on dit, un POKéMON\ndifficile à attraper est assuré\ld'obtenir l'amour de son DRESSEUR!$"

gTVPokemonTodaySuccessfulText05::
	.string "FRANGINE: Le {STR_VAR_2} de {STR_VAR_1}\nest un POKéMON mémorable car il a\lfallu une MASTER BALL pour l'attraper!\pFRANGIN: Ouah! C'est incroyable!\pFRANGINE: {STR_VAR_1} devait vraiment\nvouloir ce {STR_VAR_2}, pas de doute!$"

gTVPokemonTodaySuccessfulText06::
	.string "FRANGIN: Puis, ce DRESSEUR a surnommé\nson {STR_VAR_2} {STR_VAR_3}…\pÇa donne une bonne idée de l'état\nd'esprit de {STR_VAR_1}.\pFRANGINE: Je suis d'accord!$"

gTVPokemonTodaySuccessfulText07::
	.string "Moi en revanche, j'aurais donné ce\nsurnom à un {STR_VAR_3}!\pFRANGIN: Hé! Mais ça pourrait être\nle début d'une nouvelle mode!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} le {STR_VAR_1}!\nÇa sonne bien, non?\pLes lettres, la prononciation, tout\ncolle parfaitement au POKéMON\l{STR_VAR_1}!\pFRANGIN: Oui, c'est vrai!$"

gTVPokemonTodaySuccessfulText09::
	.string "A ma connaissance, aucun DRESSEUR\nn'a jamais donné le surnom {STR_VAR_2}\là un {STR_VAR_1}!\pFRANGIN: Cela prouve le bon goût de\nce DRESSEUR en matière de surnoms!$"

gTVPokemonTodaySuccessfulText10::
	.string "La prochaine fois que j'attrape un\nPOKéMON, je l'appelle {STR_VAR_2}.\pFRANGIN: Vraiment? Moi aussi!\nJe l'appellerai {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "FRANGINE: Oh, non!\nL'heure tourne!\pBon, les amis, c'est fini pour\naujourd'hui. Au revoir et à bientôt!\pFRANGIN: N'oubliez pas, votre\nPOKéMON pourrait être le sujet\lde la prochaine émission!$"

SmartShopper_Text_Intro::
	.string "Bonjour à tous!\pC'est l'heure du POKéACHAT.\pJOURNALISTE: Comment vont nos\ntéléspectateurs?\pAujourd'hui, nous visitons une boutique\nà {STR_VAR_2}.\pVoyons donc ce que nos vendeuses\nont à nous proposer!$"

SmartShopper_Text_ClerkNormal::
	.string "Interrogeons cette vendeuse pour\nsavoir quelle est la tendance.\pBonjour, comment vont les affaires?\pVENDEUSE: Oh, très très bien.\pEn ce moment, l'objet {STR_VAR_2} se\nvend beaucoup.\pPar exemple, l'autre jour, un DRESSEUR\nappelé {STR_VAR_1} en a acheté {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "JOURNALISTE: Le DRESSEUR en a acheté\n{STR_VAR_3}? Impressionnant!\pA mon avis, {STR_VAR_1} se préparait à\neffectuer un long voyage dans des\lcontrées lointaines.\pIl faut toujours avoir ce type\nd'objet quand on voyage!$"

SmartShopper_Text_RandomComment2::
	.string "JOURNALISTE: Puisqu'on parle de l'objet\n{STR_VAR_2}, j'en ai justement acheté\l{STR_VAR_3} récemment.\pAprès tout, c'est un super objet!$"

SmartShopper_Text_RandomComment3::
	.string "JOURNALISTE: Combien de fois l'objet\n{STR_VAR_2}?! {STR_VAR_3}?!\pJe n'aurais jamais cru que quelqu'un\nen achèterait autant.\pBon sang, je ne peux pas me permettre\nd'en acheter autant que ça, moi…$"

SmartShopper_Text_RandomComment4::
	.string "JOURNALISTE: Une fois, j'ai acheté\nun lot complet de l'objet {STR_VAR_2}.\pMais finalement, il y en avait trop.\nJ'ai fini par le regretter…\pDepuis, je n'achète que ce qui est\nstrictement nécessaire…\pHeu…\pEvidemment, ça n'intéresse personne!$"

SmartShopper_Text_SecondItem::
	.string "VENDEUSE: {STR_VAR_1} a aussi acheté\nl'objet {STR_VAR_2}. Il en a pris {STR_VAR_3}.\pJOURNALISTE: Oh, bonne idée.\nC'est un objet très utile aussi.$"

SmartShopper_Text_ThirdItem::
	.string "VENDEUSE: Et le DRESSEUR a aussi\nacheté {STR_VAR_3} exemplaires de\ll'objet {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "VENDEUSE: En plus, c'était pendant les\nsoldes. Malin, non?$"

SmartShopper_Text_OutroNormal::
	.string "JOURNALISTE: Hum… {STR_VAR_1} semble\naimer faire des économies!\pLe total des achats de {STR_VAR_1}\ns'est finalement élevé à…\p{STR_VAR_2}¥?!\nUne sacrée somme!\pOh! Mince! Notre temps est écoulé!\nRendez-vous à la prochaine émission!$"

SmartShopper_Text_IsVIP::
	.string "VENDEUSE: {STR_VAR_1} fait partie de ma\nclientèle privilégiée, c'est sûr.$"

SmartShopper_Text_ClerkMax::
	.string "Interrogeons cette vendeuse pour\nsavoir quelle est la tendance.\pBonjour, comment vont les affaires?\pVENDEUSE: Oh, les affaires marchent\ntrès fort. Nous avons du mal à suivre.\pRécemment, un DRESSEUR du nom\nde {STR_VAR_1} a acheté un lot de l'objet\l{STR_VAR_2}.\pLe DRESSEUR a pratiquement épuisé\nnotre stock pour cet objet.\pJe n'aurais jamais espéré qu'une seule\npersonne m'en achète autant.\lJe n'avais jamais vu ça!\pJOURNALISTE: Combien en avez-vous\nvendu, finalement? 100, 200?\pVENDEUSE: Oh, non, bien plus que ça!\pJOURNALISTE: Bon sang, {STR_VAR_1} aime\nvraiment faire du shopping!\pVENDEUSE: {STR_VAR_1} fait partie de ma\nclientèle privilégiée, c'est sûr.$"

SmartShopper_Text_OutroMax::
	.string "JOURNALISTE: Hum…\nC'est vraiment étonnant.\pPourquoi un DRESSEUR a-t-il\nbesoin d'en acheter autant?\p… …\pLe mystère demeure, mais nous\nn'avons malheureusement plus de temps.\pRendez-vous à la prochaine émission!\pLe mystère de {STR_VAR_1} reste entier…$"

gTVWorldOfMastersText00::
	.string "CULTURE POKéMON\pBonjour, chers téléspectateurs.\pVous avez peut-être déjà entendu\nparler d'un DRESSEUR appelé {STR_VAR_1}.\p{STR_VAR_1} est célèbre dans l'art\nd'attraper des POKéMON.\pLa quête de POKéMON de {STR_VAR_1}\ndépend essentiellement de ses longues\lrecherches effectuées à pied.\pLors d'un jour mémorable, ce DRESSEUR\na effectué {STR_VAR_2} pas.\pLe nombre total de POKéMON attrapés\nce jour-là fut de {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Cet exploit remarquable n'a été\npossible que grâce à la formidable\lentente entre le DRESSEUR et son\l{STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Le DRESSEUR a attrapé son dernier\n{STR_VAR_3} près de {STR_VAR_2}.\pCe POKéMON a la particularité d'être\nun véritable détenteur de records.\pNous espérons que ça donnera envie aux\nDRESSEURS expérimentés de faire mieux.\pC'est tout pour aujourd'hui.\nA la prochaine.$"

gTVTodaysRivalTrainerText00::
	.string "LE RIVAL DU JOUR!\pBonjour, chers DRESSEURS de POKéMON!\nComment allez-vous, aujourd'hui?\pComme chaque jour, nous allons\nparler d'un DRESSEUR rival!$"

gTVTodaysRivalTrainerText07::
	.string "Le rival du jour est {STR_VAR_1}.\nOù est notre rival? {STR_VAR_3}!\p{STR_VAR_1} a enregistré {STR_VAR_2}\nPOKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "Le rival du jour est {STR_VAR_1}.\nNotre rival est dans une BASE SECRETE!\p{STR_VAR_1} a enregistré {STR_VAR_2}\nPOKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "Le rival du jour est {STR_VAR_1}.\p{STR_VAR_1} a enregistré {STR_VAR_2}\nPOKéMON dans son POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "Le rival du jour est {STR_VAR_1}.\nNotre rival se trouve sur le ferry.\p{STR_VAR_1} a enregistré {STR_VAR_2}\nPOKéMON dans son POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Combien de BADGES a notre rival?\nEh bien, il en a {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Mais notre rival n'a aucun BADGE!$"

gTVTodaysRivalTrainerText03::
	.string "Notre rival n'a aucun symbole de la\nZONE DE COMBAT.$"

gTVTodaysRivalTrainerText04::
	.string "Voyons combien de symboles de la\nZONE DE COMBAT notre rival a-t-il.\pSymboles or: {STR_VAR_1}!\nSymboles argent: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Notre rival a obtenu {STR_VAR_1} POINT(s)\nDE COMBAT à la ZONE DE COMBAT.$"

gTVTodaysRivalTrainerText06::
	.string "Alors? Feriez-vous le poids face\nà {STR_VAR_1}?\pL'aventure continue!\pTrès chers DRESSEURS!\pIl faut toujours aller de l'avant et\nsurtout aller au devant de ses rivaux!$"

TrendWatcher_Text_Intro::
	.string "CHAINE «IN» DE MYOKARA!\pANIMATEUR: Quoi d'neuf chez vous?\nNous vous tenons au courant des\ldernières modes à MYOKARA.\pAvec nous aujourd'hui, un vieux loup de\nmer. Il en sait un paquet sur MYOKARA!\pVieil homme: Je suis content\nd'être ici.\pANIMATEUR: Allons, pas de blabla,\npas de chichi entre nous! Droit au but!\pQu'est-ce qui est à la mode à\nMYOKARA, en ce moment?\pVieil homme: {STR_VAR_1}\n{STR_VAR_2}.\pANIMATEUR: {STR_VAR_1}\n{STR_VAR_2}?\pVieil homme: Non.\p{STR_VAR_1} {STR_VAR_2} n'a jamais\nété très à la mode.\pJe peux en parler, si vous le\nsouhaitez.\pANIMATEUR: Heu… Non merci!\nOn s'intéresse à ce qui est à la mode…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Vieil homme: {STR_VAR_3} de\nBOURG-EN-VOL m'a dit que {STR_VAR_1}\l{STR_VAR_2} était à la mode…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Vieil homme: {STR_VAR_3} de\nBOURG-EN-VOL m'a dit que {STR_VAR_1}\l{STR_VAR_2} était à la mode…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Mais ça n'a pas marché.\pFestival {STR_VAR_1} {STR_VAR_2}!\pConcours {STR_VAR_1} {STR_VAR_2}!\pJ'ai essayé d'en parler autour\nde moi, mais…\pPeut-être que c'est {STR_VAR_1} qui\nn'a pas plu…\pANIMATEUR: C'est bien joli, tout ça…\nMais qu'est-ce qui est à la mode, alors?$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Vieil homme: {STR_VAR_3}!\nY a-t-il quelque chose au-dessus de\l{STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Vieil homme: {STR_VAR_3}!\nY a-t-il quelque chose au-dessus de\l{STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_Outro::
	.string "ANIMATEUR: Hum… Heu, c'était l'info\ndu jour!\p{STR_VAR_1} {STR_VAR_2}… Eh bien…\nCe n'est pas à la mode à MYOKARA!\pC'est fini pour aujourd'hui. A plus!\pVieil homme: {STR_VAR_1}\n{STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "CHASSE AU TRESOR A HOENN!\pSalut, vous… De nouveaux objets\nsecrets ont-il été trouvés?\pNous sommes avides de témoignages\nsur les trésors qui nous entourent!\pNous avons reçu une lettre. Son sujet\nest «Découverte {STR_VAR_1}»!$"

gTVHoennTreasureInvestigatorsText01::
	.string "Oh! Je ferais bien de lire cette lettre\njusqu'au bout!\p«Chers CHASSEURS,\nj'espère que vous vous portez bien.\pRécemment, j'ai vu {STR_VAR_2} dans les\nenvirons de {STR_VAR_3}.\pCe DRESSEUR a trouvé l'objet\n{STR_VAR_1}. Comme je l'envie!»\pEh bien, nous nous réjouissons\npour {STR_VAR_2}!\pChers téléspectateurs, à vos\nCHERCH'OBJETS!\pEt pensez à nous si vous tombez sur\nla perle rare!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Oh! Je ferais bien de lire cette lettre\njusqu'au bout!\p«Chers CHASSEURS,\nj'espère que vous vous portez bien.\pRécemment, j'ai vu {STR_VAR_2} sur un\nferry.\pCe DRESSEUR a trouvé l'objet\n{STR_VAR_1}. Comme je l'envie!»\pEh bien, nous nous réjouissons\npour {STR_VAR_2}!\pChers téléspectateurs, à vos\nCHERCH'OBJETS!\pEt pensez à nous si vous tombez sur\nla perle rare!$"

gTVFindThatGamerText00::
	.string "LE JOUEUR DU JOUR!\pBien le bonjour, amis joueurs!\nTout se passe bien avec la\l{STR_VAR_2}?\pComme d'habitude, nous vous présentons\nun DRESSEUR qui est venu tenter sa\lchance au CASINO!\pNotre joueur du jour est…\n{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} a gagné {STR_VAR_3} JETONS à\nla {STR_VAR_2}.\p«{STR_VAR_1} est là, rassemblez tous\nles JETONS, on en aura besoin!»\pC'est ce que les employés du CASINO\ndisent quand {STR_VAR_1} arrive!\pSi vous rencontrez {STR_VAR_1} au\nCASINO, regardez comme ce DRESSEUR\ls'y prend à la {STR_VAR_2}.\pNous étions en direct du CASINO.\nLa tension est à son comble, ici!\pCe sera tout pour aujourd'hui!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} a perdu {STR_VAR_3} JETONS à\nla {STR_VAR_2}.\p«Quand {STR_VAR_1} est là, notre vente\nde JETONS augmente.»\pC'est ce que les employés du CASINO\ndisent sur {STR_VAR_1}!$"

gTVFindThatGamerText03::
	.string "Si vous rencontrez {STR_VAR_1} au\nCASINO devant une {STR_VAR_2},\lne l'imitez pas!\pNous étions en direct du CASINO.\nLa tension est à son comble, ici!\pCe sera tout pour aujourd'hui!$"

gTVBreakingNewsText00::
	.string "CHAINE DES SCOOPS!$"

gTVBreakingNewsText01::
	.string "Un {STR_VAR_2} rare attrapé par\n{STR_VAR_1}!\pNous sommes en direct à proximité\nde {STR_VAR_3}!\p{STR_VAR_1} a réussi à capturer un\n{STR_VAR_2} rare ici même!$"

gTVBreakingNewsText02::
	.string "Quand {STR_VAR_1} a rencontré le\n{STR_VAR_2} rare, le POKéMON\l{STR_VAR_3} a été envoyé au combat.$"

gTVBreakingNewsText03::
	.string "Le DRESSEUR a naturellement eu recours\naux POKé BALLS. Il en a lancé {STR_VAR_1}.\pC'est avec une {STR_VAR_2} que le\nPOKéMON rare a été attrapé.$"

gTVBreakingNewsText04::
	.string "Les cris de triomphe de {STR_VAR_1}\nont résonné sur {STR_VAR_2}.\pJe dois dire que la prouesse de\n{STR_VAR_1} fait envie.\pVoilà, je vous dis à très bientôt!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} a failli attraper un\n{STR_VAR_2} rare!\pNous sommes en direct à proximité\nde {STR_VAR_3}!\pC'est ici que {STR_VAR_1} a failli\nattraper un {STR_VAR_2} rare!$"

gTVBreakingNewsText06::
	.string "Quand {STR_VAR_1} a rencontré le\n{STR_VAR_2} rare, le POKéMON\l{STR_VAR_3} a été envoyé au combat.$"

gTVBreakingNewsText07::
	.string "Le DRESSEUR a fait utiliser\n{STR_VAR_1} par {STR_VAR_2}.\pLe POKéMON rare s'est\nmalheureusement évanoui…$"

gTVBreakingNewsText12::
	.string "{STR_VAR_1} a paniqué à la vue\ndu {STR_VAR_2} rare.\pLe DRESSEUR a ordonné au\n{STR_VAR_3} d'attaquer.\pLe POKéMON rare s'est\nmalheureusement évanoui…$"

gTVBreakingNewsText08::
	.string "Les cris de frustration de {STR_VAR_1}\nont résonné sur {STR_VAR_2}…$"

gTVBreakingNewsText09::
	.string "{STR_VAR_1} était à court de\nPOKé BALLS.\pCe DRESSEUR a dû arrêter le\ncombat contre le {STR_VAR_2} rare.\pLes cris de frustration de {STR_VAR_1}\nont résonné sur {STR_VAR_3}…$"

gTVBreakingNewsText10::
	.string "{STR_VAR_2} a fui sans prévenir.\pLes cris de frustration de {STR_VAR_1}\nont résonné sur {STR_VAR_3}…$"

gTVBreakingNewsText11::
	.string "Je dois dire que c'est triste pour\n{STR_VAR_1}. J'ai envie de hurler aussi!\pVoilà, je vous dis à très bientôt!$"

gTVSecretBaseVisitText00::
	.string "Salut les amis!\nC'est le moment d'effectuer une petite\lVISITE DE BASE SECRETE.\pAujourd'hui, nous allons découvrir la\nBASE SECRETE de {STR_VAR_1}.\pA quoi ressemble la BASE SECRETE\nde {STR_VAR_1}?\pNous allons voir ça tout de suite!\n… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\nMerveilleux!\p{STR_VAR_2}…\nCeci est pour le moins surprenant!$"

gTVSecretBaseVisitText02::
	.string "Oh!\nRemarquable!\pIl n'y a pas un seul élément de\ndécoration!\pC'est un très bon exemple de\nminimalisme!\pC'est très simple, mais ça en jette!\pChapeau, {STR_VAR_1}.\nJe te reconnais bien là!$"

gTVSecretBaseVisitText03::
	.string "Oh! Je vois!\nC'est très clair!\p{STR_VAR_2}… A cet endroit…\nLe message est fort!$"

gTVSecretBaseVisitText04::
	.string "Oh! Je vois!\nC'est très clair!\pLes décorations ne se bousculent\npas!\pLe message n'en est que plus fort!$"

gTVSecretBaseVisitText05::
	.string "Waouh!\p{STR_VAR_2}, {STR_VAR_3}…\nÇa se marie à merveille!\pOn ne pouvait pas rêver de meilleur\nchoix!$"

gTVSecretBaseVisitText06::
	.string "Waouh!\p{STR_VAR_2}…\nCet élément de décoration\lest très bien placé!\pSa présence remplit toute la\nBASE SECRETE!$"

gTVSecretBaseVisitText07::
	.string "Waouh!\pIl n'y a absolument rien ici.\pCet espace vide donne un certain\ncachet à la BASE SECRETE.$"

gTVSecretBaseVisitText08::
	.string "Oh!\nVoici {STR_VAR_1}!\lTestons un peu ce DRESSEUR!\p… … … … … …\n… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Oh…\n{STR_VAR_1} a gagné, je m'incline.\pLes POKéMON de ce DRESSEUR ont aussi\nmérité le titre de MAITRE.\pIls reflètent la résistance de\n{STR_VAR_1} en tant que DRESSEUR.\pLe {STR_VAR_2} connaissait même\n{STR_VAR_3}…\pÇa nous en dit long sur\n{STR_VAR_1}.\pQuelle belle leçon!$"

gTVSecretBaseVisitText10::
	.string "Aïe…\n{STR_VAR_1} a gagné, je m'incline.\pLes POKéMON de ce DRESSEUR sont\nincroyablement forts!\pIls reflètent la ténacité de\n{STR_VAR_1} en tant que DRESSEUR.\pLe {STR_VAR_2} connaissait même\n{STR_VAR_3}…\pÇa nous en dit long sur\n{STR_VAR_1}.\pQuelle belle leçon!$"

gTVSecretBaseVisitText11::
	.string "Waouh!\n{STR_VAR_1} a gagné, je m'incline.\pLes POKéMON de ce DRESSEUR sont\ntrès équilibrés.\pIls reflètent le sérieux de\n{STR_VAR_1} en tant que DRESSEUR.\pLe {STR_VAR_2} connaissait même\n{STR_VAR_3}…\pÇa nous en dit long sur\n{STR_VAR_1}.\pQuelle belle leçon!$"

gTVSecretBaseVisitText12::
	.string "Bien, bien!\n{STR_VAR_1} a gagné, je m'incline.\pLes POKéMON de ce DRESSEUR\nsont très prometteurs.\pIls reflètent les espoirs et les\nrêves de {STR_VAR_1}.\pLe {STR_VAR_2} connaissait même\n{STR_VAR_3}…\pÇa nous en dit long sur\n{STR_VAR_1}.\pQuelle belle leçon!$"

gTVSecretBaseVisitText13::
	.string "Cette BASE SECRETE était vraiment\nsuperbe, les amis! \pSi vous avez l'occasion, visitez la\nBASE SECRETE de {STR_VAR_1}.\pAllez, à la prochaine!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Quel suspense!\nQuelle tension!\pVoici le FLASH SPECIAL de la\nLOTERIE POKéMON!\pBonjour à tous, en direct de la LOTERIE\nPOKéMON, au rez-de-chaussée du\lCENTRE COMMERCIAL NENUCRIQUE!\pComme d'habitude, nous avons\nun heureux DRESSEUR!\pCe DRESSEUR s'appelle…\n{STR_VAR_1}!\p{STR_VAR_1} a gagné le\n{STR_VAR_2}, {STR_VAR_3}!\pFélicitations,\n{STR_VAR_1}!\pChers téléspectateurs,\nà vous de jouer maintenant!\pNous vous attendons avec impatience\nau CENTRE COMMERCIAL NENUCRIQUE!\pNous étions en direct du CENTRE\nCOMMERCIAL NENUCRIQUE pour\lvous, résidents de HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "TRAVAUX PRATIQUES POKéMON!\pNous étudions les combats de POKéMON\ndes autres et en tirons des leçons.\pNotre sujet d'aujourd'hui sera un\ncombat mené par {STR_VAR_1}.\pLe {STR_VAR_2} de {STR_VAR_1} s'est\nbattu contre un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Il a utilisé {STR_VAR_3} contre\nle {STR_VAR_2}…\pHum… {STR_VAR_1}!\nÇa ne va pas du tout!$"

gTVThePokemonBattleSeminarText02::
	.string "Notez que le {STR_VAR_1} de ce\nDRESSEUR connaissait également$"

gTVThePokemonBattleSeminarText03::
	.string "{STR_VAR_1}, {STR_VAR_2}\net {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "{STR_VAR_1} et\n{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Quelle capacité ce DRESSEUR aurait-il\ndû utiliser?\p… … … … … …\n{STR_VAR_1}, voyons!\p{STR_VAR_1} aurait été bien plus\nefficace que {STR_VAR_2}!\pChers téléspectateurs, j'espère que\nl'erreur de ce DRESSEUR vous servira!\pA la prochaine!$"

gTVTrainerFanClubText00::
	.string "Allez, tous ensemble!\nLE FAN CLUB DES DRESSEURS!\pANIMATEUR: Alors, ça groove chez vous?\nAujourd'hui, nous avons réuni tous\lles DRESSEURS fans de {STR_VAR_1}!\pFANS: Ouais!!!!!!!\pFANS: {STR_VAR_1}!\pANIMATEUR: Tous ensemble!\nEst-ce que vous aimez {STR_VAR_1}?\pFANS: On aime {STR_VAR_1}!\pANIMATEUR: Qu'est-ce qui vous plaît\nchez {STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Ce DRESSEUR a un super\nlancer de POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: On adore sa façon de courir!$"

gTVTrainerFanClubText03::
	.string "FANS: Ce DRESSEUR sait se montrer\nfort quand les choses se corsent!$"

gTVTrainerFanClubText04::
	.string "FANS: Ce DRESSEUR en connaît un rayon\nsur les POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: Ce DRESSEUR est d'une telle\ngentillesse avec les POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: Ce DRESSEUR a une super\ntechnique à VELO!$"

gTVTrainerFanClubText07::
	.string "FANS: Sa façon d'acheter des objets!$"

gTVTrainerFanClubText08::
	.string "FANS: Les surnoms que ce DRESSEUR\ndonne aux POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: Le goût avec lequel ce\nDRESSEUR a décoré sa BASE SECRETE!$"

gTVTrainerFanClubText10::
	.string "FANS: Ce DRESSEUR utilise les CT\navec un tel aplomb!$"

gTVTrainerFanClubText11::
	.string "ANIMATEUR: Comme vous avez vu,\n{STR_VAR_1} en jette!\pLes FANS de {STR_VAR_1}\nont un slogan!\pANIMATEUR: Quand je dis {STR_VAR_1},\nvous dites…\pFANS: {STR_VAR_2}!\pFANS: {STR_VAR_3}!\pFANS: {STR_VAR_2}!\pFANS: {STR_VAR_3}!\pANIMATEUR: Exactement! Si quelqu'un dit\n«{STR_VAR_1}»…\pIl faut répondre «{STR_VAR_2}\n{STR_VAR_3}»!\pJe dois avouer que ça sonne bien!\nJe comprends les FANS de {STR_VAR_1}!\pToi, en face de ta télé, avec nous!\nTous ensemble!\pANIMATEUR: Quand je dis {STR_VAR_1},\nvous dites…\pFANS: {STR_VAR_2}!\pFANS: {STR_VAR_3}!\pFANS: {STR_VAR_2}!\pFANS: {STR_VAR_3}!\pANIMATEUR: Je remercie tous les\nFANS de {STR_VAR_1}!\lQuelle ambiance ici!\pANIMATEUR: Quand je dis {STR_VAR_1},\nvous dites…\pFANS: {STR_VAR_2}!\pFANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "QU'ILS SONT MIGNONS!\nPOKéMON ENRUBANNES!\pBonjour, téléspectateurs chéris!\pIl n'y a rien de plus craquant qu'un\nPOKéMON avec des RUBANS, non?\pAujourd'hui, j'aimerais vous présenter\nun adorable POKéMON que j'ai remarqué\len ville.\pC'est le petit {STR_VAR_2}\nde {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Le nombre de RUBANS que\n{STR_VAR_2} portait était de {STR_VAR_3}.\pÇa montre à quel point {STR_VAR_1}\nadore ses POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} porte le nombre incroyable\nde {STR_VAR_3} RUBANS!\pÇa nous en dit long sur l'engagement\nde {STR_VAR_1} envers ses POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porte le nombre incroyable\nde {STR_VAR_3} RUBANS!\pÇa nous montre bien que {STR_VAR_1} se\nconsacre totalement à ses POKéMON!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Regardons de plus près les\nRUBANS de {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Le RUBAN CHAMPION est\nparticulièrement seyant.\p{STR_VAR_2} l'a reçu à son entrée au\nPANTHEON DES DRESSEURS.\pIl témoigne du courage de\n{STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN CHAMPION!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Le RUBAN SANG-FROID est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en remportant\nun CONCOURS DE SANG-FROID.\pIl témoigne du sang-froid\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN SANG-FROID!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Le RUBAN BEAUTE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en remportant\nun CONCOURS DE BEAUTE.\pIl rend hommage à la beauté\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN BEAUTE!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Le RUBAN GRACE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en remportant\nun CONCOURS DE GRACE.\pIl témoigne de la grâce\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN GRACE!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Le RUBAN INTELLIGENCE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en remportant\nun CONCOURS D'INTELLIGENCE.\pIl témoigne de l'intelligence\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN INTELLI-\nGENCE! Il lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Le RUBAN ROBUSTESSE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en remportant\nun CONCOURS DE ROBUSTESSE.\pIl témoigne de la robustesse\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN ROBUSTESSE!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Le RUBAN GAGNANT est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu pour ses\nexploits à la TOUR DE COMBAT.\pIl témoigne de la puissance\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN GAGNANT!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Le RUBAN VICTOIRE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu pour ses\nexploits à la TOUR DE COMBAT.\pIl témoigne de la puissance\nincroyable de {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN VICTOIRE!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Le RUBAN ARTISTE est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu en servant de\nmodèle à un artiste.\pIl témoigne du charme\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN ARTISTE!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Le RUBAN EFFORT est\nparticulièrement seyant.\p{STR_VAR_2} l'a obtenu pour avoir\nété un travailleur dévoué.\pIl témoigne de la détermination\nde {STR_VAR_2}.\p{STR_VAR_2} avec le RUBAN travailleur!\nIl lui va vraiment très bien!$"

TVSpotTheCuties_Text_Outro::
	.string "Oh…\pLes RUBANS et les POKéMON…\nIls vont si bien ensemble!\pJe vais défaillir, je préfère vous\ndire au revoir!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Bonjour à tous!\nC'est l'heure du BULLETIN POKéMON.\pNous avons des informations\nétonnantes en provenance de la\lZONE DE COMBAT.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi de la SALLE DE COMBAT SOLO\lde la TOUR DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi de la SALLE DE COMBAT DUO\lde la TOUR DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi de la SALLE DE COMBAT MULTI\lde la TOUR DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi de la SALLE DE COMBAT MULTI\lLINK de la TOUR DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord au TOURNOI DE COMBAT SOLO du\lDOME DE COMBAT en gagnant {STR_VAR_2} fois.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord au TOURNOI DE COMBAT DUO du\lDOME DE COMBAT en gagnant {STR_VAR_2} fois.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi du COMBAT ECHANGE SOLO\lde l'USINE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi du COMBAT ECHANGE DUO\lde l'USINE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord! Il a terminé {STR_VAR_2} salles lors\ldu défi du COMBAT HASARD du\lREPTILE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau TOURNOI K.O. du DOJO DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi du HALL DE COMBAT SOLO du\lPALACE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord de {STR_VAR_2} victoires consécutives\lau défi du HALL DE COMBAT DUO du\lPALACE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Le DRESSEUR {STR_VAR_1} a établi un\nrecord! Il a terminé {STR_VAR_2} niveaux\llors du défi du COMBAT QUETE de\lla PYRAMIDE DE COMBAT.\pBien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Ainsi qu'aux trois POKéMON: {STR_VAR_1},\n{STR_VAR_2}, et {STR_VAR_3}!\pFélicitations pour cet exploit\népoustouflant!!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Ainsi qu'aux deux POKéMON: {STR_VAR_1},\net {STR_VAR_2}!\pFélicitations pour cet exploit\népoustouflant!!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Et aux quatre POKéMON: {STR_VAR_1}!\p{STR_VAR_2}!\p{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Et {STR_VAR_1}!\pFélicitations pour cet exploit\népoustouflant!!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Nous attendons avec impatience de\nconnaître les prochains exploits de\l{STR_VAR_1} et de ses fidèles POKéMON!\pC'était le scoop du BULLETIN POKéMON!$"

gTVWhatsNo1InHoennTodayText00::
	.string "QUOI DE NEUF DANS HOENN?\nC'est reparti pour une émission\lde folie!\pSalut les amis, ça roule pour vous?\pPenchons-nous sur le DRESSEUR\nqui a fait parler de lui aujourd'hui!\pLe DRESSEUR nº 1 du jour n'est\nautre que {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Dans la même journée, {STR_VAR_1} a joué\n{STR_VAR_2} fois aux MACHINES A\lSOUS du CASINO.\pDes témoins auraient entendu\n{STR_VAR_1} murmurer: «Pour moi, les\lrouleaux ne bougent même pas…»\lIntéressant, non?$"

gTVWhatsNo1InHoennTodayText02::
	.string "Dans la même journée, {STR_VAR_1} a joué\n{STR_VAR_2} fois à la ROULETTE du\lCASINO.\pEn plein jeu, on a entendu {STR_VAR_1}\ncrier: «Que la bille décide!»\pLe visage du DRESSEUR affichait une\nconcentration extrême.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Dans la même journée, {STR_VAR_1} a\nbattu des POKéMON sauvages {STR_VAR_2} fois!\pLes POKéMON de {STR_VAR_1} semblent\nêtre devenus beaucoup plus forts.\pIls aiment se battre, peu importe\nl'endroit, le moment ou la manière!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Dans la même journée, {STR_VAR_1} a\nutilisé le MIXEUR {STR_VAR_2} fois!\pA la fin, {STR_VAR_1} avait la tête\nqui tournait.\pLe DRESSEUR titubait comme un\nSPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Dans la même journée, {STR_VAR_1} a\nplanté {STR_VAR_2} BAIES!\pDu coup, les vêtements de {STR_VAR_1}\nétaient couverts de terre.\pLà où ce DRESSEUR a semé, de\nnombreuses fleurs ont fleuri.\pOn dit que les fleurs apaisent\nles gens.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Dans la même journée, {STR_VAR_1} a\ncueilli {STR_VAR_2} BAIES!\pLe SAC de {STR_VAR_1} était tellement\nplein que ce DRESSEUR avait du\lmal à marcher!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Dans la même journée, {STR_VAR_1} a\nobtenu {STR_VAR_2} POINTS DE COMBAT!\p{STR_VAR_1} a eu du mal à décider contre\nquoi échanger ses POINTS DE COMBAT.\lIl a longuement hésité entre un objet\lsympa et une décoration chic.\pTrop de choix s'offraient à ce\nDRESSEUR.$"

gTVWhatsNo1InHoennTodayText08::
	.string "N'est-ce pas incroyable?\p{STR_VAR_1}!\nLe DRESSEUR nº 1!\pPrenez exemple sur {STR_VAR_1}!\nDevenez le nº 1 du jour!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRETS DE BASES SECRETES!\pSi les murs pouvaient parler, que nous\ndiraient ceux des BASES SECRETES?\pAujourd'hui, nous allons observer\nla BASE SECRETE de {STR_VAR_1}.\pOh? On dirait que {STR_VAR_2} vient\nd'arriver.\pObservons discrètement cette visite!\pQue va faire {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Que va faire {STR_VAR_2} maintenant?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Et maintenant, que va faire\n{STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Finalement, {STR_VAR_2} a fait {STR_VAR_3} pas\ndans la BASE SECRETE de {STR_VAR_1}\lavant de partir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hum…\pLa BASE SECRETE de {STR_VAR_1} ne\nsemble pas intéresser {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} a l'air de beaucoup aimer la\nBASE SECRETE de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} semble se trouver très à\nl'aise dans la BASE SECRETE de\l{STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "J'espère que nous vous aurons donné\nenvie d'aller faire un tour dans la BASE\lSECRETE de {STR_VAR_1}!\pA bientôt dans une autre BASE SECRETE!\nMais chut… c'est un secret…$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Notre visiteur est immobile!\pUne vraie statue!\pLa BASE SECRETE de {STR_VAR_1}\nserait-elle soporifique?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Notre visiteur est immobile!\pUne vraie statue!\pSerait-ce un accès de fatigue? Ou\nle signe d'un ennui profond?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Notre visiteur s'assoit sur une chaise!\pCette BASE SECRETE a l'air\nconfortable!\pCette chaise semble lui plaire\nénormément!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Notre visiteur s'en prend à un ballon!\pOh, non! Le ballon a éclaté,\nchers téléspectateurs!\pLe bruit semble avoir surpris notre\nvisiteur!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Notre visiteur est dans une TENTE!\pNotre visiteur se promène!\pNotre visiteur gambade!\pLa taille de cette TENTE a dû le\nsurprendre!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Notre visiteur observe une\nplante!\pNotre visiteur semble avoir un\ngoût très sûr.$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Notre visiteur observe un\nBOUCLIER OR!\pL'émerveillement se lit dans les yeux de\nnotre visiteur!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Notre visiteur observe un\nBOUCLIER ARGENT!\pNotre visiteur en prend plein les\nmirettes!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Notre visiteur observe un\nORNEMENT VERRE!\pOh, non!\pNotre visiteur le touche!\pIl va être couvert de traces de\ndoigts…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Notre visiteur regarde la télévision!\pCela semble l'intéresser au plus haut\npoint!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Notre visiteur a vu une\nBOULE DE BOUE!\pCela semble lui plaire!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "Oh?\pNotre visiteur a ouvert son SAC\net y cherche quelque chose!\p{STR_VAR_2}? C'est donc ça que notre\nvisiteur cherchait!\pRegardez le sourire de notre visiteur\nalors qu'il brandit l'objet!\pOn pourrait en faire une pub pour un\ndentifrice!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Notre visiteur saisit un coussin et…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "le frappe?!?\pNotre visiteur semble avoir besoin de\nse défouler un peu.$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "le sert bien fort dans ses bras!\pNotre visiteur a visiblement\nbesoin d'affection!$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Notre visiteur est en pleine discussion\navec {STR_VAR_1}!\pOn dirait qu'un combat se prépare!\pEt…\pC'est notre visiteur qui\nremporte le combat!\pNotre visiteur entame une danse de la\nvictoire!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Notre visiteur est en pleine discussion\navec {STR_VAR_1}!\pOn dirait qu'un combat se prépare!\pEt…\pC'est {STR_VAR_1} qui l'emporte!\nNotre pauvre visiteur a perdu!\pNotre visiteur a l'air de s'en\nvouloir!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Notre visiteur est en pleine discussion\navec {STR_VAR_1}!\pOn dirait qu'un combat se prépare!\pEt…\pNon, notre visiteur refuse de se\nbattre!\pIl n'y aura pas de combat!\p{STR_VAR_1} ne lui a pas plu?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Notre visiteur a les yeux rivés sur\nun poster!\pCe poster est-il au goût de notre\nvisiteur?\pMais… Le regard de notre\nvisiteur est pour le moins troublant.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Notre visiteur a marché sur un TAPIS\nNOTE!\pTiens… Notre visiteur a composé\nun air entraînant!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Notre visiteur est en pleine discussion\navec {STR_VAR_1}!\pOn dirait qu'un combat se prépare!\pEt…\pEgalité!\nUn combat pour rien.\pOn peut lire la déception sur le visage\ndes deux DRESSEURS!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Notre visiteur a marché sur un TAPIS\nTOURNANT!\pOn dirait que sa tête tourne!\pNotre visiteur ne marche plus très\ndroit!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Notre visiteur s'approche d'une\nDECO DE SABLE!\pOh!\pL'objet s'effrite!\nIl s'est cassé!\pNotre visiteur a l'air penaud!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Notre visiteur passe son doigt sur\nle bureau!\pLa poussière semble l'agacer!\pEh bien, notre visiteur semble être\ntrès attaché à la propreté!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Notre visiteur regarde une BRIQUE!\pPeut-être est-ce l'objet sur la BRIQUE\nqui intéresse notre visiteur?$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Notre visiteur marche sur une\nPLANCHE SOLIDE.\pNotre visiteur regarde en bas!\pNotre visiteur ne semble pas être\ntrès téméraire!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Notre visiteur contemple une\nBARRIERE!\pNotre visiteur serait-il en train de\nmanigancer quelque chose?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Notre visiteur est sur un\nTAPIS BRILLANT!\pNotre visiteur semble prendre la pose!\pNotre visiteur se prendrait-il pour une\nstar?$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Notre visiteur regarde un PNEU!\pNotre visiteur penserait-il à s'acheter\nune voiture?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Notre visiteur se trouve sur une\nESTRADE!\pNotre visiteur regarde la BASE SECRETE\nde {STR_VAR_1} d'en haut!\pEt…\pNotre visiteur se met à hurler!\nIncroyable!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Notre visiteur a foncé tête la première\ndans une PORTE CASSABLE!\pNotre visiteur est pris d'un fou rire!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Notre visiteur parle à une POUPEE!\pÇa donne la chair de poule…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Notre visiteur monte sur un\nTOBOGGAN!\pEt…\pglisse jusqu'en bas!\pOn dirait que notre visiteur\ns'amuse bien!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Notre visiteur monte sur un\nTOBOGGAN!\pEt…\pApparemment, il préfère redescendre!\pNotre visiteur aurait-il le vertige?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Notre visiteur se trouve sur un\nTAPIS SAUTEUR!\pNotre visiteur saute!\pEt saute encore!\pBelle réception au sol!\pNotre visiteur s'applaudit!\nUne jolie performance en solo!$"

gTVSafariFanClubText00::
	.string "FAN CLUB SAFARI!\pJOURNALISTE: Alors, les amis!\nEn train de lancer des SAFARI BALLS?\pComme vous vous en doutez, je suis\nau PARC SAFARI!\pDiscutons un peu avec le GUIDE\nSAFARI!\pComment se débrouillent les\nDRESSEURS aujourd'hui?$"

gTVSafariFanClubText01::
	.string "GUIDE: Ils ont tous l'air d'y mettre\ndu leur et de s'appliquer.\p{STR_VAR_1} réussit particulièrement\nbien.\p{STR_VAR_1} a attrapé {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Ce DRESSEUR sait utiliser les {POKEBLOCK}S.\nJe crois qu'il en a utilisé {STR_VAR_2}.$"

gTVSafariFanClubText03::
	.string "Ce DRESSEUR n'a pas utilisé un\nseul {POKEBLOCK}!\pDu travail de pro.$"

gTVSafariFanClubText04::
	.string "JOURNALISTE: Vraiment?\pOn dirait que notre {STR_VAR_1}\nexcelle au SAFARI!\pGUIDE: J'espère que ce DRESSEUR va\nrevenir nous montrer sa technique.$"

gTVSafariFanClubText05::
	.string "GUIDE: Ils ne semblent pas avoir\nbeaucoup de succès.\p{STR_VAR_1} s'est particulièrement\nmal débrouillé.\pCe DRESSEUR n'a attrapé que\n{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: Ils ne semblent pas avoir\nbeaucoup de succès.\p{STR_VAR_1} s'est particulièrement\nmal débrouillé.\pCe DRESSEUR n'a attrapé aucun\n POKéMON.$"

gTVSafariFanClubText07::
	.string "Ce DRESSEUR utilise des {POKEBLOCK}S.\nJe crois qu'il en a utilisé {STR_VAR_2}.\pJ'aimerais bien que ce DRESSEUR\ns'améliore un peu.$"

gTVSafariFanClubText08::
	.string "Je pense que ce DRESSEUR aurait\neu plus de chance en utilisant des\l{POKEBLOCK}S, chose qu'il n'a pas faite.$"

gTVSafariFanClubText09::
	.string "JOURNALISTE: Vraiment?\pOn dirait que le SAFARI et\n{STR_VAR_1}, ça fait deux!\pGUIDE: J'espère que ce DRESSEUR\nreviendra souvent pour s'entraîner.$"

gTVSafariFanClubText10::
	.string "JOURNALISTE: Bien sûr!\nIl ne faut pas baisser les bras!\pTéléspectateurs, venez au\nPARC SAFARI vous aussi!\pA la prochaine, ciao!$"

ContestLiveUpdates_Text_Intro::
	.string "«INFOS CONCOURS POKéMON»\pANIMATRICE: Merci de nous retrouver!\pNous sommes en direct depuis\nle nouveau site {STR_VAR_1}.\pLe hall est rempli du public\nqui ne souhaite pas partir.\pSpectateur: {STR_VAR_2}!\pSpectateur: {STR_VAR_3}!\pANIMATRICE: Comme vous venez de\nl'apprendre, le CONCOURS a été\lremporté par le {STR_VAR_2} de {STR_VAR_3}.\pSpectateur: {STR_VAR_2}!\nTu es le meilleur!\pSpectateur: {STR_VAR_3}!\nBien joué!\pANIMATRICE: Ecoutons voir ce que\nles fans ont à dire à propos\lde ce CONCOURS.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spectateur: {STR_VAR_2} était en tête\naux jugements préliminaire et\lsecondaire!\pCe {STR_VAR_2} est sur la bonne voie!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spectateur: {STR_VAR_2} n'a pas eu un\nbon résultat au jugement préliminaire,\pmais s'est rattrapé au jugement\nsecondaire!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spectateur: {STR_VAR_2} est resté\nconstant durant les deux jugements.\p{STR_VAR_3} et {STR_VAR_2} forment une\nsacrée paire!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spectateur: Du point de vue {STR_VAR_1},\nce {STR_VAR_2} a été exceptionnel.\pMais j'espère qu'il arrivera à nous\nsurprendre encore plus la prochaine\lfois.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spectateur: Quand le {STR_VAR_2} a\ncommencé à se montrer nerveux,\pje n'ai pas pu m'empêcher de crier\npour l'encourager.\pJe n'ai qu'un mot à dire à ce\n{STR_VAR_2}: félicitations!$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spectateur: Ce {STR_VAR_2} a réussi à\nm'enflammer!\p{STR_VAR_2}, tu as été formidable!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spectateur: Ce combo de {STR_VAR_2}\nétait à couper le souffle!\pJ'en tremble encore!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spectateur: La démonstration du\n{STR_VAR_2} gagnant a fait vibrer\lmon cœur!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}! Tu as fait preuve d'un\nsang-froid incroyable!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\nC'était de toute beauté!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\nC'était super gracieux!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\nTu as fait preuve d'intelligence!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\nTu as su montrer ta robustesse!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spectateur: La démonstration du\n{STR_VAR_2} gagnant fait toujours\lvibrer mon cœur!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\nTu incarnes le sang-froid!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\nTu incarnes la beauté!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\nTu incarnes la grâce!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\nComment fais-tu pour être aussi\lintelligent?$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\nQuelle robustesse!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spectateur: Je n'ai pas réussi à quitter\n{STR_VAR_2} du regard, même après\lsa démonstration.\pCe {STR_VAR_2} arrive vraiment à me\ncaptiver!$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spectateur: J'étais au bord des larmes\nquand {STR_VAR_2} s'est fait surprendre\ppar la démonstration d'un\nautre POKéMON.\pMais tu as su tenir, {STR_VAR_2}!\nBien joué!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spectateur: Oh!\pCette capacité {STR_VAR_3} de\n{STR_VAR_2}!\pComment arrive-t-il à faire des\nchoses pareilles?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "ANIMATRICE: Cet endroit est rempli\nde fans de {STR_VAR_1}!\pMais je dois vous avouer qu'un autre\nPOKéMON a attiré mon attention,\lle {STR_VAR_3} de {STR_VAR_2}!\p{STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "A cause de sa nervosité, il n'a pas\npu réussir une seule démonstration\ldurant le jugement secondaire.\pLa prochaine fois, j'aimerais que\n{STR_VAR_1} en réussisse au moins une.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Il est arrivé bon dernier aux deux\njugements.\pJ'espère que {STR_VAR_1} va se rattraper\navec {STR_VAR_2} pour se faire\lpardonner cette dernière place!$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Il n'a pas réussi à profiter de\nl'ambiance dans le public pour\lfaire une démonstration appropriée.\pNous espérons que {STR_VAR_1} apprendra\nà saisir leur humeur pour changer leurs\lencouragements en une vraie clameur!$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Bien qu'étant en tête à la fin du\njugement préliminaire, il n'a pas réussi\pà en tirer avantage pendant le\njugement secondaire.\pQuelle humiliation, tout ça pour\nrien!\p{STR_VAR_1} doit certainement être en\ntrain de réfléchir à la manière de\lréussir ses prochaines démonstrations.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Le public ne s'est jamais véritablement\nenflammé pour ses démonstrations\lpendant le jugement secondaire.\pNous espérons qu'il arrêtera de trop\npenser aux autres POKéMON pour\lse concentrer sur ses démonstrations!$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Il a perdu de peu contre le {STR_VAR_2}\nde {STR_VAR_1}!\pJe n'ose imaginer ce qu'il doit ressentir\naprès avoir échoué si près de la\lvictoire!\pÇa ne me surprendrait pas que\n{STR_VAR_3} craque et se mette à pleurer.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Il a déçu le JUGE en répétant encore\net encore les mêmes démonstrations.\pC'est une erreur impardonnable dans\nun CONCOURS, et ce POKéMON\len fait les frais.\p{STR_VAR_1} devrait avoir honte de nous\navoir montré ça.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} a vraiment fait de son mieux,\nmais…\pÇa n'a servi à rien, il est arrivé dernier.\p{STR_VAR_1} devrait réfléchir à cette\ndéfaite et en tirer les conclusions.$"

ContestLiveUpdates_Text_Outro::
	.string "J'aimerais terminer cette émission\nen félicitant les gagnants.\pCette fois, il s'agit de {STR_VAR_2}\net {STR_VAR_1}!\pANIMATRICE: Est-ce que tout le\nmonde est prêt?\lTous ensemble!\pPublic: {STR_VAR_1}! {STR_VAR_2}!\nFélicitations!\lVous avez gagné le CONCOURS!$"

gTVPokemonBattleUpdateText00::
	.string "«INFOS COMBATS POKéMON»\pNous vous donnons les derniers\nrésultats des combats de POKéMON!$"

gTVPokemonBattleUpdateText01::
	.string "Les DRESSEURS {STR_VAR_1} et\n{STR_VAR_2} étaient face à face dans\lun COMBAT {STR_VAR_3}.\pCe match s'est terminé sur une\nvictoire de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Dans le combat, le {STR_VAR_2} de\n{STR_VAR_1} a très efficacement\lutilisé {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "Le {STR_VAR_2} de {STR_VAR_1} n'a pas\nsu montrer son vrai niveau.$"

gTVPokemonBattleUpdateText04::
	.string "Bravo pour votre victoire,\n{STR_VAR_1}!\pQuant à vous, {STR_VAR_2},\nnous espérons que vous ferez mieux\lla prochaine fois!\pAinsi se termine cette émission\nd'«INFOS COMBATS POKéMON»!$"

gTVPokemonBattleUpdateText05::
	.string "Les équipes des DRESSEURS {STR_VAR_1}\net {STR_VAR_2} se sont affrontées en\lCOMBAT MULTI.\pCe match s'est terminé sur une\nvictoire de l'équipe de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText06::
	.string "Dans le combat, le {STR_VAR_2} de\nl'équipe de {STR_VAR_1} a très\lefficacement utilisé {STR_VAR_3}!$"

gTVPokemonBattleUpdateText07::
	.string "Le {STR_VAR_3} n'a pas su montrer\nson vrai niveau face à l'équipe de\l{STR_VAR_2}.\pFélicitations sur la victoire de votre\néquipe, {STR_VAR_1}!\pQuand à vous {STR_VAR_2},\nnous espérons que votre équipe\lfera mieux la prochaine fois!\pAinsi se termine cette émission\nd'«INFOS COMBATS POKéMON»!$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "INES: Oh! Nous venons de repérer un\nDRESSEUR qui a l'air costaud!\pOK, caméra, action!\nAllons l'interviewer.$"

GabbyAndTy_Text_GabbyIntro:
	.string "INES: Oh! Tu es {PLAYER}! Bonjour!\nTu te souviens de nous?\pNous sommes devenus bien plus forts.\nOn peut te montrer? Caméra, ça tourne!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "INES: Je ne me suis pas trompée!\nJ'ai découvert un DRESSEUR incroyable!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "INES: Incroyable! Génial!\nQui es-tu?!\pJe savais qu'on était sur un bon coup\nquand on est tombés sur toi!\pOh, laisse-moi t'expliquer. Nous\nvoyageons un peu partout pour\linterviewer des DRESSEURS.\pPourrais-tu nous accorder un peu de\nton temps pour une interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "INES: «{STR_VAR_1}!»\pTu te souviens? C'est ta conclusion\naprès ton dernier combat.\pJe n'oublie jamais ce genre de truc!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "La dernière fois qu'on s'est battus,\ntu nous as écrasés avant qu'on ait eu\lle temps de dire ouf…\pAlors, qu'en penses-tu?\nTu veux qu'on t'interviewe de nouveau?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "La dernière fois qu'on s'est battus, tu\nnous as jeté une POKé BALL, non?\pNous étions si choqués. Nous en avons\nparlé à tout le monde. Tout le monde!\pAlors, qu'en penses-tu?\nTu veux qu'on t'interviewe de nouveau?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "La dernière fois qu'on s'est battus, tu\nas utilisé tes objets avec brio.\pAlors, qu'en penses-tu?\nTu veux qu'on t'interviewe de nouveau?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "La dernière fois qu'on s'est battus, on\na réussi à éviter l'humiliation.\pAlors, qu'en penses-tu?\nTu veux qu'on t'interviewe de nouveau?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Alors, qu'en penses-tu?\nTu veux qu'on t'interviewe de nouveau?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Tu veux bien?\nMerci mille fois!\pBien, je voudrais que tu décrives\nta perception de notre combat.\lSois précis et concis. Allez!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "INES: Mmm, mouais!\nC'est une excellente conclusion!\pJ'ai l'impression qu'on va faire un tabac\navec cette émission de télé.\pIls vont sûrement la diffuser,\nalors regarde-nous souvent à la télé!\pBon, allez!\nA bientôt!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "INES: Oh…\pTant pis, mais n'abandonne pas! Nous\nallons continuer à suivre ton parcours!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "INES: Nous allons continuer à\nsuivre ton parcours!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "INES: Y a-t-il un vrai DRESSEUR, ici,\navec beaucoup de POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "INES: Ouah, tu es un sacré\npersonnage!\pTu as gagné en puissance depuis notre\ndernier combat. Et pas qu'un peu!\pNous avions raison quand nous avons\ndit que tu étais un DRESSEUR balèze.\pAlors, qu'en penses-tu?\nTu veux bien qu'on t'interviewe,\lcette fois?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "INES: Ça, c'était du combat!\nTu as pu tout filmer?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "GUY: Hé, mate un peu, là! Ce DRESSEUR\na l'air d'être balèze!\pOn tourne!$"

GabbyAndTy_Text_TyIntro:
	.string "GUY: Hé, mate un peu, là!\nJe me souviens de toi!\pJe vais filmer ce combat avec ma\ncaméra!$"

GabbyAndTy_Text_TyPostBattle:
	.string "GUY: Tu as ça dans le sang! J'ai une\nvidéo de premier choix, maintenant!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "GUY: Quoi? Tu n'as qu'un POKéMON?\nEt c'est tout?\pSi tu avais plus de POKéMON, ça me\nferait une super vidéo, mais bon…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "GUY: Ouais, on a repéré un super\nDRESSEUR. C'est un super scoop!$"

GabbyAndTy_Text_TyDefeat:
	.string "GUY: Ouais, j'ai tout.\nC'est dans la boîte!$"

gTVInSearchOfTrainersText00::
	.string "EN QUETE DE DRESSEURS…\pINES: Bonjour! Aujourd'hui, je suis\ndu côté de la {STR_VAR_1}.\pNous sommes sur le terrain pour essayer\nde repérer les talents qui montent.\pAujourd'hui, nous braquons notre\nobjectif sur le DRESSEUR {PLAYER}.\pQuelque chose à propos de ce DRESSEUR\na éveillé notre curiosité.$"

gTVInSearchOfTrainersText01::
	.string "Nous nous étions déjà battus contre\n{PLAYER}, mais nous pouvons vous jurer\lque sa technique s'est améliorée.\pJe savais que nous tenions un scoop\nquand nous avons repéré ce DRESSEUR!$"

gTVInSearchOfTrainersText02::
	.string "La meilleure façon de déterminer la\nforce d'un DRESSEUR est de…\pHeu, enfin, la façon la plus rapide est\nde se battre. C'est comme ça que\lnous avons commencé notre enquête!\p… …\pNous nous sommes donc battus contre\n{PLAYER}.\pAu cours de cette performance\néprouvante, nous avons été aplatis,\lécrasés et terriblement humiliés!\p{PLAYER} est d'une force redoutable…\pNous avons alors tenu à connaître ses\nimpressions sur le combat.$"

gTVInSearchOfTrainersText03::
	.string "L'enchaînement de {STR_VAR_1} et\nde {STR_VAR_3} était divin!\pLa vue de {STR_VAR_1} et de {STR_VAR_3}\nse soutenant mutuellement\len plein milieu du combat…\pCe sont des images qui font\nchaud au cœur!\pLe DRESSEUR a utilisé {STR_VAR_2}\npour clore le combat.\pL'attaque {STR_VAR_2} montre l'amitié\nentre {STR_VAR_1} et {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "… Après notre rencontre, j'ai perdu\ntoute confiance en moi.\pNous avons été battus avant même de\npouvoir frapper.\lOhhh… Sniff…\pEn tout cas, les combats de {PLAYER}\nsont des spectacles à ne pas manquer.\pJ'encourage les DRESSEURS confiants\nà défier {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Juste une précision.\nIl ne faut jamais jeter de POKé BALL\lpendant un combat de DRESSEURS!\p{PLAYER} a de toute évidence une grande\nforce, mais ne respecte pas les règles.\pUn message pour notre public:\pSi vous croisez {PLAYER},\ndites-le-lui!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} adore anticiper les actions de\nl'adversaire.\pLe timing de l'utilisation des objets\nétait tout simplement remarquable!$"

gTVInSearchOfTrainersText07::
	.string "Honnêtement, j'ai vraiment fait de\nmon mieux.\pMême si nous avons perdu, le\ncombat a été particulièrement tendu.\pMais si tu as du mal à me battre,\nc'est que tu as encore du chemin\là parcourir, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Après notre combat, nous avons demandé\nà {PLAYER} un bref résumé.\pLe DRESSEUR a répondu:\n«{STR_VAR_1}».\pLes POKéMON de {PLAYER} étaient\n{STR_VAR_2} et {STR_VAR_3}…\lEt «{STR_VAR_1}»…\pMmm! Voilà qui est profond! Il y a\nun sens caché derrière ça!\pCe n'est pas étonnant. C'est toujours\nintéressant d'écouter un bon DRESSEUR.\pVoilà, c'est tout pour aujourd'hui!\nNe ratez pas la prochaine émission!$"

ContestLadyShow_Text_Intro::
	.string "«INFOS CONCOURS POKéMON»\pANIMATRICE: Désolée d'interrompre\nvos programmes, et merci de nous\lretrouver!\pNous sommes en direct pour vous\nmontrer le résultat d'un CONCOURS\pcatégorie {STR_VAR_1} qui vient de\nse terminer!\pSpectateurs: ?!!!\pANIMATRICE: Oh, on dirait bien que\nles participants du CONCOURS se\ldirigent par ici!\pJe vais tenter de les interviewer en\ndirect pour vous!\pSpectateurs: ?!!!\n?!!!$"

ContestLadyShow_Text_Won::
	.string "ANIMATRICE: Excusez-moi!\nMerci de répondre à nos questions\len direct!\pPuis-je vous féliciter pour votre\nvictoire?\pQu'est-ce qui vous a permis de\nremporter cette victoire si\lbrillamment?\pCANON: Nous nous sommes donnés\nà fond aujourd'hui, mon {STR_VAR_2}\let moi!\pMais je suis sûre que nous n'aurions\npas réussi sans le soutien que nous\lavons reçu pendant le CONCOURS!\pANIMATRICE: Y a-t-il quelqu'un en\nparticulier avec qui vous souhaiteriez\lpartager votre joie?\pAllez-y, tous nos téléspectateurs vous\nregardent!\pCANON: Hé, tu es là?\p{STR_VAR_3}! Est-ce que tu regardes?\nOn a réussi!\lMerci, {STR_VAR_3}!$"

ContestLadyShow_Text_Lost::
	.string "ANIMATRICE: Excusez-moi!\nMerci de répondre à nos questions\len direct!\pVous devez être déçue par la tournure\ndes évènements. Avez-vous des\lcommentaires?\pCANON: Ça me brise le cœur…\nNous nous sommes pourtant donnés\là fond, mon {STR_VAR_2} et moi!\pMais j'ai l'impression d'avoir trahi\ntous ceux qui nous ont supportés.\pANIMATRICE: Je ne devrais pas le dire,\nmais il manquait quelque chose\là votre POKéMON.\pCANON: {STR_VAR_3}, je suis désolée…\nJe ferai mieux la prochaine fois…\lJe le jure… Sniff… sniff…\pSpectateurs: Vous avez vu?\nLa pauvre fille!\pANIMATRICE: Oh… oh…\nHum… C'est tout pour aujourd'hui!\lMerci de nous avoir suivis!$"

ContestLadyShow_Text_LostBadly::
	.string "ANMATRICE: Excusez-moi!\nMerci de répondre à nos questions\len direct!\pComment s'est passé ce CONCOURS\npour vous?\pCANON: Tout s'est mal passé…\nPour une raison qui m'échappe,\lmon {STR_VAR_2} n'a pas réussi à attirer\ll'attention du public.\pANIMATRICE: Je ne devrais pas le dire,\nmais il manquait quelque chose\là votre POKéMON.\pCANON: … … … … … …\n…Sniff… Ouin!!\pSpectateurs: Vous avez vu?\nLa pauvre fille!\pANIMATRICE: Oh… oh…\nHum… C'est tout pour aujourd'hui!\lMerci de nous avoir suivis!$"
